#!/bin/sh
# Generate what Rune compiles a program of the xc2:polyml configuration of
# tests/basis/run-matrix.sh with: Poly/ML's Basis Library and the shim that
# makes Poly/ML's compiler primitives and runtime functions of Rune's
# (tests/basis/xc2/README.md).
#   tests/basis/xc2/polyml/gen.sh OUTDIR POLYML      (RUNE: bin/rune)
# POLYML is Poly/ML's installation, whose basis directory holds the sources
# of its library (scripts/fetch-hosts.sh keeps them there), with basis.patch
# applied (XC2_POLYML_BASIS names a patched basis directory to take as it
# is instead, when working on the patch). Writes to OUTDIR:
#   prefix          the files a program compiles before its own, in order
#   src/NNNN-NAME.sml  the files of the library, in the order of its
#                   build.sml (order.awk), Poly/ML's extensions and calls of
#                   the runtime replaced (rewrite.awk)
#   stubs.sml       XC2PR: a value for every function of the runtime, which
#                   raises unless rts.sml makes it
#   lib             the part of Rune's library the shim needs (../trim-lib.sh)
set -eu

[ $# = 2 ] || { echo "usage: tests/basis/xc2/polyml/gen.sh OUTDIR POLYML" >&2; exit 2; }
mkdir -p "$1"
out=$(cd "$1" && pwd)
polyml=$(cd "$2" && pwd)
cd "$(dirname "$0")/../../../.."
here=$(pwd)/tests/basis/xc2/polyml
xc2=$(pwd)/tests/basis/xc2
[ -f "$polyml/basis/build.sml" ] || { echo "xc2/polyml/gen.sh: no sources in $polyml/basis" >&2; exit 2; }

if [ -n "${XC2_POLYML_BASIS:-}" ]; then basis=$XC2_POLYML_BASIS
else
  rm -rf "$out/basis"
  cp -R "$polyml/basis" "$out/basis"
  chmod -R u+w "$out/basis"
  (cd "$out" && patch -s -p1 < "$here/basis.patch")
  basis=$out/basis
fi

awk -f "$here/order.awk" "$polyml/basis/build.sml" > "$out/order"
rm -rf "$out/src"
mkdir -p "$out/src"
: > "$out/table"
: > "$out/files"
i=0
emit() { # emit FILE: FILE rewritten, as the next file of the program
  i=$((i + 1))
  dst=$out/src/$(printf '%04d' "$i")-$(basename "$1" | sed 's/\.\(ML\|sig\)$/.sml/')
  awk -v table="$out/table" -f "$here/rewrite.awk" "$1" > "$dst"
  echo "$dst" >> "$out/files"
}
while read -r f; do
  case $f in
    "@decl "*) echo "${f#@decl }" > "$out/decl$i.sml"; emit "$out/decl$i.sml" ;;
    *) emit "$basis/$f" ;;
  esac
done < "$out/order"
sort -u "$out/table" -o "$out/table"

# The stubs: a value for every function of the runtime the library calls,
# which raises XC2.Unimplemented when it is applied.
{
  echo "(* Generated by tests/basis/xc2/polyml/gen.sh -- do not edit. *)"
  echo "structure XC2PR ="
  echo "struct"
  awk '{ print "  val " $1 " = fn _ => XC2.unimplemented \"the runtime'"'"'s " $1 "\"" }' "$out/table"
  echo "  open XC2PRImpl"
  echo "end"
} > "$out/stubs.sml"
# the initial environment, after the shim (which is written with Rune's)
echo "open XC2PolyBuiltin" > "$out/open.sml"

# What a program compiles first: the shim (copied, so that a run compiles
# one version of it throughout), the stubs and the sources.
cp "$xc2/xc2.sml" "$here/mem.sml" "$here/prologue.sml" "$here/rts.sml" "$out/"
{
  for f in xc2.sml mem.sml prologue.sml rts.sml stubs.sml open.sml; do echo "$out/$f"; done
  cat "$out/files"
} > "$out/prefix"
: > "$out/flags"

# The part of Rune's library the shim needs, less the structures in it that
# Poly/ML lacks, so that a program that names one finds none, as on the
# host: Int64 (and Rune's FixedInt, which the prologue's replaces) and
# Real64, which real.sml binds beside Real
# shellcheck disable=SC2046
sh "$xc2/trim-lib.sh" "$out" $(sed 5q "$out/prefix")
lib=$out/lib/basis
rm -f "$lib/int64.sml" "$lib/seal_int64.sml"
sed -i -e '/^int64\.sml /d' -e '/^seal_int64\.sml /d' -e 's/ Real64 / /' "$lib/MANIFEST"
sed -i '/^structure Real64 = Real$/d' "$lib/real.sml"
sed -i '/^structure Real64 : REAL = Real64$/d' "$lib/seal_real.sml"
