(* The arbitraries of the Basis Library's monomorphic vectors, arrays,
   slices and two-dimensional arrays of every element type but characters and
   bytes, which text.sml, bytes.sml and arrays2.sml have
   (docs/plans/quickcheck.md, D8 and M8): `XArb.arb` is the arbitrary of the
   type of `X`. Most of these structures are optional, and not every compiler
   has them. *)

(* Implements: ARB_OF where type t = BoolVector.vector *)
structure BoolVectorArb = MonoVectorArbFn (structure V = BoolVector val elem = Arb.bool val name = "BoolVector")
(* Implements: ARB_OF where type t = BoolArray.array *)
structure BoolArrayArb = MonoArrayArbFn (structure A = BoolArray val elem = Arb.bool val name = "BoolArray")
(* Implements: ARB_OF where type t = BoolVectorSlice.slice *)
structure BoolVectorSliceArb =
  MonoVectorSliceArbFn (structure S = BoolVectorSlice val vector = BoolVectorArb.arb val name = "BoolVectorSlice")
(* Implements: ARB_OF where type t = BoolArraySlice.slice *)
structure BoolArraySliceArb =
  MonoArraySliceArbFn (structure S = BoolArraySlice val array = BoolArrayArb.arb val name = "BoolArraySlice")
(* Implements: ARB_OF where type t = BoolArray2.array *)
structure BoolArray2Arb = MonoArray2ArbFn (structure A = BoolArray2 val elem = Arb.bool val name = "BoolArray2")
(* Implements: ARB_OF where type t = IntVector.vector *)
structure IntVectorArb = MonoVectorArbFn (structure V = IntVector val elem = IntArb.arb val name = "IntVector")
(* Implements: ARB_OF where type t = IntArray.array *)
structure IntArrayArb = MonoArrayArbFn (structure A = IntArray val elem = IntArb.arb val name = "IntArray")
(* Implements: ARB_OF where type t = IntVectorSlice.slice *)
structure IntVectorSliceArb =
  MonoVectorSliceArbFn (structure S = IntVectorSlice val vector = IntVectorArb.arb val name = "IntVectorSlice")
(* Implements: ARB_OF where type t = IntArraySlice.slice *)
structure IntArraySliceArb =
  MonoArraySliceArbFn (structure S = IntArraySlice val array = IntArrayArb.arb val name = "IntArraySlice")
(* Implements: ARB_OF where type t = Int8Vector.vector *)
structure Int8VectorArb = MonoVectorArbFn (structure V = Int8Vector val elem = Int8Arb.arb val name = "Int8Vector")
(* Implements: ARB_OF where type t = Int8Array.array *)
structure Int8ArrayArb = MonoArrayArbFn (structure A = Int8Array val elem = Int8Arb.arb val name = "Int8Array")
(* Implements: ARB_OF where type t = Int8VectorSlice.slice *)
structure Int8VectorSliceArb =
  MonoVectorSliceArbFn (structure S = Int8VectorSlice val vector = Int8VectorArb.arb val name = "Int8VectorSlice")
(* Implements: ARB_OF where type t = Int8ArraySlice.slice *)
structure Int8ArraySliceArb =
  MonoArraySliceArbFn (structure S = Int8ArraySlice val array = Int8ArrayArb.arb val name = "Int8ArraySlice")
(* Implements: ARB_OF where type t = Int8Array2.array *)
structure Int8Array2Arb = MonoArray2ArbFn (structure A = Int8Array2 val elem = Int8Arb.arb val name = "Int8Array2")
(* Implements: ARB_OF where type t = Int16Vector.vector *)
structure Int16VectorArb = MonoVectorArbFn (structure V = Int16Vector val elem = Int16Arb.arb val name = "Int16Vector")
(* Implements: ARB_OF where type t = Int16Array.array *)
structure Int16ArrayArb = MonoArrayArbFn (structure A = Int16Array val elem = Int16Arb.arb val name = "Int16Array")
(* Implements: ARB_OF where type t = Int16VectorSlice.slice *)
structure Int16VectorSliceArb =
  MonoVectorSliceArbFn (structure S = Int16VectorSlice val vector = Int16VectorArb.arb val name = "Int16VectorSlice")
(* Implements: ARB_OF where type t = Int16ArraySlice.slice *)
structure Int16ArraySliceArb =
  MonoArraySliceArbFn (structure S = Int16ArraySlice val array = Int16ArrayArb.arb val name = "Int16ArraySlice")
(* Implements: ARB_OF where type t = Int16Array2.array *)
structure Int16Array2Arb = MonoArray2ArbFn (structure A = Int16Array2 val elem = Int16Arb.arb val name = "Int16Array2")
(* Implements: ARB_OF where type t = Int32Vector.vector *)
structure Int32VectorArb = MonoVectorArbFn (structure V = Int32Vector val elem = Int32Arb.arb val name = "Int32Vector")
(* Implements: ARB_OF where type t = Int32Array.array *)
structure Int32ArrayArb = MonoArrayArbFn (structure A = Int32Array val elem = Int32Arb.arb val name = "Int32Array")
(* Implements: ARB_OF where type t = Int32VectorSlice.slice *)
structure Int32VectorSliceArb =
  MonoVectorSliceArbFn (structure S = Int32VectorSlice val vector = Int32VectorArb.arb val name = "Int32VectorSlice")
(* Implements: ARB_OF where type t = Int32ArraySlice.slice *)
structure Int32ArraySliceArb =
  MonoArraySliceArbFn (structure S = Int32ArraySlice val array = Int32ArrayArb.arb val name = "Int32ArraySlice")
(* Implements: ARB_OF where type t = Int32Array2.array *)
structure Int32Array2Arb = MonoArray2ArbFn (structure A = Int32Array2 val elem = Int32Arb.arb val name = "Int32Array2")
(* Implements: ARB_OF where type t = Int64Vector.vector *)
structure Int64VectorArb = MonoVectorArbFn (structure V = Int64Vector val elem = Int64Arb.arb val name = "Int64Vector")
(* Implements: ARB_OF where type t = Int64Array.array *)
structure Int64ArrayArb = MonoArrayArbFn (structure A = Int64Array val elem = Int64Arb.arb val name = "Int64Array")
(* Implements: ARB_OF where type t = Int64VectorSlice.slice *)
structure Int64VectorSliceArb =
  MonoVectorSliceArbFn (structure S = Int64VectorSlice val vector = Int64VectorArb.arb val name = "Int64VectorSlice")
(* Implements: ARB_OF where type t = Int64ArraySlice.slice *)
structure Int64ArraySliceArb =
  MonoArraySliceArbFn (structure S = Int64ArraySlice val array = Int64ArrayArb.arb val name = "Int64ArraySlice")
(* Implements: ARB_OF where type t = Int64Array2.array *)
structure Int64Array2Arb = MonoArray2ArbFn (structure A = Int64Array2 val elem = Int64Arb.arb val name = "Int64Array2")
(* Implements: ARB_OF where type t = LargeIntVector.vector *)
structure LargeIntVectorArb = MonoVectorArbFn (structure V = LargeIntVector val elem = LargeIntArb.arb val name = "LargeIntVector")
(* Implements: ARB_OF where type t = LargeIntArray.array *)
structure LargeIntArrayArb = MonoArrayArbFn (structure A = LargeIntArray val elem = LargeIntArb.arb val name = "LargeIntArray")
(* Implements: ARB_OF where type t = LargeIntVectorSlice.slice *)
structure LargeIntVectorSliceArb =
  MonoVectorSliceArbFn (structure S = LargeIntVectorSlice val vector = LargeIntVectorArb.arb val name = "LargeIntVectorSlice")
(* Implements: ARB_OF where type t = LargeIntArraySlice.slice *)
structure LargeIntArraySliceArb =
  MonoArraySliceArbFn (structure S = LargeIntArraySlice val array = LargeIntArrayArb.arb val name = "LargeIntArraySlice")
(* Implements: ARB_OF where type t = LargeIntArray2.array *)
structure LargeIntArray2Arb = MonoArray2ArbFn (structure A = LargeIntArray2 val elem = LargeIntArb.arb val name = "LargeIntArray2")
(* Implements: ARB_OF where type t = RealVector.vector *)
structure RealVectorArb = MonoVectorArbFn (structure V = RealVector val elem = RealArb.arb val name = "RealVector")
(* Implements: ARB_OF where type t = RealArray.array *)
structure RealArrayArb = MonoArrayArbFn (structure A = RealArray val elem = RealArb.arb val name = "RealArray")
(* Implements: ARB_OF where type t = RealVectorSlice.slice *)
structure RealVectorSliceArb =
  MonoVectorSliceArbFn (structure S = RealVectorSlice val vector = RealVectorArb.arb val name = "RealVectorSlice")
(* Implements: ARB_OF where type t = RealArraySlice.slice *)
structure RealArraySliceArb =
  MonoArraySliceArbFn (structure S = RealArraySlice val array = RealArrayArb.arb val name = "RealArraySlice")
(* Implements: ARB_OF where type t = RealArray2.array *)
structure RealArray2Arb = MonoArray2ArbFn (structure A = RealArray2 val elem = RealArb.arb val name = "RealArray2")
(* Implements: ARB_OF where type t = Real32Vector.vector *)
structure Real32VectorArb = MonoVectorArbFn (structure V = Real32Vector val elem = Real32Arb.arb val name = "Real32Vector")
(* Implements: ARB_OF where type t = Real32Array.array *)
structure Real32ArrayArb = MonoArrayArbFn (structure A = Real32Array val elem = Real32Arb.arb val name = "Real32Array")
(* Implements: ARB_OF where type t = Real32VectorSlice.slice *)
structure Real32VectorSliceArb =
  MonoVectorSliceArbFn (structure S = Real32VectorSlice val vector = Real32VectorArb.arb val name = "Real32VectorSlice")
(* Implements: ARB_OF where type t = Real32ArraySlice.slice *)
structure Real32ArraySliceArb =
  MonoArraySliceArbFn (structure S = Real32ArraySlice val array = Real32ArrayArb.arb val name = "Real32ArraySlice")
(* Implements: ARB_OF where type t = Real32Array2.array *)
structure Real32Array2Arb = MonoArray2ArbFn (structure A = Real32Array2 val elem = Real32Arb.arb val name = "Real32Array2")
(* Implements: ARB_OF where type t = Real64Vector.vector *)
structure Real64VectorArb = MonoVectorArbFn (structure V = Real64Vector val elem = Real64Arb.arb val name = "Real64Vector")
(* Implements: ARB_OF where type t = Real64Array.array *)
structure Real64ArrayArb = MonoArrayArbFn (structure A = Real64Array val elem = Real64Arb.arb val name = "Real64Array")
(* Implements: ARB_OF where type t = Real64VectorSlice.slice *)
structure Real64VectorSliceArb =
  MonoVectorSliceArbFn (structure S = Real64VectorSlice val vector = Real64VectorArb.arb val name = "Real64VectorSlice")
(* Implements: ARB_OF where type t = Real64ArraySlice.slice *)
structure Real64ArraySliceArb =
  MonoArraySliceArbFn (structure S = Real64ArraySlice val array = Real64ArrayArb.arb val name = "Real64ArraySlice")
(* Implements: ARB_OF where type t = Real64Array2.array *)
structure Real64Array2Arb = MonoArray2ArbFn (structure A = Real64Array2 val elem = Real64Arb.arb val name = "Real64Array2")
(* Implements: ARB_OF where type t = LargeRealVector.vector *)
structure LargeRealVectorArb = MonoVectorArbFn (structure V = LargeRealVector val elem = LargeRealArb.arb val name = "LargeRealVector")
(* Implements: ARB_OF where type t = LargeRealArray.array *)
structure LargeRealArrayArb = MonoArrayArbFn (structure A = LargeRealArray val elem = LargeRealArb.arb val name = "LargeRealArray")
(* Implements: ARB_OF where type t = LargeRealVectorSlice.slice *)
structure LargeRealVectorSliceArb =
  MonoVectorSliceArbFn (structure S = LargeRealVectorSlice val vector = LargeRealVectorArb.arb val name = "LargeRealVectorSlice")
(* Implements: ARB_OF where type t = LargeRealArraySlice.slice *)
structure LargeRealArraySliceArb =
  MonoArraySliceArbFn (structure S = LargeRealArraySlice val array = LargeRealArrayArb.arb val name = "LargeRealArraySlice")
(* Implements: ARB_OF where type t = LargeRealArray2.array *)
structure LargeRealArray2Arb = MonoArray2ArbFn (structure A = LargeRealArray2 val elem = LargeRealArb.arb val name = "LargeRealArray2")
(* Implements: ARB_OF where type t = WordVector.vector *)
structure WordVectorArb = MonoVectorArbFn (structure V = WordVector val elem = WordArb.arb val name = "WordVector")
(* Implements: ARB_OF where type t = WordArray.array *)
structure WordArrayArb = MonoArrayArbFn (structure A = WordArray val elem = WordArb.arb val name = "WordArray")
(* Implements: ARB_OF where type t = WordVectorSlice.slice *)
structure WordVectorSliceArb =
  MonoVectorSliceArbFn (structure S = WordVectorSlice val vector = WordVectorArb.arb val name = "WordVectorSlice")
(* Implements: ARB_OF where type t = WordArraySlice.slice *)
structure WordArraySliceArb =
  MonoArraySliceArbFn (structure S = WordArraySlice val array = WordArrayArb.arb val name = "WordArraySlice")
(* Implements: ARB_OF where type t = WordArray2.array *)
structure WordArray2Arb = MonoArray2ArbFn (structure A = WordArray2 val elem = WordArb.arb val name = "WordArray2")
(* Implements: ARB_OF where type t = Word16Vector.vector *)
structure Word16VectorArb = MonoVectorArbFn (structure V = Word16Vector val elem = Word16Arb.arb val name = "Word16Vector")
(* Implements: ARB_OF where type t = Word16Array.array *)
structure Word16ArrayArb = MonoArrayArbFn (structure A = Word16Array val elem = Word16Arb.arb val name = "Word16Array")
(* Implements: ARB_OF where type t = Word16VectorSlice.slice *)
structure Word16VectorSliceArb =
  MonoVectorSliceArbFn (structure S = Word16VectorSlice val vector = Word16VectorArb.arb val name = "Word16VectorSlice")
(* Implements: ARB_OF where type t = Word16ArraySlice.slice *)
structure Word16ArraySliceArb =
  MonoArraySliceArbFn (structure S = Word16ArraySlice val array = Word16ArrayArb.arb val name = "Word16ArraySlice")
(* Implements: ARB_OF where type t = Word16Array2.array *)
structure Word16Array2Arb = MonoArray2ArbFn (structure A = Word16Array2 val elem = Word16Arb.arb val name = "Word16Array2")
(* Implements: ARB_OF where type t = Word32Vector.vector *)
structure Word32VectorArb = MonoVectorArbFn (structure V = Word32Vector val elem = Word32Arb.arb val name = "Word32Vector")
(* Implements: ARB_OF where type t = Word32Array.array *)
structure Word32ArrayArb = MonoArrayArbFn (structure A = Word32Array val elem = Word32Arb.arb val name = "Word32Array")
(* Implements: ARB_OF where type t = Word32VectorSlice.slice *)
structure Word32VectorSliceArb =
  MonoVectorSliceArbFn (structure S = Word32VectorSlice val vector = Word32VectorArb.arb val name = "Word32VectorSlice")
(* Implements: ARB_OF where type t = Word32ArraySlice.slice *)
structure Word32ArraySliceArb =
  MonoArraySliceArbFn (structure S = Word32ArraySlice val array = Word32ArrayArb.arb val name = "Word32ArraySlice")
(* Implements: ARB_OF where type t = Word32Array2.array *)
structure Word32Array2Arb = MonoArray2ArbFn (structure A = Word32Array2 val elem = Word32Arb.arb val name = "Word32Array2")
(* Implements: ARB_OF where type t = Word64Vector.vector *)
structure Word64VectorArb = MonoVectorArbFn (structure V = Word64Vector val elem = Word64Arb.arb val name = "Word64Vector")
(* Implements: ARB_OF where type t = Word64Array.array *)
structure Word64ArrayArb = MonoArrayArbFn (structure A = Word64Array val elem = Word64Arb.arb val name = "Word64Array")
(* Implements: ARB_OF where type t = Word64VectorSlice.slice *)
structure Word64VectorSliceArb =
  MonoVectorSliceArbFn (structure S = Word64VectorSlice val vector = Word64VectorArb.arb val name = "Word64VectorSlice")
(* Implements: ARB_OF where type t = Word64ArraySlice.slice *)
structure Word64ArraySliceArb =
  MonoArraySliceArbFn (structure S = Word64ArraySlice val array = Word64ArrayArb.arb val name = "Word64ArraySlice")
(* Implements: ARB_OF where type t = Word64Array2.array *)
structure Word64Array2Arb = MonoArray2ArbFn (structure A = Word64Array2 val elem = Word64Arb.arb val name = "Word64Array2")
(* Implements: ARB_OF where type t = LargeWordVector.vector *)
structure LargeWordVectorArb = MonoVectorArbFn (structure V = LargeWordVector val elem = LargeWordArb.arb val name = "LargeWordVector")
(* Implements: ARB_OF where type t = LargeWordArray.array *)
structure LargeWordArrayArb = MonoArrayArbFn (structure A = LargeWordArray val elem = LargeWordArb.arb val name = "LargeWordArray")
(* Implements: ARB_OF where type t = LargeWordVectorSlice.slice *)
structure LargeWordVectorSliceArb =
  MonoVectorSliceArbFn (structure S = LargeWordVectorSlice val vector = LargeWordVectorArb.arb val name = "LargeWordVectorSlice")
(* Implements: ARB_OF where type t = LargeWordArraySlice.slice *)
structure LargeWordArraySliceArb =
  MonoArraySliceArbFn (structure S = LargeWordArraySlice val array = LargeWordArrayArb.arb val name = "LargeWordArraySlice")
(* Implements: ARB_OF where type t = LargeWordArray2.array *)
structure LargeWordArray2Arb = MonoArray2ArbFn (structure A = LargeWordArray2 val elem = LargeWordArb.arb val name = "LargeWordArray2")
(* Implements: ARB_OF where type t = WideCharVector.vector *)
structure WideCharVectorArb = MonoVectorArbFn (structure V = WideCharVector val elem = WideCharArb.arb val name = "WideCharVector")
(* Implements: ARB_OF where type t = WideCharArray.array *)
structure WideCharArrayArb = MonoArrayArbFn (structure A = WideCharArray val elem = WideCharArb.arb val name = "WideCharArray")
(* Implements: ARB_OF where type t = WideCharVectorSlice.slice *)
structure WideCharVectorSliceArb =
  MonoVectorSliceArbFn (structure S = WideCharVectorSlice val vector = WideCharVectorArb.arb val name = "WideCharVectorSlice")
(* Implements: ARB_OF where type t = WideCharArraySlice.slice *)
structure WideCharArraySliceArb =
  MonoArraySliceArbFn (structure S = WideCharArraySlice val array = WideCharArrayArb.arb val name = "WideCharArraySlice")
(* Implements: ARB_OF where type t = WideCharArray2.array *)
structure WideCharArray2Arb = MonoArray2ArbFn (structure A = WideCharArray2 val elem = WideCharArb.arb val name = "WideCharArray2")
