(* src/opt/x64_layout.sml -- runeopt's templates for the layout of values and
   objects, generated by bin/runeopt-templates (runtime/register/jit/templates.c) from
   the JIT's macro-assembler (runtime/register/jit/masm.c): DO NOT EDIT; `make templates`
   after a change to masm.c, and `make check-templates` refuses a stale file.
   Each function prints, through `line`, what the macro-assembler emits for the
   operation, in runeopt's conventions (docs/native.md): s and d are the texts
   of frame-slot displacements (slotDisp), b and r registers by number (RAX ...),
   kind a name of rune-offsets.s, unless and slow labels, l a prefix for the
   labels an operation makes for itself (printed through line too). A value is
   one word and an immediate is its payload doubled and one more: the templates
   of ints, words, chars and constructor tags (oneImm ... setWord) work on the
   words in %rax and %rcx and clobber %rdx, and those of reals use %rdx and
   %r8; each takes the label of the slow path, where the primitive's C does
   what has no immediate. *)
structure X64Layout =
struct
  fun num (n : int) : string = if n < 0 then "-" ^ Int.toString (~n) else Int.toString n
  val RAX = 0 val RCX = 1 val RDX = 2 val RBX = 3 val RSI = 6 val RDI = 7
  val R8 = 8 val R9 = 9 val R10 = 10 val R11 = 11
  val regs64 = Vector.fromList ["%rax", "%rcx", "%rdx", "%rbx", "%rsp", "%rbp", "%rsi", "%rdi",
                                "%r8", "%r9", "%r10", "%r11", "%r12", "%r13", "%r14", "%r15"]
  val regs32 = Vector.fromList ["%eax", "%ecx", "%edx", "%ebx", "%esp", "%ebp", "%esi", "%edi",
                                "%r8d", "%r9d", "%r10d", "%r11d", "%r12d", "%r13d", "%r14d", "%r15d"]
  fun reg64 r = Vector.sub (regs64, r)
  fun reg32 r = Vector.sub (regs32, r)
  (* the sizes the frame and an object's fields are cut by, and the
     rounding of an object's payload (runtime/value.h) *)
  val valueSize = 8
  val valueShift = 3
  val headerSize = 8
  val payloadAlign = 8
  val payloadMin = 8
  (* the payloads `set` can write: those whose word a store of 32 bits holds;
     setWide writes the others through %rax *)
  val setMin = ~1073741824
  val setMax = 1073741823
  (* the displacement of frame slot i from (%r13,%rbp), and of field i from an object *)
  fun slotDisp i = num (valueSize * i)
  fun fieldDisp i = "OBJ_FIELDS+" ^ num (valueSize * i)
  (* the kinds, by number, for alloc *)
  val K_TUPLE = 1
  val K_CON = 2
  val K_CLOSURE = 3
  val K_STRING = 4
  val K_REF = 5
  val K_ARRAY = 6
  val K_EXN = 7
  val K_EXNCON = 8
  val K_REAL = 10
  val K_BOX = 11
  fun checkImm line (s, unless) =
    (line ("testb $1, " ^ s ^ "(%r13,%rbp)");
     line ("je " ^ unless))
  fun set line (d, v) =
    (line ("movq $" ^ num (1 + 2 * v) ^ ", " ^ d ^ "(%r13,%rbp)"))
  fun setWide line (d, v) =
    (line ("movabs $" ^ num (1 + 2 * v) ^ ", %rax");
     line ("mov %rax, " ^ d ^ "(%r13,%rbp)"))
  fun setImm line (d, r) =
    (line ("lea 1(" ^ reg64 r ^ "," ^ reg64 r ^ ",1), " ^ reg64 r);
     line ("mov " ^ reg64 r ^ ", " ^ d ^ "(%r13,%rbp)"))
  fun setBits line (d, r) =
    (line ("mov " ^ reg64 r ^ ", " ^ d ^ "(%r13,%rbp)"))
  fun loadBits line (r, s) =
    (line ("mov " ^ s ^ "(%r13,%rbp), " ^ reg64 r))
  fun loadPayload line (r, s) =
    (line ("mov " ^ s ^ "(%r13,%rbp), " ^ reg64 r);
     line ("sar $1, " ^ reg64 r))
  fun copy line (d, s) =
    (line ("movsd " ^ s ^ "(%r13,%rbp), %xmm0");
     line ("movsd %xmm0, " ^ d ^ "(%r13,%rbp)"))
  fun loadReal line (s, unless, l) =
    (line ("mov " ^ s ^ "(%r13,%rbp), %rdx");
     line ("test $1, %rdx");
     line ("je " ^ l ^ "_a");
     line ("mov %rdx, %r8");
     line ("shr $1, %r8");
     line ("and $1023, %r8");
     line ("test %r8, %r8");
     line ("je " ^ l ^ "_b");
     line ("cmp $1023, %r8");
     line ("jne " ^ l ^ "_c");
     line ("mov $2047, %r8");
     line ("jmp " ^ l ^ "_b");
     line (l ^ "_c:");
     line ("add $512, %r8");
     line (l ^ "_b:");
     line ("and $-2048, %rdx");
     line ("or %r8, %rdx");
     line ("ror $12, %rdx");
     line ("movq %rdx, %xmm0");
     line ("jmp " ^ l ^ "_d");
     line (l ^ "_a:");
     line ("test %rdx, %rdx");
     line ("je " ^ unless);
     line ("cmpb $K_REAL, OBJ_KIND(%rdx)");
     line ("jne " ^ unless);
     line ("movsd OBJ_FIELDS(%rdx), %xmm0");
     line (l ^ "_d:"))
  fun loadReal1 line (s, unless, l) =
    (line ("mov " ^ s ^ "(%r13,%rbp), %rdx");
     line ("test $1, %rdx");
     line ("je " ^ l ^ "_a");
     line ("mov %rdx, %r8");
     line ("shr $1, %r8");
     line ("and $1023, %r8");
     line ("test %r8, %r8");
     line ("je " ^ l ^ "_b");
     line ("cmp $1023, %r8");
     line ("jne " ^ l ^ "_c");
     line ("mov $2047, %r8");
     line ("jmp " ^ l ^ "_b");
     line (l ^ "_c:");
     line ("add $512, %r8");
     line (l ^ "_b:");
     line ("and $-2048, %rdx");
     line ("or %r8, %rdx");
     line ("ror $12, %rdx");
     line ("movq %rdx, %xmm1");
     line ("jmp " ^ l ^ "_d");
     line (l ^ "_a:");
     line ("test %rdx, %rdx");
     line ("je " ^ unless);
     line ("cmpb $K_REAL, OBJ_KIND(%rdx)");
     line ("jne " ^ unless);
     line ("movsd OBJ_FIELDS(%rdx), %xmm1");
     line (l ^ "_d:"))
  fun setReal line (d, slow, l) =
    (line ("movq %xmm0, %rdx");
     line ("ror $52, %rdx");
     line ("mov %rdx, %r8");
     line ("and $2047, %r8");
     line ("test %r8, %r8");
     line ("je " ^ l ^ "_a");
     line ("cmp $2047, %r8");
     line ("jne " ^ l ^ "_b");
     line ("mov $1023, %r8");
     line ("jmp " ^ l ^ "_a");
     line (l ^ "_b:");
     line ("sub $513, %r8");
     line ("cmp $1021, %r8");
     line ("ja " ^ slow);
     line ("add $1, %r8");
     line (l ^ "_a:");
     line ("and $-2048, %rdx");
     line ("lea 1(%rdx,%r8,2), %rdx");
     line ("mov %rdx, " ^ d ^ "(%r13,%rbp)"))
  fun testFalse line s =
    (line ("cmpq $1, " ^ s ^ "(%r13,%rbp)"))
  fun oneInt line (x, slow, l) =
    (line ("mov " ^ x ^ "(%r13,%rbp), %rax");
     line ("test $1, %rax");
     line ("je " ^ slow))
  fun oneWord line (x, slow, l) =
    (line ("mov " ^ x ^ "(%r13,%rbp), %rax");
     line ("test $1, %rax");
     line ("je " ^ slow))
  fun oneChar line (x, slow, l) =
    (line ("mov " ^ x ^ "(%r13,%rbp), %rax");
     line ("test $1, %rax");
     line ("je " ^ slow))
  fun twoInt line (x, y, slow, l) =
    (line ("mov " ^ x ^ "(%r13,%rbp), %rax");
     line ("mov " ^ y ^ "(%r13,%rbp), %rcx");
     line ("mov %rax, %rdx");
     line ("and %rcx, %rdx");
     line ("test $1, %rdx");
     line ("je " ^ slow))
  fun twoWord line (x, y, slow, l) =
    (line ("mov " ^ x ^ "(%r13,%rbp), %rax");
     line ("mov " ^ y ^ "(%r13,%rbp), %rcx");
     line ("mov %rax, %rdx");
     line ("and %rcx, %rdx");
     line ("test $1, %rdx");
     line ("je " ^ slow))
  fun twoChar line (x, y, slow, l) =
    (line ("mov " ^ x ^ "(%r13,%rbp), %rax");
     line ("mov " ^ y ^ "(%r13,%rbp), %rcx");
     line ("mov %rax, %rdx");
     line ("and %rcx, %rdx");
     line ("test $1, %rdx");
     line ("je " ^ slow))
  fun twoWords line (x, y, slow) =
    (line ("mov " ^ x ^ "(%r13,%rbp), %rax");
     line ("mov " ^ y ^ "(%r13,%rbp), %rcx");
     line ("mov %rax, %rdx");
     line ("and %rcx, %rdx");
     line ("test $1, %rdx");
     line ("je " ^ slow))
  fun setInt line (d, r, slow) =
    (line ("mov " ^ reg64 r ^ ", " ^ d ^ "(%r13,%rbp)"))
  fun setWord line (d, r, slow) =
    (line ("mov " ^ reg64 r ^ ", " ^ d ^ "(%r13,%rbp)"))
  fun setChar line (d, r, slow) =
    (line ("mov " ^ reg64 r ^ ", " ^ d ^ "(%r13,%rbp)"))
  fun setPayInt line (d, r, slow) =
    (line ("lea 1(" ^ reg64 r ^ "," ^ reg64 r ^ ",1), " ^ reg64 r);
     line ("mov " ^ reg64 r ^ ", " ^ d ^ "(%r13,%rbp)"))
  fun setPayWord line (d, r, slow) =
    (line ("lea 1(" ^ reg64 r ^ "," ^ reg64 r ^ ",1), " ^ reg64 r);
     line ("mov " ^ reg64 r ^ ", " ^ d ^ "(%r13,%rbp)"))
  fun intAdd line slow =
    (line ("lea -1(%rax), %rax");
     line ("add %rcx, %rax");
     line ("jo " ^ slow))
  fun intSub line slow =
    (line ("sub %rcx, %rax");
     line ("jo " ^ slow);
     line ("lea 1(%rax), %rax"))
  fun intMul line slow =
    (line ("sar $1, %rcx");
     line ("lea -1(%rax), %rax");
     line ("imul %rcx, %rax");
     line ("jo " ^ slow);
     line ("lea 1(%rax), %rax"))
  fun intNeg line slow =
    (line ("mov $2, %rcx");
     line ("sub %rax, %rcx");
     line ("jo " ^ slow);
     line ("mov %rcx, %rax"))
  fun intToChar line slow =
    (line ("cmp $511, %rax");
     line ("ja " ^ slow))
  fun wordAdd line slow =
    (line ("lea -1(%rax), %rax");
     line ("add %rcx, %rax"))
  fun wordSub line slow =
    (line ("sub %rcx, %rax");
     line ("lea 1(%rax), %rax"))
  fun wordMul line slow =
    (line ("shr $1, %rcx");
     line ("lea -1(%rax), %rax");
     line ("imul %rcx, %rax");
     line ("lea 1(%rax), %rax"))
  fun wordAnd line slow =
    (line ("and %rcx, %rax"))
  fun wordOr line slow =
    (line ("or %rcx, %rax"))
  fun wordXor line slow =
    (line ("xor %rcx, %rax");
     line ("lea 1(%rax), %rax"))
  fun wordNot line slow =
    (line ("neg %rax"))
  fun wordToInt line slow =
    (line ("test %rax, %rax");
     line ("js " ^ slow))
  fun wordToIntX line slow =
    ()
  fun intToWord line slow =
    ()
  fun untagInt line r =
    (line ("sar $1, " ^ reg64 r))
  fun untagWord line r =
    (line ("shr $1, " ^ reg64 r))
  fun loadObj line (r, s, kind, unless) =
    (line ("mov " ^ s ^ "(%r13,%rbp), " ^ reg64 r);
     line ("test $1, " ^ reg64 r);
     line ("jne " ^ unless);
     line ("cmpb $" ^ kind ^ ", OBJ_KIND(" ^ reg64 r ^ ")");
     line ("jne " ^ unless))
  fun loadTagOfCon line (r, s, unless, l) =
    (line ("mov " ^ s ^ "(%r13,%rbp), " ^ reg64 r);
     line ("test $1, " ^ reg64 r);
     line ("je " ^ l ^ "_a");
     line ("sar $1, " ^ reg64 r);
     line ("jmp " ^ l ^ "_b");
     line (l ^ "_a:");
     line ("cmpb $K_CON, OBJ_KIND(" ^ reg64 r ^ ")");
     line ("jne " ^ unless);
     line ("movzwl OBJ_CONTAG(" ^ reg64 r ^ "), " ^ reg32 r);
     line (l ^ "_b:"))
  fun alloc line (kind, contag, n, slow) =
    (line ("cmpq $0, VM_GC_STRESS(%r12)");
     line ("jne " ^ slow);
     line ("mov VM_HEAP_USED(%r12), %rax");
     line ("lea " ^ num (8 + 8 * n) ^ "(%rax), %rcx");
     line ("cmp VM_HEAP_SIZE(%r12), %rcx");
     line ("ja " ^ slow);
     line ("mov %rcx, VM_HEAP_USED(%r12)");
     line ("addq $" ^ num (8 + 8 * n) ^ ", VM_BYTES_ALLOCATED(%r12)");
     line ("addq $1, VM_OBJECTS_ALLOCATED(%r12)");
     line ("add VM_HEAP_FROM(%r12), %rax");
     line ("movl $" ^ num (kind + 65536 * contag) ^ ", (%rax)");
     line ("movl $" ^ num (n) ^ ", OBJ_LEN(%rax)"))
  fun storeField line (b, i, s) =
    (line ("movsd " ^ s ^ "(%r13,%rbp), %xmm0");
     line ("movsd %xmm0, OBJ_FIELDS+" ^ num (8 * i) ^ "(" ^ reg64 b ^ ")"))
  fun loadField line (d, b, i) =
    (line ("movsd OBJ_FIELDS+" ^ num (8 * i) ^ "(" ^ reg64 b ^ "), %xmm0");
     line ("movsd %xmm0, " ^ d ^ "(%r13,%rbp)"))
  fun loadLen line (r, b) =
    (line ("mov OBJ_LEN(" ^ reg64 b ^ "), " ^ reg32 r))
  fun checkLen line (b, n, unless) =
    (line ("cmpl $" ^ num (n) ^ ", OBJ_LEN(" ^ reg64 b ^ ")");
     line ("jne " ^ unless))
  fun loadContag line (r, b) =
    (line ("movzwl OBJ_CONTAG(" ^ reg64 b ^ "), " ^ reg32 r))
  fun needLen line (b, n, unless) =
    (line ("cmpl $" ^ num (n) ^ ", OBJ_LEN(" ^ reg64 b ^ ")");
     line ("jbe " ^ unless))
  fun storeFieldImm line (b, i, v) =
    (line ("movq $" ^ num (1 + 2 * v) ^ ", OBJ_FIELDS+" ^ num (8 * i) ^ "(" ^ reg64 b ^ ")"))
  fun loadFieldPayload line (r, b, i) =
    (line ("mov OBJ_FIELDS+" ^ num (8 * i) ^ "(" ^ reg64 b ^ "), " ^ reg64 r);
     line ("sar $1, " ^ reg64 r))
  fun element line () =
    (line ("shl $3, %rcx");
     line ("add %rcx, %rax"))
  fun stringByte line () =
    (line ("add %rcx, %rax");
     line ("movzbl OBJ_FIELDS(%rax), %ecx"))
  fun copyMem line (from, to) =
    (line ("movsd " ^ from ^ ", %xmm0");
     line ("movsd %xmm0, " ^ to))
end
