(* src/opt/x64_layout.sml -- runeopt's templates for the layout of values and
   objects, generated by bin/runeopt-templates (runtime/register/jit/templates.c) from
   the JIT's macro-assembler (runtime/register/jit/masm.c): DO NOT EDIT; `make templates`
   after a change to masm.c, and `make check-templates` refuses a stale file.
   Each function prints, through `line`, what the macro-assembler emits for the
   operation, in runeopt's conventions (docs/native.md): s and d are the texts
   of frame-slot displacements (slotDisp), b and r registers by number (RAX ...),
   tag and kind the names of rune-offsets.s, unless and slow labels, l a prefix
   for the labels an operation makes for itself (printed through line too). *)
structure X64Layout =
struct
  fun num (n : int) : string = if n < 0 then "-" ^ Int.toString (~n) else Int.toString n
  val RAX = 0 val RCX = 1 val RDX = 2 val RBX = 3 val RSI = 6 val RDI = 7
  val R8 = 8 val R9 = 9 val R10 = 10 val R11 = 11
  val regs64 = Vector.fromList ["%rax", "%rcx", "%rdx", "%rbx", "%rsp", "%rbp", "%rsi", "%rdi",
                                "%r8", "%r9", "%r10", "%r11", "%r12", "%r13", "%r14", "%r15"]
  val regs32 = Vector.fromList ["%eax", "%ecx", "%edx", "%ebx", "%esp", "%ebp", "%esi", "%edi",
                                "%r8d", "%r9d", "%r10d", "%r11d", "%r12d", "%r13d", "%r14d", "%r15d"]
  fun reg64 r = Vector.sub (regs64, r)
  fun reg32 r = Vector.sub (regs32, r)
  (* the sizes the frame and an object's fields are cut by, and the
     rounding of an object's payload (runtime/value.h) *)
  val valueSize = 16
  val valueShift = 4
  val headerSize = 8
  val payloadAlign = 16
  val payloadMin = 16
  (* the displacement of frame slot i from (%r13,%rbp), and of field i from an object *)
  fun slotDisp i = num (valueSize * i)
  fun fieldDisp i = "OBJ_FIELDS+" ^ num (valueSize * i)
  (* the kinds, by number, for alloc *)
  val K_TUPLE = 1
  val K_CON = 2
  val K_CLOSURE = 3
  val K_STRING = 4
  val K_REF = 5
  val K_ARRAY = 6
  val K_EXN = 7
  val K_EXNCON = 8
  fun checkTag line (s, tag, unless) =
    (line ("cmpb $" ^ tag ^ ", " ^ s ^ "(%r13,%rbp)");
     line ("jne " ^ unless))
  fun set line (d, tag, v) =
    (line ("movq $" ^ tag ^ ", " ^ d ^ "(%r13,%rbp)");
     line ("movq $" ^ num (v) ^ ", " ^ d ^ "+8(%r13,%rbp)"))
  fun setReg line (d, tag, r) =
    (line ("movq $" ^ tag ^ ", " ^ d ^ "(%r13,%rbp)");
     line ("mov " ^ reg64 r ^ ", " ^ d ^ "+8(%r13,%rbp)"))
  fun loadTag line (r, s) =
    (line ("movzbl " ^ s ^ "(%r13,%rbp), " ^ reg32 r))
  fun loadPayload line (r, s) =
    (line ("mov " ^ s ^ "+8(%r13,%rbp), " ^ reg64 r))
  fun copy line (d, s) =
    (line ("movdqu " ^ s ^ "(%r13,%rbp), %xmm0");
     line ("movdqu %xmm0, " ^ d ^ "(%r13,%rbp)"))
  fun loadReal line s =
    (line ("movsd " ^ s ^ "+8(%r13,%rbp), %xmm0"))
  fun loadReal1 line s =
    (line ("movsd " ^ s ^ "+8(%r13,%rbp), %xmm1"))
  fun setReal line d =
    (line ("movq $T_REAL, " ^ d ^ "(%r13,%rbp)");
     line ("movsd %xmm0, " ^ d ^ "+8(%r13,%rbp)"))
  fun cmpPayload line (r, s) =
    (line ("cmp " ^ s ^ "+8(%r13,%rbp), " ^ reg64 r))
  fun testFalse line s =
    (line ("cmpq $0, " ^ s ^ "+8(%r13,%rbp)"))
  fun loadObj line (r, s, kind, unless) =
    (line ("cmpb $T_PTR, " ^ s ^ "(%r13,%rbp)");
     line ("jne " ^ unless);
     line ("mov " ^ s ^ "+8(%r13,%rbp), " ^ reg64 r);
     line ("cmpb $" ^ kind ^ ", OBJ_KIND(" ^ reg64 r ^ ")");
     line ("jne " ^ unless))
  fun loadTagOfCon line (r, s, unless, l) =
    (line ("cmpb $T_CON0, " ^ s ^ "(%r13,%rbp)");
     line ("jne " ^ l ^ "_a");
     line ("mov " ^ s ^ "+8(%r13,%rbp), " ^ reg64 r);
     line ("jmp " ^ l ^ "_b");
     line (l ^ "_a:");
     line ("cmpb $T_PTR, " ^ s ^ "(%r13,%rbp)");
     line ("jne " ^ unless);
     line ("mov " ^ s ^ "+8(%r13,%rbp), " ^ reg64 r);
     line ("cmpb $K_CON, OBJ_KIND(" ^ reg64 r ^ ")");
     line ("jne " ^ unless);
     line ("movzwl OBJ_CONTAG(" ^ reg64 r ^ "), " ^ reg32 r);
     line (l ^ "_b:"))
  fun alloc line (kind, contag, n, slow) =
    (line ("cmpq $0, VM_GC_STRESS(%r12)");
     line ("jne " ^ slow);
     line ("mov VM_HEAP_USED(%r12), %rax");
     line ("lea " ^ num (8 + 16 * n) ^ "(%rax), %rcx");
     line ("cmp VM_HEAP_SIZE(%r12), %rcx");
     line ("ja " ^ slow);
     line ("mov %rcx, VM_HEAP_USED(%r12)");
     line ("addq $" ^ num (8 + 16 * n) ^ ", VM_BYTES_ALLOCATED(%r12)");
     line ("addq $1, VM_OBJECTS_ALLOCATED(%r12)");
     line ("add VM_HEAP_FROM(%r12), %rax");
     line ("movl $" ^ num (kind + 65536 * contag) ^ ", (%rax)");
     line ("movl $" ^ num (n) ^ ", OBJ_LEN(%rax)"))
  fun storeField line (b, i, s) =
    (line ("movdqu " ^ s ^ "(%r13,%rbp), %xmm0");
     line ("movdqu %xmm0, OBJ_FIELDS+" ^ num (16 * i) ^ "(" ^ reg64 b ^ ")"))
  fun loadField line (d, b, i) =
    (line ("movdqu OBJ_FIELDS+" ^ num (16 * i) ^ "(" ^ reg64 b ^ "), %xmm0");
     line ("movdqu %xmm0, " ^ d ^ "(%r13,%rbp)"))
  fun loadLen line (r, b) =
    (line ("mov OBJ_LEN(" ^ reg64 b ^ "), " ^ reg32 r))
  fun checkLen line (b, n, unless) =
    (line ("cmpl $" ^ num (n) ^ ", OBJ_LEN(" ^ reg64 b ^ ")");
     line ("jne " ^ unless))
  fun loadContag line (r, b) =
    (line ("movzwl OBJ_CONTAG(" ^ reg64 b ^ "), " ^ reg32 r))
  fun needLen line (b, n, unless) =
    (line ("cmpl $" ^ num (n) ^ ", OBJ_LEN(" ^ reg64 b ^ ")");
     line ("jbe " ^ unless))
  fun storeFieldImm line (b, i, tag, v) =
    (line ("movq $" ^ tag ^ ", OBJ_FIELDS+" ^ num (16 * i) ^ "(" ^ reg64 b ^ ")");
     line ("movq $" ^ num (v) ^ ", OBJ_FIELDS+" ^ num (8 + 16 * i) ^ "(" ^ reg64 b ^ ")"))
  fun loadFieldPayload line (r, b, i) =
    (line ("mov OBJ_FIELDS+" ^ num (8 + 16 * i) ^ "(" ^ reg64 b ^ "), " ^ reg64 r))
  fun element line () =
    (line ("shl $4, %rcx");
     line ("add %rcx, %rax"))
  fun stringByte line () =
    (line ("add %rcx, %rax");
     line ("movzbl OBJ_FIELDS(%rax), %ecx"))
  fun copyMem line (from, to) =
    (line ("movdqu " ^ from ^ ", %xmm0");
     line ("movdqu %xmm0, " ^ to))
end
