/* Generated by runeisa from src/isa -- do not edit.
   The cases of the interpreter's loop (vm/interp.c), each the body of its
   instruction in src/isa/stack.sml; a shared body is a function of
   vm/ops.h. */
CASE(HALT) {
    TRACE(OP_HALT, 0, 0);
    pc += 1;
    count++;
    SYNC();
    return 0;
    NEXT;
}
CASE(CONST) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(OP_CONST, a, 0);
    pc += 5;
    count++;
    PUSH(p->consts[a]);
    NEXT;
}
CASE(INT) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(OP_INT, a, 0);
    pc += 5;
    count++;
    PUSH(mk_int(a));
    NEXT;
}
CASE(UNIT) {
    TRACE(OP_UNIT, 0, 0);
    pc += 1;
    count++;
    PUSH(mk_unit());
    NEXT;
}
CASE(CON0) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(OP_CON0, a, 0);
    pc += 5;
    count++;
    PUSH(mk_con0(a));
    NEXT;
}
CASE(LOCAL) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(OP_LOCAL, a, 0);
    pc += 5;
    count++;
    PUSH(LOCALV(a));
    NEXT;
}
CASE(SETLOCAL) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(OP_SETLOCAL, a, 0);
    pc += 5;
    count++;
    LOCALV(a) = POP();
    NEXT;
}
CASE(ENV) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(OP_ENV, a, 0);
    pc += 5;
    count++;
    Obj *c = FRAME->closure;
    if (!c || (uint32_t)a + 1 >= c->len) FATAL("environment slot %d out of range", a);
    PUSH(OBJ_FIELDS(c)[a + 1]);
    NEXT;
}
CASE(SELF) {
    TRACE(OP_SELF, 0, 0);
    pc += 1;
    count++;
    if (!FRAME->closure) FATAL("SELF outside a closure");
    PUSH(mk_ptr(FRAME->closure));
    NEXT;
}
CASE(GLOBAL) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(OP_GLOBAL, a, 0);
    pc += 5;
    count++;
    if (!vm->global_set[a]) FATAL("global %d read before initialization", a);
    PUSH(vm->globals[a]);
    NEXT;
}
CASE(SETGLOBAL) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(OP_SETGLOBAL, a, 0);
    pc += 5;
    count++;
    vm->globals[a] = POP();
    vm->global_set[a] = 1;
    NEXT;
}
CASE(POP) {
    TRACE(OP_POP, 0, 0);
    pc += 1;
    count++;
    (void)POP();
    NEXT;
}
CASE(TUPLE) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(OP_TUPLE, a, 0);
    pc += 5;
    count++;
    SYNC();
    op_TUPLE(vm, a, 0);
    RELOAD();
    NEXT;
}
CASE(SELECT) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(OP_SELECT, a, 0);
    pc += 5;
    count++;
    Value v = POP();
    Obj *t = EXPECT(v, K_TUPLE, "tuple");
    if ((uint32_t)a >= t->len) FATAL("tuple index %d out of range", a);
    PUSH(OBJ_FIELDS(t)[a]);
    NEXT;
}
CASE(CON) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(OP_CON, a, 0);
    pc += 5;
    count++;
    SYNC();
    op_CON(vm, a, 0);
    RELOAD();
    NEXT;
}
CASE(DECON) {
    TRACE(OP_DECON, 0, 0);
    pc += 1;
    count++;
    Value v = POP();
    Obj *c = EXPECT(v, K_CON, "constructor with argument");
    PUSH(OBJ_FIELDS(c)[0]);
    NEXT;
}
CASE(CONTAG) {
    TRACE(OP_CONTAG, 0, 0);
    pc += 1;
    count++;
    Value v = POP();
    if (v.tag == T_CON0) PUSH(mk_int(v.u.i));
    else if (v.tag == T_PTR && v.u.p->kind == K_CON) PUSH(mk_int(v.u.p->contag));
    else FATAL("CONTAG on non-constructor");
    NEXT;
}
CASE(CLOSURE) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    TRACE(OP_CLOSURE, a, b);
    pc += 9;
    count++;
    SYNC();
    op_CLOSURE(vm, a, b);
    RELOAD();
    NEXT;
}
CASE(SETENV) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(OP_SETENV, a, 0);
    pc += 5;
    count++;
    SYNC();
    op_SETENV(vm, a, 0);
    RELOAD();
    NEXT;
}
CASE(CALL) {
    TRACE(OP_CALL, 0, 0);
    pc += 1;
    count++;
    Value arg = POP();
    Value cv = POP();
    Obj *c = EXPECT(cv, K_CLOSURE, "closure in call");
    int64_t fidx = OBJ_FIELDS(c)[0].u.i;
    if (fidx < 0 || (uint64_t)fidx >= p->nfuncs) FATAL("bad function index");
    Function *fn = &p->funcs[fidx];
    size_t at = (size_t)(sp - vm->stack);
    vm_push_frame(vm, (uint32_t)fidx, c, PC, at);
    size_t need = at + fn->nlocals + fn->maxstack;
    if (need > vm->stack_cap) vm_grow_stack(vm, need);
    Value *slot = vm->stack + at;
    slot[0] = arg;
    for (uint32_t i = 1; i < fn->nlocals; i++) slot[i] = mk_unit();
    ENTER(slot, fn);
    NEXT;
}
CASE(TAILCALL) {
    TRACE(OP_TAILCALL, 0, 0);
    pc += 1;
    count++;
    Value arg = POP();
    Value cv = POP();
    Obj *c = EXPECT(cv, K_CLOSURE, "closure in call");
    int64_t fidx = OBJ_FIELDS(c)[0].u.i;
    if (fidx < 0 || (uint64_t)fidx >= p->nfuncs) FATAL("bad function index");
    Function *fn = &p->funcs[fidx];
    size_t at = FRAME->base;
    FRAME->func = (uint32_t)fidx;
    FRAME->closure = c;
    size_t need = at + fn->nlocals + fn->maxstack;
    if (need > vm->stack_cap) vm_grow_stack(vm, need);
    Value *slot = vm->stack + at;
    slot[0] = arg;
    for (uint32_t i = 1; i < fn->nlocals; i++) slot[i] = mk_unit();
    ENTER(slot, fn);
    NEXT;
}
CASE(RET) {
    TRACE(OP_RET, 0, 0);
    pc += 1;
    count++;
    Value v = POP();
    size_t at = FRAME->base;
    uint32_t back = FRAME->ret_pc;
    if (vm->fp == 0) { sp = vm->stack + at; PUSH(v); JUMP_TO(back); SYNC(); return 0; }
    vm->fp--;
    sp = vm->stack + at;
    PUSH(v);
    RETURN_TO(back);
    NEXT;
}
CASE(JUMP) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(OP_JUMP, a, 0);
    pc += 5;
    count++;
    JUMP_TO(a);
    NEXT;
}
CASE(JUMPIFNOT) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(OP_JUMPIFNOT, a, 0);
    pc += 5;
    count++;
    Value v = POP();
    if (v.tag != T_CON0) FATAL("JUMPIFNOT on non-bool");
    if (v.u.i == 0) JUMP_TO(a);
    NEXT;
}
CASE(JUMPIF) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(OP_JUMPIF, a, 0);
    pc += 5;
    count++;
    Value v = POP();
    if (v.tag != T_CON0) FATAL("JUMPIF on non-bool");
    if (v.u.i != 0) JUMP_TO(a);
    NEXT;
}
CASE(PUSHHANDLER) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(OP_PUSHHANDLER, a, 0);
    pc += 5;
    count++;
    SYNC();
    vm_push_handler(vm, (uint32_t)a);
    NEXT;
}
CASE(POPHANDLER) {
    TRACE(OP_POPHANDLER, 0, 0);
    pc += 1;
    count++;
    if (vm->hp == 0) FATAL("POPHANDLER with no handler");
    vm->hp--;
    NEXT;
}
CASE(RAISE) {
    TRACE(OP_RAISE, 0, 0);
    pc += 1;
    count++;
    Value v = POP();
    if (v.tag != T_PTR || v.u.p->kind != K_EXN) FATAL("RAISE of non-exception");
    SYNC();
    vm_raise(vm, v);
    RELOAD();
    NEXT;
}
CASE(NEWEXN) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(OP_NEWEXN, a, 0);
    pc += 5;
    count++;
    SYNC();
    op_NEWEXN(vm, a, 0);
    RELOAD();
    NEXT;
}
CASE(BUILTINEXN) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(OP_BUILTINEXN, a, 0);
    pc += 5;
    count++;
    PUSH(mk_ptr(vm->builtin_exns[a]));
    NEXT;
}
CASE(MKEXN) {
    TRACE(OP_MKEXN, 0, 0);
    pc += 1;
    count++;
    SYNC();
    op_MKEXN(vm, 0, 0);
    RELOAD();
    NEXT;
}
CASE(EXNCON) {
    TRACE(OP_EXNCON, 0, 0);
    pc += 1;
    count++;
    Value v = POP();
    Obj *e = EXPECT(v, K_EXN, "exception");
    PUSH(OBJ_FIELDS(e)[0]);
    NEXT;
}
CASE(EXNARG) {
    TRACE(OP_EXNARG, 0, 0);
    pc += 1;
    count++;
    Value v = POP();
    Obj *e = EXPECT(v, K_EXN, "exception");
    PUSH(OBJ_FIELDS(e)[1]);
    NEXT;
}
CASE(PRIM) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(OP_PRIM, a, 0);
    pc += 5;
    count++;
    SYNC();
    /* A primitive that says PRIM_NEW_WORLD has put another program
       here (Runtime.restore); RELOAD takes its code again, and the
       pc with it. */
    (void)prim_table[a](vm);
    RELOAD();
    NEXT;
}
CASE(JUMPIFNOTTAG) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    TRACE(OP_JUMPIFNOTTAG, a, b);
    pc += 9;
    count++;
    /* CONTAG; INT t; PRIM poly_eq; JUMPIFNOT o, the test of a match
       against a constructor, in one */
    Value v = POP();
    int64_t tag = 0;
    if (v.tag == T_CON0) tag = v.u.i;
    else if (v.tag == T_PTR && v.u.p->kind == K_CON) tag = v.u.p->contag;
    else FATAL("JUMPIFNOTTAG on non-constructor");
    if (tag != b) JUMP_TO(a);
    NEXT;
}
CASE(TEELOCAL) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(OP_TEELOCAL, a, 0);
    pc += 5;
    count++;
    LOCALV(a) = TOP(0);
    NEXT;
}
