/* Generated by runeisa from src/isa -- do not edit.
   The cases of the interpreter's loop (vm/interp.c), each the body of its
   instruction in src/isa/stack.sml; a shared body is a function of
   vm/ops.h. */
case OP_HALT: {
    return 0;
    break;
}
case OP_CONST: {
    vm_push(vm, p->consts[a]);
    break;
}
case OP_INT: {
    vm_push(vm, mk_int(a));
    break;
}
case OP_UNIT: {
    vm_push(vm, mk_unit());
    break;
}
case OP_CON0: {
    vm_push(vm, mk_con0(a));
    break;
}
case OP_LOCAL: {
    vm_push(vm, vm->stack[fr->base + (size_t)a]);
    break;
}
case OP_SETLOCAL: {
    vm->stack[fr->base + (size_t)a] = vm_pop(vm);
    break;
}
case OP_ENV: {
    Obj *c = fr->closure;
    if (!c || (uint32_t)a + 1 >= c->len) vm_fatal(vm, "environment slot %d out of range", a);
    vm_push(vm, OBJ_FIELDS(c)[a + 1]);
    break;
}
case OP_SELF: {
    if (!fr->closure) vm_fatal(vm, "SELF outside a closure");
    vm_push(vm, mk_ptr(fr->closure));
    break;
}
case OP_GLOBAL: {
    if (!vm->global_set[a]) vm_fatal(vm, "global %d read before initialization", a);
    vm_push(vm, vm->globals[a]);
    break;
}
case OP_SETGLOBAL: {
    vm->globals[a] = vm_pop(vm);
    vm->global_set[a] = 1;
    break;
}
case OP_POP: {
    (void)vm_pop(vm);
    break;
}
case OP_TUPLE:
    op_TUPLE(vm, a, b);
    break;
case OP_SELECT: {
    Value v = vm_pop(vm);
    Obj *t = vm_expect_obj(vm, v, K_TUPLE, "tuple");
    if ((uint32_t)a >= t->len) vm_fatal(vm, "tuple index %d out of range", a);
    vm_push(vm, OBJ_FIELDS(t)[a]);
    break;
}
case OP_CON:
    op_CON(vm, a, b);
    break;
case OP_DECON: {
    Value v = vm_pop(vm);
    Obj *c = vm_expect_obj(vm, v, K_CON, "constructor with argument");
    vm_push(vm, OBJ_FIELDS(c)[0]);
    break;
}
case OP_CONTAG: {
    Value v = vm_pop(vm);
    if (v.tag == T_CON0) vm_push(vm, mk_int(v.u.i));
    else if (v.tag == T_PTR && v.u.p->kind == K_CON) vm_push(vm, mk_int(v.u.p->contag));
    else vm_fatal(vm, "CONTAG on non-constructor");
    break;
}
case OP_CLOSURE:
    op_CLOSURE(vm, a, b);
    break;
case OP_SETENV:
    op_SETENV(vm, a, b);
    break;
case OP_CALL: {
    Value arg = vm_pop(vm);
    Value cv = vm_pop(vm);
    Obj *c = vm_expect_obj(vm, cv, K_CLOSURE, "closure in call");
    int64_t fidx = OBJ_FIELDS(c)[0].u.i;
    if (fidx < 0 || (uint64_t)fidx >= p->nfuncs) vm_fatal(vm, "bad function index");
    Function *fn = &p->funcs[fidx];
    vm_push_frame(vm, (uint32_t)fidx, c, vm->pc, vm->sp);
    if (vm->sp + fn->nlocals > vm->stack_cap) vm_grow_stack(vm, vm->sp + fn->nlocals);
    Value *slot = &vm->stack[vm->sp];
    slot[0] = arg;
    for (uint32_t i = 1; i < fn->nlocals; i++) slot[i] = mk_unit();
    vm->sp += fn->nlocals;
    vm->pc = fn->code_offset;
    break;
}
case OP_TAILCALL: {
    Value arg = vm_pop(vm);
    Value cv = vm_pop(vm);
    Obj *c = vm_expect_obj(vm, cv, K_CLOSURE, "closure in call");
    int64_t fidx = OBJ_FIELDS(c)[0].u.i;
    if (fidx < 0 || (uint64_t)fidx >= p->nfuncs) vm_fatal(vm, "bad function index");
    Function *fn = &p->funcs[fidx];
    vm->sp = fr->base;
    fr->func = (uint32_t)fidx;
    fr->closure = c;
    if (vm->sp + fn->nlocals > vm->stack_cap) vm_grow_stack(vm, vm->sp + fn->nlocals);
    Value *slot = &vm->stack[vm->sp];
    slot[0] = arg;
    for (uint32_t i = 1; i < fn->nlocals; i++) slot[i] = mk_unit();
    vm->sp += fn->nlocals;
    vm->pc = fn->code_offset;
    break;
}
case OP_RET: {
    Value v = vm_pop(vm);
    vm->sp = fr->base;
    vm->pc = fr->ret_pc;
    if (vm->fp == 0) { vm_push(vm, v); return 0; }
    vm->fp--;
    vm_push(vm, v);
    break;
}
case OP_JUMP: {
    vm->pc = (uint32_t)a;
    break;
}
case OP_JUMPIFNOT: {
    Value v = vm_pop(vm);
    if (v.tag != T_CON0) vm_fatal(vm, "JUMPIFNOT on non-bool");
    if (v.u.i == 0) vm->pc = (uint32_t)a;
    break;
}
case OP_JUMPIF: {
    Value v = vm_pop(vm);
    if (v.tag != T_CON0) vm_fatal(vm, "JUMPIF on non-bool");
    if (v.u.i != 0) vm->pc = (uint32_t)a;
    break;
}
case OP_PUSHHANDLER: {
    vm_push_handler(vm, (uint32_t)a);
    break;
}
case OP_POPHANDLER: {
    if (vm->hp == 0) vm_fatal(vm, "POPHANDLER with no handler");
    vm->hp--;
    break;
}
case OP_RAISE: {
    Value v = vm_pop(vm);
    if (v.tag != T_PTR || v.u.p->kind != K_EXN) vm_fatal(vm, "RAISE of non-exception");
    vm_raise(vm, v);
    break;
}
case OP_NEWEXN:
    op_NEWEXN(vm, a, b);
    break;
case OP_BUILTINEXN: {
    vm_push(vm, mk_ptr(vm->builtin_exns[a]));
    break;
}
case OP_MKEXN:
    op_MKEXN(vm, a, b);
    break;
case OP_EXNCON: {
    Value v = vm_pop(vm);
    Obj *e = vm_expect_obj(vm, v, K_EXN, "exception");
    vm_push(vm, OBJ_FIELDS(e)[0]);
    break;
}
case OP_EXNARG: {
    Value v = vm_pop(vm);
    Obj *e = vm_expect_obj(vm, v, K_EXN, "exception");
    vm_push(vm, OBJ_FIELDS(e)[1]);
    break;
}
case OP_PRIM: {
    if (vm->sp < prim_arity[a]) vm_fatal(vm, "stack underflow in primitive %s", prim_names[a]);
    /* A primitive that says PRIM_NEW_WORLD has put another program
       here (Runtime.restore), so the code this loop is reading from
       has been freed: take it again, and the pc with it. */
    if (prim_table[a](vm) == PRIM_NEW_WORLD) code = p->code;
    break;
}
case OP_JUMPIFNOTTAG: {
    /* CONTAG; INT t; PRIM poly_eq; JUMPIFNOT o, the test of a match
       against a constructor, in one */
    Value v = vm_pop(vm);
    int64_t tag = 0;
    if (v.tag == T_CON0) tag = v.u.i;
    else if (v.tag == T_PTR && v.u.p->kind == K_CON) tag = v.u.p->contag;
    else vm_fatal(vm, "JUMPIFNOTTAG on non-constructor");
    if (tag != b) vm->pc = (uint32_t)a;
    break;
}
