/* Generated by runeisa from src/isa -- do not edit. */
#ifndef RUNE_OPCODES_H
#define RUNE_OPCODES_H

/* The version of the layout of an .rbc, and the fingerprint of the
   instruction set, which an .rbc and an image carry. */
#define RBC_VERSION 4
#define ISA_FINGERPRINT 0x00dc71ccu
#define ISA_FINGERPRINT_HEX "00dc71cc"

enum Opcode {
  OP_HALT = 0,  /* Stop execution. */
  OP_CONST = 1,  /* Push constant pool entry k. */
  OP_INT = 2,  /* Push the small integer i. */
  OP_UNIT = 3,  /* Push unit. */
  OP_CON0 = 4,  /* Push the nullary constructor with tag t. */
  OP_LOCAL = 5,  /* Push local slot l of the current frame. */
  OP_SETLOCAL = 6,  /* Pop the top of stack into local slot l. */
  OP_ENV = 7,  /* Push slot e of the current closure's environment. */
  OP_SELF = 8,  /* Push the currently executing closure. */
  OP_GLOBAL = 9,  /* Push global g. */
  OP_SETGLOBAL = 10,  /* Pop the top of stack into global g. */
  OP_POP = 11,  /* Discard the top of stack. */
  OP_TUPLE = 12,  /* Pop n values (first pushed is field 0) and push a tuple. */
  OP_SELECT = 13,  /* Pop a tuple and push its field i. */
  OP_CON = 14,  /* Pop a value and push constructor t applied to it. */
  OP_DECON = 15,  /* Pop a constructor value, of tag t, and push its argument; runevm --checked stops where the tag is another. */
  OP_CONTAG = 16,  /* Pop a constructor value and push its tag as an int. */
  OP_CLOSURE = 17,  /* Pop n values (first pushed is env slot 0) into a new closure of function f. */
  OP_SETENV = 18,  /* Pop value v, pop closure c, and set c.env[e] := v. */
  OP_CALL = 19,  /* Pop argument, pop closure, and call it. */
  OP_TAILCALL = 20,  /* Like CALL but the current frame is replaced. */
  OP_RET = 21,  /* Return the top of stack to the caller. */
  OP_JUMP = 22,  /* Jump to absolute code offset o. */
  OP_JUMPIFNOT = 23,  /* Pop a bool; jump to o if it is false. */
  OP_JUMPIF = 24,  /* Pop a bool; jump to o if it is true. */
  OP_PUSHHANDLER = 25,  /* Install an exception handler whose code starts at o. */
  OP_POPHANDLER = 26,  /* Remove the innermost exception handler. */
  OP_RAISE = 27,  /* Pop an exception value and raise it. */
  OP_NEWEXN = 28,  /* Create a fresh exception constructor named by string constant k. */
  OP_BUILTINEXN = 29,  /* Push builtin exception constructor i (see docs/bytecode.md). */
  OP_MKEXN = 30,  /* Pop payload, pop exception constructor, push the exception value. */
  OP_EXNCON = 31,  /* Pop an exception value and push its constructor. */
  OP_EXNARG = 32,  /* Pop an exception value and push its payload. */
  OP_PRIM = 33,  /* Invoke primitive p; pops its arguments and pushes the result. */
  OP_JUMPIFNOTTAG = 34,  /* Pop a constructor value; jump to o unless its tag is t. */
  OP_TEELOCAL = 35,  /* Store the top of stack into local slot l and leave it there: SETLOCAL l; LOCAL l in one. */
  OP_CALLK = 36,  /* Call function f, known, with the n values on top of the stack, which become its locals 0 to n-1; no closure. */
  OP_SWITCH = 37,  /* Pop a constructor value; jump to the target of the JUMP of its tag among the n that follow, or past them. */
  OP_TAILCALLK = 38,  /* Like CALLK, but the current frame is replaced. */
  OP__COUNT
};

static const char *const op_names[] = {
  "HALT",
  "CONST",
  "INT",
  "UNIT",
  "CON0",
  "LOCAL",
  "SETLOCAL",
  "ENV",
  "SELF",
  "GLOBAL",
  "SETGLOBAL",
  "POP",
  "TUPLE",
  "SELECT",
  "CON",
  "DECON",
  "CONTAG",
  "CLOSURE",
  "SETENV",
  "CALL",
  "TAILCALL",
  "RET",
  "JUMP",
  "JUMPIFNOT",
  "JUMPIF",
  "PUSHHANDLER",
  "POPHANDLER",
  "RAISE",
  "NEWEXN",
  "BUILTINEXN",
  "MKEXN",
  "EXNCON",
  "EXNARG",
  "PRIM",
  "JUMPIFNOTTAG",
  "TEELOCAL",
  "CALLK",
  "SWITCH",
  "TAILCALLK",
};

static const unsigned char op_nargs[] = {
  0,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  2,
  1,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  2,
  1,
  2,
  1,
  2,
};

/* What each opcode pops: a number (op_pops_fixed), the value of an
   operand (op_pops_operand, its position), or the arity of the
   primitive an operand names (op_pops_arity); -1 where not. The
   loader works out from these, and from what each pushes, how deep
   each function's stack goes (Function.maxstack). */
static const signed char op_pops_fixed[] = {
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  -1,
  1,
  1,
  1,
  1,
  -1,
  2,
  2,
  2,
  1,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  2,
  1,
  1,
  -1,
  1,
  1,
  -1,
  1,
  -1,
};
static const signed char op_pops_operand[] = {
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  0,
  -1,
  -1,
  -1,
  -1,
  1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  1,
  -1,
  1,
};
static const signed char op_pops_arity[] = {
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  0,
  -1,
  -1,
  -1,
  -1,
  -1,
};
static const unsigned char op_pushes[] = {
  0,
  1,
  1,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  1,
  1,
  0,
  0,
};

/* Where control goes after each (src/isa/isa.sml, flow). */
enum OpFlow { FLOW_NEXT, FLOW_BRANCH, FLOW_JUMP, FLOW_CALL, FLOW_TAILCALL, FLOW_RETURN, FLOW_RAISE, FLOW_HALT,
              FLOW_SWITCH };
static const unsigned char op_flow[] = {
  FLOW_HALT,
  FLOW_NEXT,
  FLOW_NEXT,
  FLOW_NEXT,
  FLOW_NEXT,
  FLOW_NEXT,
  FLOW_NEXT,
  FLOW_NEXT,
  FLOW_NEXT,
  FLOW_NEXT,
  FLOW_NEXT,
  FLOW_NEXT,
  FLOW_NEXT,
  FLOW_NEXT,
  FLOW_NEXT,
  FLOW_NEXT,
  FLOW_NEXT,
  FLOW_NEXT,
  FLOW_NEXT,
  FLOW_CALL,
  FLOW_TAILCALL,
  FLOW_RETURN,
  FLOW_JUMP,
  FLOW_BRANCH,
  FLOW_BRANCH,
  FLOW_NEXT,
  FLOW_NEXT,
  FLOW_RAISE,
  FLOW_NEXT,
  FLOW_NEXT,
  FLOW_NEXT,
  FLOW_NEXT,
  FLOW_NEXT,
  FLOW_NEXT,
  FLOW_BRANCH,
  FLOW_NEXT,
  FLOW_CALL,
  FLOW_SWITCH,
  FLOW_TAILCALL,
};

/* What each operand is, which says what the loader accepts for it
   (src/isa/isa.sml, kind). */
enum OperandKind {
  OPND_CONSTANT = 0,
  OPND_STRING_CONSTANT = 1,
  OPND_IMMEDIATE = 2,
  OPND_TAG = 3,
  OPND_LOCAL = 4,
  OPND_ENV_SLOT = 5,
  OPND_GLOBAL = 6,
  OPND_FUNCTION = 7,
  OPND_LABEL = 8,
  OPND_HANDLER_LABEL = 9,
  OPND_PRIMITIVE = 10,
  OPND_COUNT = 11,
  OPND_FIELD = 12,
  OPND_BUILTIN_EXN = 13,
};

/* The kind of each operand of each opcode, by position; 0 past the last. */
static const unsigned char op_kinds[][2] = {
  {0, 0},  /* HALT */
  {0, 0},  /* CONST */
  {2, 0},  /* INT */
  {0, 0},  /* UNIT */
  {3, 0},  /* CON0 */
  {4, 0},  /* LOCAL */
  {4, 0},  /* SETLOCAL */
  {5, 0},  /* ENV */
  {0, 0},  /* SELF */
  {6, 0},  /* GLOBAL */
  {6, 0},  /* SETGLOBAL */
  {0, 0},  /* POP */
  {11, 0},  /* TUPLE */
  {12, 0},  /* SELECT */
  {3, 0},  /* CON */
  {3, 0},  /* DECON */
  {0, 0},  /* CONTAG */
  {7, 11},  /* CLOSURE */
  {5, 0},  /* SETENV */
  {0, 0},  /* CALL */
  {0, 0},  /* TAILCALL */
  {0, 0},  /* RET */
  {8, 0},  /* JUMP */
  {8, 0},  /* JUMPIFNOT */
  {8, 0},  /* JUMPIF */
  {9, 0},  /* PUSHHANDLER */
  {0, 0},  /* POPHANDLER */
  {0, 0},  /* RAISE */
  {1, 0},  /* NEWEXN */
  {13, 0},  /* BUILTINEXN */
  {0, 0},  /* MKEXN */
  {0, 0},  /* EXNCON */
  {0, 0},  /* EXNARG */
  {10, 0},  /* PRIM */
  {8, 3},  /* JUMPIFNOTTAG */
  {4, 0},  /* TEELOCAL */
  {7, 11},  /* CALLK */
  {11, 0},  /* SWITCH */
  {7, 11},  /* TAILCALLK */
};

#endif
