/* Generated by scripts/generate.py; edit spec/opcodes.tsv. */
enum {
    OP_HALT = 0,
    OP_INT = 1,
    OP_BOOL = 2,
    OP_UNIT = 3,
    OP_STRING = 4,
    OP_BUILTIN = 5,
    OP_LOAD = 6,
    OP_STORE = 7,
    OP_POP = 8,
    OP_ADD = 9,
    OP_SUB = 10,
    OP_MUL = 11,
    OP_DIV = 12,
    OP_MOD = 13,
    OP_CONCAT = 14,
    OP_EQ = 15,
    OP_NE = 16,
    OP_LT = 17,
    OP_LE = 18,
    OP_GT = 19,
    OP_GE = 20,
    OP_CALL = 21,
    OP_JUMP = 22,
    OP_JUMP_FALSE = 23,
    OP_COUNT = 24
};
enum { ARG_NONE, ARG_INT, ARG_BOOL, ARG_CONSTANT, ARG_BUILTIN, ARG_LOCAL, ARG_TARGET };
static const unsigned char op_arg[] = {ARG_NONE,ARG_INT,ARG_BOOL,ARG_NONE,ARG_CONSTANT,ARG_BUILTIN,ARG_LOCAL,ARG_LOCAL,ARG_NONE,ARG_NONE,ARG_NONE,ARG_NONE,ARG_NONE,ARG_NONE,ARG_NONE,ARG_NONE,ARG_NONE,ARG_NONE,ARG_NONE,ARG_NONE,ARG_NONE,ARG_NONE,ARG_TARGET,ARG_TARGET};
static const unsigned char op_pops[] = {0,0,0,0,0,0,0,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,0,1};
static const unsigned char op_pushes[] = {0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0};
