/* Generated by scripts/gen-opcodes.sh from vm/opcodes.def -- do not edit. */
#ifndef RUNE_OPCODES_H
#define RUNE_OPCODES_H

enum Opcode {
  OP_HALT = 0,  /* Stop execution. */
  OP_CONST = 1,  /* Push constant pool entry k. */
  OP_INT = 2,  /* Push the small integer i. */
  OP_UNIT = 3,  /* Push unit. */
  OP_CON0 = 4,  /* Push the nullary constructor with tag t. */
  OP_LOCAL = 5,  /* Push local slot l of the current frame. */
  OP_SETLOCAL = 6,  /* Pop the top of stack into local slot l. */
  OP_ENV = 7,  /* Push slot e of the current closure's environment. */
  OP_SELF = 8,  /* Push the currently executing closure. */
  OP_GLOBAL = 9,  /* Push global g. */
  OP_SETGLOBAL = 10,  /* Pop the top of stack into global g. */
  OP_POP = 11,  /* Discard the top of stack. */
  OP_TUPLE = 12,  /* Pop n values (first pushed is field 0) and push a tuple. */
  OP_SELECT = 13,  /* Pop a tuple and push its field i. */
  OP_CON = 14,  /* Pop a value and push constructor t applied to it. */
  OP_DECON = 15,  /* Pop a constructor value and push its argument. */
  OP_CONTAG = 16,  /* Pop a constructor value and push its tag as an int. */
  OP_CLOSURE = 17,  /* Pop n values (first pushed is env slot 0) into a new closure of function f. */
  OP_SETENV = 18,  /* Pop value v, pop closure c, and set c.env[e] := v. */
  OP_CALL = 19,  /* Pop argument, pop closure, and call it. */
  OP_TAILCALL = 20,  /* Like CALL but the current frame is replaced. */
  OP_RET = 21,  /* Return the top of stack to the caller. */
  OP_JUMP = 22,  /* Jump to absolute code offset o. */
  OP_JUMPIFNOT = 23,  /* Pop a bool; jump to o if it is false. */
  OP_JUMPIF = 24,  /* Pop a bool; jump to o if it is true. */
  OP_PUSHHANDLER = 25,  /* Install an exception handler whose code starts at o. */
  OP_POPHANDLER = 26,  /* Remove the innermost exception handler. */
  OP_RAISE = 27,  /* Pop an exception value and raise it. */
  OP_NEWEXN = 28,  /* Create a fresh exception constructor named by string constant k. */
  OP_BUILTINEXN = 29,  /* Push builtin exception constructor i (see docs/bytecode.md). */
  OP_MKEXN = 30,  /* Pop payload, pop exception constructor, push the exception value. */
  OP_EXNCON = 31,  /* Pop an exception value and push its constructor. */
  OP_EXNARG = 32,  /* Pop an exception value and push its payload. */
  OP_PRIM = 33,  /* Invoke primitive p; pops its arguments and pushes the result. */
  OP__COUNT
};

static const char *const op_names[] = {
  "HALT",
  "CONST",
  "INT",
  "UNIT",
  "CON0",
  "LOCAL",
  "SETLOCAL",
  "ENV",
  "SELF",
  "GLOBAL",
  "SETGLOBAL",
  "POP",
  "TUPLE",
  "SELECT",
  "CON",
  "DECON",
  "CONTAG",
  "CLOSURE",
  "SETENV",
  "CALL",
  "TAILCALL",
  "RET",
  "JUMP",
  "JUMPIFNOT",
  "JUMPIF",
  "PUSHHANDLER",
  "POPHANDLER",
  "RAISE",
  "NEWEXN",
  "BUILTINEXN",
  "MKEXN",
  "EXNCON",
  "EXNARG",
  "PRIM",
};

static const unsigned char op_nargs[] = {
  0,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  1,
  1,
  0,
  1,
  1,
  1,
  0,
  0,
  2,
  1,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
};

#endif
