/* Generated by scripts/gen-opcodes.sh from vm/prims.def -- do not edit. */
#ifndef RUNE_PRIMS_TABLE_H
#define RUNE_PRIMS_TABLE_H

enum Prim {
  PRIM_poly_eq = 0,
  PRIM_ptr_eq = 1,
  PRIM_int_add = 2,
  PRIM_int_sub = 3,
  PRIM_int_mul = 4,
  PRIM_int_div = 5,
  PRIM_int_mod = 6,
  PRIM_int_quot = 7,
  PRIM_int_rem = 8,
  PRIM_int_neg = 9,
  PRIM_int_abs = 10,
  PRIM_int_lt = 11,
  PRIM_int_le = 12,
  PRIM_int_gt = 13,
  PRIM_int_ge = 14,
  PRIM_int_to_string = 15,
  PRIM_int_from_string = 16,
  PRIM_int_to_char = 17,
  PRIM_int_to_real = 18,
  PRIM_word_add = 19,
  PRIM_word_sub = 20,
  PRIM_word_mul = 21,
  PRIM_word_div = 22,
  PRIM_word_mod = 23,
  PRIM_word_lt = 24,
  PRIM_word_le = 25,
  PRIM_word_gt = 26,
  PRIM_word_ge = 27,
  PRIM_word_andb = 28,
  PRIM_word_orb = 29,
  PRIM_word_xorb = 30,
  PRIM_word_notb = 31,
  PRIM_word_lsl = 32,
  PRIM_word_lsr = 33,
  PRIM_word_to_int = 34,
  PRIM_word_to_int_x = 35,
  PRIM_word_from_int = 36,
  PRIM_word_to_string = 37,
  PRIM_real_add = 38,
  PRIM_real_sub = 39,
  PRIM_real_mul = 40,
  PRIM_real_div = 41,
  PRIM_real_neg = 42,
  PRIM_real_abs = 43,
  PRIM_real_lt = 44,
  PRIM_real_le = 45,
  PRIM_real_gt = 46,
  PRIM_real_ge = 47,
  PRIM_real_eq = 48,
  PRIM_real_floor = 49,
  PRIM_real_ceil = 50,
  PRIM_real_round = 51,
  PRIM_real_trunc = 52,
  PRIM_real_to_string = 53,
  PRIM_real_from_string = 54,
  PRIM_real_sqrt = 55,
  PRIM_real_exp = 56,
  PRIM_real_ln = 57,
  PRIM_real_sin = 58,
  PRIM_real_cos = 59,
  PRIM_real_tan = 60,
  PRIM_real_atan = 61,
  PRIM_real_atan2 = 62,
  PRIM_real_pow = 63,
  PRIM_real_is_nan = 64,
  PRIM_char_ord = 65,
  PRIM_char_lt = 66,
  PRIM_char_le = 67,
  PRIM_char_gt = 68,
  PRIM_char_ge = 69,
  PRIM_string_size = 70,
  PRIM_string_sub = 71,
  PRIM_string_concat = 72,
  PRIM_string_extract = 73,
  PRIM_string_lt = 74,
  PRIM_string_le = 75,
  PRIM_string_gt = 76,
  PRIM_string_ge = 77,
  PRIM_string_compare = 78,
  PRIM_string_from_char = 79,
  PRIM_string_implode = 80,
  PRIM_string_explode = 81,
  PRIM_string_concat_list = 82,
  PRIM_ref_new = 83,
  PRIM_ref_get = 84,
  PRIM_ref_set = 85,
  PRIM_array_new = 86,
  PRIM_array_length = 87,
  PRIM_array_sub = 88,
  PRIM_array_update = 89,
  PRIM_array_from_list = 90,
  PRIM_vector_from_list = 91,
  PRIM_vector_length = 92,
  PRIM_vector_sub = 93,
  PRIM_print = 94,
  PRIM_print_err = 95,
  PRIM_flush_out = 96,
  PRIM_input_line = 97,
  PRIM_input_all = 98,
  PRIM_exit = 99,
  PRIM_command_args = 100,
  PRIM_command_name = 101,
  PRIM__COUNT
};

static const char *const prim_names[] = {
  "poly_eq",
  "ptr_eq",
  "int_add",
  "int_sub",
  "int_mul",
  "int_div",
  "int_mod",
  "int_quot",
  "int_rem",
  "int_neg",
  "int_abs",
  "int_lt",
  "int_le",
  "int_gt",
  "int_ge",
  "int_to_string",
  "int_from_string",
  "int_to_char",
  "int_to_real",
  "word_add",
  "word_sub",
  "word_mul",
  "word_div",
  "word_mod",
  "word_lt",
  "word_le",
  "word_gt",
  "word_ge",
  "word_andb",
  "word_orb",
  "word_xorb",
  "word_notb",
  "word_lsl",
  "word_lsr",
  "word_to_int",
  "word_to_int_x",
  "word_from_int",
  "word_to_string",
  "real_add",
  "real_sub",
  "real_mul",
  "real_div",
  "real_neg",
  "real_abs",
  "real_lt",
  "real_le",
  "real_gt",
  "real_ge",
  "real_eq",
  "real_floor",
  "real_ceil",
  "real_round",
  "real_trunc",
  "real_to_string",
  "real_from_string",
  "real_sqrt",
  "real_exp",
  "real_ln",
  "real_sin",
  "real_cos",
  "real_tan",
  "real_atan",
  "real_atan2",
  "real_pow",
  "real_is_nan",
  "char_ord",
  "char_lt",
  "char_le",
  "char_gt",
  "char_ge",
  "string_size",
  "string_sub",
  "string_concat",
  "string_extract",
  "string_lt",
  "string_le",
  "string_gt",
  "string_ge",
  "string_compare",
  "string_from_char",
  "string_implode",
  "string_explode",
  "string_concat_list",
  "ref_new",
  "ref_get",
  "ref_set",
  "array_new",
  "array_length",
  "array_sub",
  "array_update",
  "array_from_list",
  "vector_from_list",
  "vector_length",
  "vector_sub",
  "print",
  "print_err",
  "flush_out",
  "input_line",
  "input_all",
  "exit",
  "command_args",
  "command_name",
};

static const unsigned char prim_arity[] = {
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  1,
  1,
  2,
  2,
  2,
  2,
  1,
  1,
  1,
  1,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  1,
  2,
  2,
  1,
  1,
  1,
  1,
  2,
  2,
  2,
  2,
  1,
  1,
  2,
  2,
  2,
  2,
  2,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  1,
  1,
  2,
  2,
  2,
  2,
  1,
  2,
  2,
  3,
  2,
  2,
  2,
  2,
  2,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  1,
  2,
  3,
  1,
  1,
  1,
  2,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
};

#define RUNE_PRIM_LIST(X) \
  X(poly_eq) \
  X(ptr_eq) \
  X(int_add) \
  X(int_sub) \
  X(int_mul) \
  X(int_div) \
  X(int_mod) \
  X(int_quot) \
  X(int_rem) \
  X(int_neg) \
  X(int_abs) \
  X(int_lt) \
  X(int_le) \
  X(int_gt) \
  X(int_ge) \
  X(int_to_string) \
  X(int_from_string) \
  X(int_to_char) \
  X(int_to_real) \
  X(word_add) \
  X(word_sub) \
  X(word_mul) \
  X(word_div) \
  X(word_mod) \
  X(word_lt) \
  X(word_le) \
  X(word_gt) \
  X(word_ge) \
  X(word_andb) \
  X(word_orb) \
  X(word_xorb) \
  X(word_notb) \
  X(word_lsl) \
  X(word_lsr) \
  X(word_to_int) \
  X(word_to_int_x) \
  X(word_from_int) \
  X(word_to_string) \
  X(real_add) \
  X(real_sub) \
  X(real_mul) \
  X(real_div) \
  X(real_neg) \
  X(real_abs) \
  X(real_lt) \
  X(real_le) \
  X(real_gt) \
  X(real_ge) \
  X(real_eq) \
  X(real_floor) \
  X(real_ceil) \
  X(real_round) \
  X(real_trunc) \
  X(real_to_string) \
  X(real_from_string) \
  X(real_sqrt) \
  X(real_exp) \
  X(real_ln) \
  X(real_sin) \
  X(real_cos) \
  X(real_tan) \
  X(real_atan) \
  X(real_atan2) \
  X(real_pow) \
  X(real_is_nan) \
  X(char_ord) \
  X(char_lt) \
  X(char_le) \
  X(char_gt) \
  X(char_ge) \
  X(string_size) \
  X(string_sub) \
  X(string_concat) \
  X(string_extract) \
  X(string_lt) \
  X(string_le) \
  X(string_gt) \
  X(string_ge) \
  X(string_compare) \
  X(string_from_char) \
  X(string_implode) \
  X(string_explode) \
  X(string_concat_list) \
  X(ref_new) \
  X(ref_get) \
  X(ref_set) \
  X(array_new) \
  X(array_length) \
  X(array_sub) \
  X(array_update) \
  X(array_from_list) \
  X(vector_from_list) \
  X(vector_length) \
  X(vector_sub) \
  X(print) \
  X(print_err) \
  X(flush_out) \
  X(input_line) \
  X(input_all) \
  X(exit) \
  X(command_args) \
  X(command_name)

#endif
