/* Generated by runeisa from src/isa -- do not edit. */
#ifndef RUNE_PRIMS_TABLE_H
#define RUNE_PRIMS_TABLE_H

enum Prim {
  PRIM_poly_eq = 0,
  PRIM_ptr_eq = 1,
  PRIM_int_add = 2,
  PRIM_int_sub = 3,
  PRIM_int_mul = 4,
  PRIM_int_div = 5,
  PRIM_int_mod = 6,
  PRIM_int_quot = 7,
  PRIM_int_rem = 8,
  PRIM_int_neg = 9,
  PRIM_int_abs = 10,
  PRIM_int_lt = 11,
  PRIM_int_le = 12,
  PRIM_int_gt = 13,
  PRIM_int_ge = 14,
  PRIM_int_to_string = 15,
  PRIM_int_from_string = 16,
  PRIM_int_to_char = 17,
  PRIM_int_to_real = 18,
  PRIM_word_add = 19,
  PRIM_word_sub = 20,
  PRIM_word_mul = 21,
  PRIM_word_div = 22,
  PRIM_word_mod = 23,
  PRIM_word_lt = 24,
  PRIM_word_le = 25,
  PRIM_word_gt = 26,
  PRIM_word_ge = 27,
  PRIM_word_andb = 28,
  PRIM_word_orb = 29,
  PRIM_word_xorb = 30,
  PRIM_word_notb = 31,
  PRIM_word_lsl = 32,
  PRIM_word_lsr = 33,
  PRIM_word_to_int = 34,
  PRIM_word_to_int_x = 35,
  PRIM_word_from_int = 36,
  PRIM_word_to_string = 37,
  PRIM_real_add = 38,
  PRIM_real_sub = 39,
  PRIM_real_mul = 40,
  PRIM_real_div = 41,
  PRIM_real_neg = 42,
  PRIM_real_abs = 43,
  PRIM_real_lt = 44,
  PRIM_real_le = 45,
  PRIM_real_gt = 46,
  PRIM_real_ge = 47,
  PRIM_real_eq = 48,
  PRIM_real_floor = 49,
  PRIM_real_ceil = 50,
  PRIM_real_round = 51,
  PRIM_real_trunc = 52,
  PRIM_real_to_string = 53,
  PRIM_real_from_string = 54,
  PRIM_real_sqrt = 55,
  PRIM_real_exp = 56,
  PRIM_real_ln = 57,
  PRIM_real_sin = 58,
  PRIM_real_cos = 59,
  PRIM_real_tan = 60,
  PRIM_real_atan = 61,
  PRIM_real_atan2 = 62,
  PRIM_real_pow = 63,
  PRIM_real_is_nan = 64,
  PRIM_char_ord = 65,
  PRIM_char_lt = 66,
  PRIM_char_le = 67,
  PRIM_char_gt = 68,
  PRIM_char_ge = 69,
  PRIM_string_size = 70,
  PRIM_string_sub = 71,
  PRIM_string_concat = 72,
  PRIM_string_extract = 73,
  PRIM_string_lt = 74,
  PRIM_string_le = 75,
  PRIM_string_gt = 76,
  PRIM_string_ge = 77,
  PRIM_string_compare = 78,
  PRIM_string_from_char = 79,
  PRIM_string_implode = 80,
  PRIM_string_explode = 81,
  PRIM_string_concat_list = 82,
  PRIM_ref_new = 83,
  PRIM_ref_get = 84,
  PRIM_ref_set = 85,
  PRIM_array_new = 86,
  PRIM_array_length = 87,
  PRIM_array_sub = 88,
  PRIM_array_update = 89,
  PRIM_array_from_list = 90,
  PRIM_vector_from_list = 91,
  PRIM_vector_length = 92,
  PRIM_vector_sub = 93,
  PRIM_print = 94,
  PRIM_print_err = 95,
  PRIM_flush_out = 96,
  PRIM_input_line = 97,
  PRIM_input_all = 98,
  PRIM_exit = 99,
  PRIM_command_args = 100,
  PRIM_command_name = 101,
  PRIM_file_open = 102,
  PRIM_file_close = 103,
  PRIM_file_write = 104,
  PRIM_file_flush = 105,
  PRIM_file_read_line = 106,
  PRIM_file_read_all = 107,
  PRIM_file_error = 108,
  PRIM_word_neg = 109,
  PRIM_exn_name = 110,
  PRIM_real_floor_r = 111,
  PRIM_real_ceil_r = 112,
  PRIM_real_trunc_r = 113,
  PRIM_real_round_r = 114,
  PRIM_real_sign_bit = 115,
  PRIM_real_copy_sign = 116,
  PRIM_real_frexp_man = 117,
  PRIM_real_frexp_exp = 118,
  PRIM_real_ldexp = 119,
  PRIM_real_next_after = 120,
  PRIM_real_rem = 121,
  PRIM_real_fmt_e = 122,
  PRIM_real_fmt_f = 123,
  PRIM_real_shortest = 124,
  PRIM_real_set_round = 125,
  PRIM_real_get_round = 126,
  PRIM_real_sinh = 127,
  PRIM_real_cosh = 128,
  PRIM_real_tanh = 129,
  PRIM_file_read_vec = 130,
  PRIM_file_avail = 131,
  PRIM_sys_errno = 132,
  PRIM_sys_error_msg = 133,
  PRIM_sys_error_name = 134,
  PRIM_sys_error_of_name = 135,
  PRIM_time_now = 136,
  PRIM_time_user = 137,
  PRIM_time_sys = 138,
  PRIM_time_sleep = 139,
  PRIM_time_gc_user = 140,
  PRIM_time_gc_sys = 141,
  PRIM_date_parts = 142,
  PRIM_date_seconds = 143,
  PRIM_date_offset = 144,
  PRIM_date_format = 145,
  PRIM_os_system = 146,
  PRIM_os_getenv = 147,
  PRIM_file_errno = 148,
  PRIM_os_mkdir = 149,
  PRIM_os_rmdir = 150,
  PRIM_os_chdir = 151,
  PRIM_os_getcwd = 152,
  PRIM_os_remove = 153,
  PRIM_os_rename = 154,
  PRIM_os_access = 155,
  PRIM_os_file_kind = 156,
  PRIM_os_link_kind = 157,
  PRIM_os_file_size = 158,
  PRIM_os_mod_time = 159,
  PRIM_os_set_time = 160,
  PRIM_os_read_link = 161,
  PRIM_os_real_path = 162,
  PRIM_os_tmp_name = 163,
  PRIM_os_file_id = 164,
  PRIM_os_open_dir = 165,
  PRIM_os_read_dir = 166,
  PRIM_os_rewind_dir = 167,
  PRIM_os_close_dir = 168,
  PRIM_os_desc_kind = 169,
  PRIM_os_poll = 170,
  PRIM_posix_const = 171,
  PRIM_posix_fork = 172,
  PRIM_posix_exec = 173,
  PRIM_posix_exece = 174,
  PRIM_posix_spawn = 175,
  PRIM_posix_waitpid = 176,
  PRIM_posix_kill = 177,
  PRIM_posix_alarm = 178,
  PRIM_posix_pause = 179,
  PRIM_posix_getpid = 180,
  PRIM_posix_getppid = 181,
  PRIM_posix_getuid = 182,
  PRIM_posix_geteuid = 183,
  PRIM_posix_getgid = 184,
  PRIM_posix_getegid = 185,
  PRIM_posix_setuid = 186,
  PRIM_posix_setgid = 187,
  PRIM_posix_getgroups = 188,
  PRIM_posix_getlogin = 189,
  PRIM_posix_getpgrp = 190,
  PRIM_posix_setsid = 191,
  PRIM_posix_setpgid = 192,
  PRIM_posix_uname = 193,
  PRIM_posix_times = 194,
  PRIM_posix_environ = 195,
  PRIM_posix_ctermid = 196,
  PRIM_posix_ttyname = 197,
  PRIM_posix_isatty = 198,
  PRIM_posix_sysconf = 199,
  PRIM_posix_openf = 200,
  PRIM_posix_close = 201,
  PRIM_posix_dup = 202,
  PRIM_posix_dup2 = 203,
  PRIM_posix_pipe = 204,
  PRIM_posix_read = 205,
  PRIM_posix_write = 206,
  PRIM_posix_lseek = 207,
  PRIM_posix_fsync = 208,
  PRIM_posix_fcntl = 209,
  PRIM_posix_ftruncate = 210,
  PRIM_posix_stat = 211,
  PRIM_posix_chmod = 212,
  PRIM_posix_chown = 213,
  PRIM_posix_link = 214,
  PRIM_posix_symlink = 215,
  PRIM_posix_mkfifo = 216,
  PRIM_posix_umask = 217,
  PRIM_posix_getpw = 218,
  PRIM_posix_getgr = 219,
  PRIM_socket_create = 220,
  PRIM_socket_pair = 221,
  PRIM_socket_bind = 222,
  PRIM_socket_connect = 223,
  PRIM_socket_listen = 224,
  PRIM_socket_accept = 225,
  PRIM_socket_send = 226,
  PRIM_socket_sendto = 227,
  PRIM_socket_recv = 228,
  PRIM_socket_recvfrom = 229,
  PRIM_socket_shutdown = 230,
  PRIM_socket_name = 231,
  PRIM_socket_peer = 232,
  PRIM_socket_getopt = 233,
  PRIM_socket_setopt = 234,
  PRIM_socket_inet_addr = 235,
  PRIM_socket_unix_addr = 236,
  PRIM_socket_addr_family = 237,
  PRIM_socket_inet_parts = 238,
  PRIM_socket_unix_path = 239,
  PRIM_netdb_host_byname = 240,
  PRIM_netdb_host_byaddr = 241,
  PRIM_netdb_hostname = 242,
  PRIM_netdb_proto_byname = 243,
  PRIM_netdb_proto_bynumber = 244,
  PRIM_netdb_serv_byname = 245,
  PRIM_netdb_serv_byport = 246,
  PRIM_file_descriptor = 247,
  PRIM_posix_exit = 248,
  PRIM_posix_lock = 249,
  PRIM_posix_pathconf = 250,
  PRIM_posix_utime = 251,
  PRIM_file_tell = 252,
  PRIM_file_seek = 253,
  PRIM_posix_tcgetattr = 254,
  PRIM_posix_tcsetattr = 255,
  PRIM_posix_tcop = 256,
  PRIM_real_to_bits = 257,
  PRIM_real_from_bits = 258,
  PRIM_socket_linger = 259,
  PRIM_socket_query = 260,
  PRIM_real_to_single = 261,
  PRIM_real_single_from_string = 262,
  PRIM_socket_inet6_addr = 263,
  PRIM_socket_inet6_parts = 264,
  PRIM_win_reg_open = 265,
  PRIM_win_reg_close = 266,
  PRIM_win_reg_delete = 267,
  PRIM_win_reg_enum = 268,
  PRIM_win_reg_query = 269,
  PRIM_win_reg_set = 270,
  PRIM_win_config = 271,
  PRIM_win_version = 272,
  PRIM_win_volume = 273,
  PRIM_win_find_executable = 274,
  PRIM_win_shell_execute = 275,
  PRIM_win_spawn = 276,
  PRIM_win_wait = 277,
  PRIM_win_dde_start = 278,
  PRIM_win_dde_execute = 279,
  PRIM_win_dde_stop = 280,
  PRIM_rt_instructions = 281,
  PRIM_rt_bytes = 282,
  PRIM_rt_objects = 283,
  PRIM_rt_collections = 284,
  PRIM_rt_live = 285,
  PRIM_rt_heap_size = 286,
  PRIM_rt_collect = 287,
  PRIM_rt_version = 288,
  PRIM_rt_trace = 289,
  PRIM_rt_save = 290,
  PRIM_rt_restore = 291,
  PRIM_int_order = 292,
  PRIM_word_order = 293,
  PRIM_char_order = 294,
  PRIM_string_order = 295,
  PRIM_imm_eq = 296,
  PRIM__COUNT
};

static const char *const prim_names[] = {
  "poly_eq",
  "ptr_eq",
  "int_add",
  "int_sub",
  "int_mul",
  "int_div",
  "int_mod",
  "int_quot",
  "int_rem",
  "int_neg",
  "int_abs",
  "int_lt",
  "int_le",
  "int_gt",
  "int_ge",
  "int_to_string",
  "int_from_string",
  "int_to_char",
  "int_to_real",
  "word_add",
  "word_sub",
  "word_mul",
  "word_div",
  "word_mod",
  "word_lt",
  "word_le",
  "word_gt",
  "word_ge",
  "word_andb",
  "word_orb",
  "word_xorb",
  "word_notb",
  "word_lsl",
  "word_lsr",
  "word_to_int",
  "word_to_int_x",
  "word_from_int",
  "word_to_string",
  "real_add",
  "real_sub",
  "real_mul",
  "real_div",
  "real_neg",
  "real_abs",
  "real_lt",
  "real_le",
  "real_gt",
  "real_ge",
  "real_eq",
  "real_floor",
  "real_ceil",
  "real_round",
  "real_trunc",
  "real_to_string",
  "real_from_string",
  "real_sqrt",
  "real_exp",
  "real_ln",
  "real_sin",
  "real_cos",
  "real_tan",
  "real_atan",
  "real_atan2",
  "real_pow",
  "real_is_nan",
  "char_ord",
  "char_lt",
  "char_le",
  "char_gt",
  "char_ge",
  "string_size",
  "string_sub",
  "string_concat",
  "string_extract",
  "string_lt",
  "string_le",
  "string_gt",
  "string_ge",
  "string_compare",
  "string_from_char",
  "string_implode",
  "string_explode",
  "string_concat_list",
  "ref_new",
  "ref_get",
  "ref_set",
  "array_new",
  "array_length",
  "array_sub",
  "array_update",
  "array_from_list",
  "vector_from_list",
  "vector_length",
  "vector_sub",
  "print",
  "print_err",
  "flush_out",
  "input_line",
  "input_all",
  "exit",
  "command_args",
  "command_name",
  "file_open",
  "file_close",
  "file_write",
  "file_flush",
  "file_read_line",
  "file_read_all",
  "file_error",
  "word_neg",
  "exn_name",
  "real_floor_r",
  "real_ceil_r",
  "real_trunc_r",
  "real_round_r",
  "real_sign_bit",
  "real_copy_sign",
  "real_frexp_man",
  "real_frexp_exp",
  "real_ldexp",
  "real_next_after",
  "real_rem",
  "real_fmt_e",
  "real_fmt_f",
  "real_shortest",
  "real_set_round",
  "real_get_round",
  "real_sinh",
  "real_cosh",
  "real_tanh",
  "file_read_vec",
  "file_avail",
  "sys_errno",
  "sys_error_msg",
  "sys_error_name",
  "sys_error_of_name",
  "time_now",
  "time_user",
  "time_sys",
  "time_sleep",
  "time_gc_user",
  "time_gc_sys",
  "date_parts",
  "date_seconds",
  "date_offset",
  "date_format",
  "os_system",
  "os_getenv",
  "file_errno",
  "os_mkdir",
  "os_rmdir",
  "os_chdir",
  "os_getcwd",
  "os_remove",
  "os_rename",
  "os_access",
  "os_file_kind",
  "os_link_kind",
  "os_file_size",
  "os_mod_time",
  "os_set_time",
  "os_read_link",
  "os_real_path",
  "os_tmp_name",
  "os_file_id",
  "os_open_dir",
  "os_read_dir",
  "os_rewind_dir",
  "os_close_dir",
  "os_desc_kind",
  "os_poll",
  "posix_const",
  "posix_fork",
  "posix_exec",
  "posix_exece",
  "posix_spawn",
  "posix_waitpid",
  "posix_kill",
  "posix_alarm",
  "posix_pause",
  "posix_getpid",
  "posix_getppid",
  "posix_getuid",
  "posix_geteuid",
  "posix_getgid",
  "posix_getegid",
  "posix_setuid",
  "posix_setgid",
  "posix_getgroups",
  "posix_getlogin",
  "posix_getpgrp",
  "posix_setsid",
  "posix_setpgid",
  "posix_uname",
  "posix_times",
  "posix_environ",
  "posix_ctermid",
  "posix_ttyname",
  "posix_isatty",
  "posix_sysconf",
  "posix_openf",
  "posix_close",
  "posix_dup",
  "posix_dup2",
  "posix_pipe",
  "posix_read",
  "posix_write",
  "posix_lseek",
  "posix_fsync",
  "posix_fcntl",
  "posix_ftruncate",
  "posix_stat",
  "posix_chmod",
  "posix_chown",
  "posix_link",
  "posix_symlink",
  "posix_mkfifo",
  "posix_umask",
  "posix_getpw",
  "posix_getgr",
  "socket_create",
  "socket_pair",
  "socket_bind",
  "socket_connect",
  "socket_listen",
  "socket_accept",
  "socket_send",
  "socket_sendto",
  "socket_recv",
  "socket_recvfrom",
  "socket_shutdown",
  "socket_name",
  "socket_peer",
  "socket_getopt",
  "socket_setopt",
  "socket_inet_addr",
  "socket_unix_addr",
  "socket_addr_family",
  "socket_inet_parts",
  "socket_unix_path",
  "netdb_host_byname",
  "netdb_host_byaddr",
  "netdb_hostname",
  "netdb_proto_byname",
  "netdb_proto_bynumber",
  "netdb_serv_byname",
  "netdb_serv_byport",
  "file_descriptor",
  "posix_exit",
  "posix_lock",
  "posix_pathconf",
  "posix_utime",
  "file_tell",
  "file_seek",
  "posix_tcgetattr",
  "posix_tcsetattr",
  "posix_tcop",
  "real_to_bits",
  "real_from_bits",
  "socket_linger",
  "socket_query",
  "real_to_single",
  "real_single_from_string",
  "socket_inet6_addr",
  "socket_inet6_parts",
  "win_reg_open",
  "win_reg_close",
  "win_reg_delete",
  "win_reg_enum",
  "win_reg_query",
  "win_reg_set",
  "win_config",
  "win_version",
  "win_volume",
  "win_find_executable",
  "win_shell_execute",
  "win_spawn",
  "win_wait",
  "win_dde_start",
  "win_dde_execute",
  "win_dde_stop",
  "rt_instructions",
  "rt_bytes",
  "rt_objects",
  "rt_collections",
  "rt_live",
  "rt_heap_size",
  "rt_collect",
  "rt_version",
  "rt_trace",
  "rt_save",
  "rt_restore",
  "int_order",
  "word_order",
  "char_order",
  "string_order",
  "imm_eq",
};

static const unsigned char prim_arity[] = {
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  1,
  1,
  2,
  2,
  2,
  2,
  1,
  1,
  1,
  1,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  1,
  2,
  2,
  1,
  1,
  1,
  1,
  2,
  2,
  2,
  2,
  1,
  1,
  2,
  2,
  2,
  2,
  2,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  1,
  1,
  2,
  2,
  2,
  2,
  1,
  2,
  2,
  3,
  2,
  2,
  2,
  2,
  2,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  1,
  2,
  3,
  1,
  1,
  1,
  2,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  1,
  2,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  1,
  1,
  2,
  2,
  2,
  2,
  2,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  1,
  3,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  3,
  1,
  1,
  1,
  1,
  3,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  3,
  1,
  1,
  3,
  3,
  5,
  2,
  2,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  3,
  1,
  1,
  2,
  1,
  2,
  2,
  3,
  1,
  3,
  2,
  3,
  3,
  4,
  2,
  2,
  2,
  1,
  2,
  2,
  3,
  3,
  2,
  2,
  2,
  1,
  3,
  4,
  3,
  3,
  2,
  1,
  1,
  3,
  4,
  2,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  1,
  1,
  6,
  3,
  3,
  1,
  2,
  1,
  3,
  3,
  1,
  1,
  3,
  2,
  1,
  1,
  2,
  1,
  4,
  1,
  3,
  3,
  2,
  4,
  1,
  1,
  1,
  1,
  3,
  3,
  1,
  2,
  4,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  2,
  2,
  2,
};

#define RUNE_PRIM_LIST(X) \
  X(poly_eq) \
  X(ptr_eq) \
  X(int_add) \
  X(int_sub) \
  X(int_mul) \
  X(int_div) \
  X(int_mod) \
  X(int_quot) \
  X(int_rem) \
  X(int_neg) \
  X(int_abs) \
  X(int_lt) \
  X(int_le) \
  X(int_gt) \
  X(int_ge) \
  X(int_to_string) \
  X(int_from_string) \
  X(int_to_char) \
  X(int_to_real) \
  X(word_add) \
  X(word_sub) \
  X(word_mul) \
  X(word_div) \
  X(word_mod) \
  X(word_lt) \
  X(word_le) \
  X(word_gt) \
  X(word_ge) \
  X(word_andb) \
  X(word_orb) \
  X(word_xorb) \
  X(word_notb) \
  X(word_lsl) \
  X(word_lsr) \
  X(word_to_int) \
  X(word_to_int_x) \
  X(word_from_int) \
  X(word_to_string) \
  X(real_add) \
  X(real_sub) \
  X(real_mul) \
  X(real_div) \
  X(real_neg) \
  X(real_abs) \
  X(real_lt) \
  X(real_le) \
  X(real_gt) \
  X(real_ge) \
  X(real_eq) \
  X(real_floor) \
  X(real_ceil) \
  X(real_round) \
  X(real_trunc) \
  X(real_to_string) \
  X(real_from_string) \
  X(real_sqrt) \
  X(real_exp) \
  X(real_ln) \
  X(real_sin) \
  X(real_cos) \
  X(real_tan) \
  X(real_atan) \
  X(real_atan2) \
  X(real_pow) \
  X(real_is_nan) \
  X(char_ord) \
  X(char_lt) \
  X(char_le) \
  X(char_gt) \
  X(char_ge) \
  X(string_size) \
  X(string_sub) \
  X(string_concat) \
  X(string_extract) \
  X(string_lt) \
  X(string_le) \
  X(string_gt) \
  X(string_ge) \
  X(string_compare) \
  X(string_from_char) \
  X(string_implode) \
  X(string_explode) \
  X(string_concat_list) \
  X(ref_new) \
  X(ref_get) \
  X(ref_set) \
  X(array_new) \
  X(array_length) \
  X(array_sub) \
  X(array_update) \
  X(array_from_list) \
  X(vector_from_list) \
  X(vector_length) \
  X(vector_sub) \
  X(print) \
  X(print_err) \
  X(flush_out) \
  X(input_line) \
  X(input_all) \
  X(exit) \
  X(command_args) \
  X(command_name) \
  X(file_open) \
  X(file_close) \
  X(file_write) \
  X(file_flush) \
  X(file_read_line) \
  X(file_read_all) \
  X(file_error) \
  X(word_neg) \
  X(exn_name) \
  X(real_floor_r) \
  X(real_ceil_r) \
  X(real_trunc_r) \
  X(real_round_r) \
  X(real_sign_bit) \
  X(real_copy_sign) \
  X(real_frexp_man) \
  X(real_frexp_exp) \
  X(real_ldexp) \
  X(real_next_after) \
  X(real_rem) \
  X(real_fmt_e) \
  X(real_fmt_f) \
  X(real_shortest) \
  X(real_set_round) \
  X(real_get_round) \
  X(real_sinh) \
  X(real_cosh) \
  X(real_tanh) \
  X(file_read_vec) \
  X(file_avail) \
  X(sys_errno) \
  X(sys_error_msg) \
  X(sys_error_name) \
  X(sys_error_of_name) \
  X(time_now) \
  X(time_user) \
  X(time_sys) \
  X(time_sleep) \
  X(time_gc_user) \
  X(time_gc_sys) \
  X(date_parts) \
  X(date_seconds) \
  X(date_offset) \
  X(date_format) \
  X(os_system) \
  X(os_getenv) \
  X(file_errno) \
  X(os_mkdir) \
  X(os_rmdir) \
  X(os_chdir) \
  X(os_getcwd) \
  X(os_remove) \
  X(os_rename) \
  X(os_access) \
  X(os_file_kind) \
  X(os_link_kind) \
  X(os_file_size) \
  X(os_mod_time) \
  X(os_set_time) \
  X(os_read_link) \
  X(os_real_path) \
  X(os_tmp_name) \
  X(os_file_id) \
  X(os_open_dir) \
  X(os_read_dir) \
  X(os_rewind_dir) \
  X(os_close_dir) \
  X(os_desc_kind) \
  X(os_poll) \
  X(posix_const) \
  X(posix_fork) \
  X(posix_exec) \
  X(posix_exece) \
  X(posix_spawn) \
  X(posix_waitpid) \
  X(posix_kill) \
  X(posix_alarm) \
  X(posix_pause) \
  X(posix_getpid) \
  X(posix_getppid) \
  X(posix_getuid) \
  X(posix_geteuid) \
  X(posix_getgid) \
  X(posix_getegid) \
  X(posix_setuid) \
  X(posix_setgid) \
  X(posix_getgroups) \
  X(posix_getlogin) \
  X(posix_getpgrp) \
  X(posix_setsid) \
  X(posix_setpgid) \
  X(posix_uname) \
  X(posix_times) \
  X(posix_environ) \
  X(posix_ctermid) \
  X(posix_ttyname) \
  X(posix_isatty) \
  X(posix_sysconf) \
  X(posix_openf) \
  X(posix_close) \
  X(posix_dup) \
  X(posix_dup2) \
  X(posix_pipe) \
  X(posix_read) \
  X(posix_write) \
  X(posix_lseek) \
  X(posix_fsync) \
  X(posix_fcntl) \
  X(posix_ftruncate) \
  X(posix_stat) \
  X(posix_chmod) \
  X(posix_chown) \
  X(posix_link) \
  X(posix_symlink) \
  X(posix_mkfifo) \
  X(posix_umask) \
  X(posix_getpw) \
  X(posix_getgr) \
  X(socket_create) \
  X(socket_pair) \
  X(socket_bind) \
  X(socket_connect) \
  X(socket_listen) \
  X(socket_accept) \
  X(socket_send) \
  X(socket_sendto) \
  X(socket_recv) \
  X(socket_recvfrom) \
  X(socket_shutdown) \
  X(socket_name) \
  X(socket_peer) \
  X(socket_getopt) \
  X(socket_setopt) \
  X(socket_inet_addr) \
  X(socket_unix_addr) \
  X(socket_addr_family) \
  X(socket_inet_parts) \
  X(socket_unix_path) \
  X(netdb_host_byname) \
  X(netdb_host_byaddr) \
  X(netdb_hostname) \
  X(netdb_proto_byname) \
  X(netdb_proto_bynumber) \
  X(netdb_serv_byname) \
  X(netdb_serv_byport) \
  X(file_descriptor) \
  X(posix_exit) \
  X(posix_lock) \
  X(posix_pathconf) \
  X(posix_utime) \
  X(file_tell) \
  X(file_seek) \
  X(posix_tcgetattr) \
  X(posix_tcsetattr) \
  X(posix_tcop) \
  X(real_to_bits) \
  X(real_from_bits) \
  X(socket_linger) \
  X(socket_query) \
  X(real_to_single) \
  X(real_single_from_string) \
  X(socket_inet6_addr) \
  X(socket_inet6_parts) \
  X(win_reg_open) \
  X(win_reg_close) \
  X(win_reg_delete) \
  X(win_reg_enum) \
  X(win_reg_query) \
  X(win_reg_set) \
  X(win_config) \
  X(win_version) \
  X(win_volume) \
  X(win_find_executable) \
  X(win_shell_execute) \
  X(win_spawn) \
  X(win_wait) \
  X(win_dde_start) \
  X(win_dde_execute) \
  X(win_dde_stop) \
  X(rt_instructions) \
  X(rt_bytes) \
  X(rt_objects) \
  X(rt_collections) \
  X(rt_live) \
  X(rt_heap_size) \
  X(rt_collect) \
  X(rt_version) \
  X(rt_trace) \
  X(rt_save) \
  X(rt_restore) \
  X(int_order) \
  X(word_order) \
  X(char_order) \
  X(string_order) \
  X(imm_eq)

#endif
