(* What runeisa writes from the descriptions of src/isa: each file as its
   path and its text. Every one of them is committed, so that the VM builds
   with a C compiler alone, and `make check-isa` fails where one is not
   what the descriptions give. *)
structure IsaGen =
struct
  open Isa

  type file = {path : string, text : string}

  fun lines (ls : string list) : string = String.concat (List.map (fn l => l ^ "\n") ls)

  fun pad (s : string, n : int) : string =
    if String.size s >= n then s ^ " " else s ^ CharVector.tabulate (n - String.size s, fn _ => #" ")

  fun numbered (xs : 'a list) : (int * 'a) list =
    #2 (List.foldr (fn (x, (i, acc)) => (i - 1, (i - 1, x) :: acc)) (List.length xs, []) xs)

  fun commaList (xs : string list) : string = String.concatWith ", " xs

  val generated = "Generated by runeisa from src/isa -- do not edit."

  (* ---- the fingerprint of an instruction set: a number, below 2^24, of
     everything that says what a bytecode of it means -- the instructions'
     names, operands, stack effects and flow, and the primitives' names and
     arities, in order -- but not what documents them. A .rbc and an image
     carry it, and a VM refuses one made for another instruction set. It is
     worked out so that no number goes above 2^30, as on every host. ---- *)

  fun canonical (instrs : instruction list, prims : primitive list) : string =
    let
      fun count (Fixed n) = "f" ^ Int.toString n
        | count (OperandValue k) = "o" ^ Int.toString k
        | count (ArityOf k) = "a" ^ Int.toString k
      fun flowName f =
        case f of Next => "next" | Branch => "branch" | Jump => "jump" | Call => "call"
                | TailCall => "tailcall" | Return => "return" | Raise => "raise" | Halt => "halt"
      fun handlersName h = case h of Keeps => "keeps" | Installs => "installs" | Removes => "removes"
      fun instr (i : instruction) =
        String.concatWith " "
          ([#name i] @ List.map (fn (_, k) => kindName k) (#operands i)
           @ [count (#pops i), Int.toString (#pushes i), flowName (#flow i), handlersName (#handlers i),
              if #raises i then "raises" else "-"])
      fun prim (p : primitive) = #name p ^ " " ^ Int.toString (#arity p)
    in
      String.concatWith "\n" (List.map instr instrs @ ["--"] @ List.map prim prims)
    end

  fun fingerprint (instrs, prims) : int =
    CharVector.foldl (fn (c, h) => (h * 31 + Char.ord c) mod 16777213) 7 (canonical (instrs, prims))

  fun hex8 (n : int) : string =
    let val s = Int.fmt StringCvt.HEX n
    in CharVector.tabulate (8 - String.size s, fn _ => #"0") ^ String.map Char.toLower s end

  (* The first bytes of an .rbc: "RUNE", the version and the fingerprint,
     each four bytes little-endian, as escapes of printf, for the scripts
     that write one. *)
  fun headerEscapes (version : int, fp : int) : string =
    let
      fun byte b = "\\" ^ StringCvt.padLeft #"0" 3 (Int.fmt StringCvt.OCT b)
      fun u32 v = String.concat (List.map (fn k => byte ((v div k) mod 256)) [1, 256, 65536, 16777216])
    in
      "RUNE" ^ u32 version ^ u32 fp
    end

  (* ---- the .def files, which the scripts of the tests and of the checks
     read: one line per instruction or primitive, as before the DSL ---- *)

  fun opcodesDef (instrs : instruction list, fp : int) : file =
    {path = "vm/opcodes.def",
     text =
       lines
         (["# The instruction set of the stack bytecode. " ^ generated,
           "# The description is src/isa/stack.sml, in the language of src/isa/isa.sml.",
           "# rbc version " ^ Int.toString StackIsa.rbcVersion,
           "# fingerprint " ^ hex8 fp,
           "# rbc header " ^ headerEscapes (StackIsa.rbcVersion, fp),
           "# Format:  NAME  OPERANDS  DESCRIPTION",
           "# OPERANDS is '-' or a comma separated list of operand names; each operand is",
           "# encoded as a little-endian signed 32-bit integer following the opcode byte.",
           "# An opcode's number is its place in this file, from 0."]
          @ List.map (fn (i : instruction) =>
                        pad (#name i, 14)
                        ^ pad (case #operands i of [] => "-" | ops => String.concatWith "," (List.map #1 ops), 8)
                        ^ #doc i)
                     instrs)}

  fun primsDef (prims : primitive list) : file =
    let
      fun entry (p : primitive) =
        pad (#name p, 17) ^ pad (Int.toString (#arity p), 3) ^ pad (#ty p ^ " ", 24) ^ " " ^ #doc p
      fun go (_, []) = []
        | go (last, p :: rest) =
            (if SOME (#group p) = last then [] else ["", "# --- " ^ #group p ^ " ---"])
            @ entry p :: go (SOME (#group p), rest)
    in
      {path = "vm/prims.def",
       text =
         lines
           (["# The primitives of the VMs. " ^ generated,
             "# The description is src/isa/prims.sml, in the language of src/isa/isa.sml.",
             "# Format:  NAME  ARITY  TYPE  DESCRIPTION, where two spaces end the TYPE.",
             "# A primitive's number is its place in this file, from 0."]
            @ go (NONE, prims))}
    end

  (* ---- the tables of the VM ---- *)

  fun opcodesH (instrs : instruction list, fp : int) : file =
    let val is = numbered instrs
    in
      {path = "vm/opcodes.h",
       text =
         lines
           (["/* " ^ generated ^ " */",
             "#ifndef RUNE_OPCODES_H",
             "#define RUNE_OPCODES_H",
             "",
             "/* The version of the layout of an .rbc, and the fingerprint of the",
             "   instruction set, which an .rbc and an image carry. */",
             "#define RBC_VERSION " ^ Int.toString StackIsa.rbcVersion,
             "#define ISA_FINGERPRINT 0x" ^ hex8 fp ^ "u",
             "#define ISA_FINGERPRINT_HEX \"" ^ hex8 fp ^ "\"",
             "",
             "enum Opcode {"]
            @ List.map (fn (n, i : instruction) => "  OP_" ^ #name i ^ " = " ^ Int.toString n ^ ",  /* " ^ #doc i ^ " */") is
            @ ["  OP__COUNT",
               "};",
               "",
               "static const char *const op_names[] = {"]
            @ List.map (fn (_, i : instruction) => "  \"" ^ #name i ^ "\",") is
            @ ["};",
               "",
               "static const unsigned char op_nargs[] = {"]
            @ List.map (fn (_, i : instruction) => "  " ^ Int.toString (List.length (#operands i)) ^ ",") is
            @ ["};",
               "",
               "/* What each opcode pops: a number (op_pops_fixed), the value of an",
               "   operand (op_pops_operand, its position), or the arity of the",
               "   primitive an operand names (op_pops_arity); -1 where not. The",
               "   loader works out from these, and from what each pushes, how deep",
               "   each function's stack goes (Function.maxstack). */",
               "static const signed char op_pops_fixed[] = {"]
            @ List.map (fn (_, i : instruction) => "  " ^ (case #pops i of Fixed n => Int.toString n | _ => "-1") ^ ",") is
            @ ["};",
               "static const signed char op_pops_operand[] = {"]
            @ List.map (fn (_, i : instruction) => "  " ^ (case #pops i of OperandValue k => Int.toString k | _ => "-1") ^ ",") is
            @ ["};",
               "static const signed char op_pops_arity[] = {"]
            @ List.map (fn (_, i : instruction) => "  " ^ (case #pops i of ArityOf k => Int.toString k | _ => "-1") ^ ",") is
            @ ["};",
               "static const unsigned char op_pushes[] = {"]
            @ List.map (fn (_, i : instruction) => "  " ^ Int.toString (#pushes i) ^ ",") is
            @ ["};",
               "",
               "/* Where control goes after each (src/isa/isa.sml, flow). */",
               "enum OpFlow { FLOW_NEXT, FLOW_BRANCH, FLOW_JUMP, FLOW_CALL, FLOW_TAILCALL, FLOW_RETURN, FLOW_RAISE, FLOW_HALT };",
               "static const unsigned char op_flow[] = {"]
            @ List.map (fn (_, i : instruction) =>
                          "  FLOW_" ^ (case #flow i of
                                          Next => "NEXT" | Branch => "BRANCH" | Jump => "JUMP" | Call => "CALL"
                                        | TailCall => "TAILCALL" | Return => "RETURN" | Raise => "RAISE" | Halt => "HALT") ^ ",") is
            @ ["};",
               "",
               "/* What each operand is, which says what the loader accepts for it",
               "   (src/isa/isa.sml, kind). */",
               "enum OperandKind {"]
            @ List.map (fn (k, kind) => "  OPND_" ^ kindName kind ^ " = " ^ Int.toString k ^ ",") (numbered kinds)
            @ ["};",
               "",
               "/* The kind of each operand of each opcode, by position; 0 past the last. */",
               "static const unsigned char op_kinds[][2] = {"]
            @ List.map (fn (_, i : instruction) =>
                          let
                            fun kindNumber k = #1 (valOf (List.find (fn (_, k') => k' = k) (numbered kinds)))
                            val ks = List.map (fn (_, k) => Int.toString (kindNumber k)) (#operands i)
                            val ks = ks @ List.tabulate (2 - List.length ks, fn _ => "0")
                          in
                            "  {" ^ commaList ks ^ "},  /* " ^ #name i ^ " */"
                          end) is
            @ ["};",
               "",
               "#endif"])}
    end

  fun primsH (prims : primitive list) : file =
    let
      val ps = numbered prims
      val n = List.length prims
    in
      {path = "vm/prims_table.h",
       text =
         lines
           (["/* " ^ generated ^ " */",
             "#ifndef RUNE_PRIMS_TABLE_H",
             "#define RUNE_PRIMS_TABLE_H",
             "",
             "enum Prim {"]
            @ List.map (fn (k, p : primitive) => "  PRIM_" ^ #name p ^ " = " ^ Int.toString k ^ ",") ps
            @ ["  PRIM__COUNT",
               "};",
               "",
               "static const char *const prim_names[] = {"]
            @ List.map (fn (_, p : primitive) => "  \"" ^ #name p ^ "\",") ps
            @ ["};",
               "",
               "static const unsigned char prim_arity[] = {"]
            @ List.map (fn (_, p : primitive) => "  " ^ Int.toString (#arity p) ^ ",") ps
            @ ["};",
               "",
               "#define RUNE_PRIM_LIST(X) \\"]
            @ List.map (fn (k, p : primitive) => "  X(" ^ #name p ^ ")" ^ (if k < n - 1 then " \\" else "")) ps
            @ ["",
               "#endif"])}
    end

  (* ---- the interpreter, from the bodies ---- *)

  fun indent (n : int) (ls : string list) : string list =
    let val sp = CharVector.tabulate (n, fn _ => #" ")
    in List.map (fn l => if l = "" then l else sp ^ l) ls end

  (* Each case of the loop (vm/interp.c) reads its own operands, moves the
     pc past it and counts it, then does its body -- a shared one through
     its function of vm/ops.h, with the VM given what the loop keeps -- and
     goes on to the next (NEXT). CASE and NEXT are the loop's: labels and a
     computed goto, or the cases of a switch. *)
  fun interpCases (instrs : instruction list) : file =
    {path = "vm/interp_cases.h",
     text =
       lines
         (["/* " ^ generated,
           "   The cases of the interpreter's loop (vm/interp.c), each the body of its",
           "   instruction in src/isa/stack.sml; a shared body is a function of",
           "   vm/ops.h. */"]
          @ List.concat
              (List.map (fn (i : instruction) =>
                           let
                             val n = List.length (#operands i)
                             val reads =
                               (if n >= 1 then ["int32_t a = read_i32(code + pc + 1);"] else [])
                               @ (if n >= 2 then ["int32_t b = read_i32(code + pc + 5);"] else [])
                             val ab = (if n >= 1 then "a" else "0") ^ ", " ^ (if n >= 2 then "b" else "0")
                             val body =
                               if #shared i then ["SYNC();", "op_" ^ #name i ^ "(vm, " ^ ab ^ ");", "RELOAD();"]
                               else #body i
                           in
                             ["CASE(" ^ #name i ^ ") {"]
                             @ indent 4 (reads
                                         @ ["TRACE(OP_" ^ #name i ^ ", " ^ ab ^ ");",
                                            "pc += " ^ Int.toString (1 + 4 * n) ^ ";",
                                            "count++;"]
                                         @ body
                                         @ ["NEXT;"])
                             @ ["}"]
                           end)
                        instrs))}

  (* The labels of the cases, in the order of the opcodes, for the computed
     goto of the loop. *)
  fun interpLabels (instrs : instruction list) : file =
    {path = "vm/interp_labels.h",
     text =
       lines
         (["/* " ^ generated,
           "   The labels of the cases of vm/interp_cases.h by opcode, for the",
           "   dispatch of vm/interp.c by computed goto. */"]
          @ List.map (fn (i : instruction) => "&&L_" ^ #name i ^ ",") instrs)}

  fun opsH (instrs : instruction list) : file =
    {path = "vm/ops.h",
     text =
       lines
         (["/* " ^ generated,
           "   The instructions whose body is shared (src/isa/isa.sml): the",
           "   interpreter's case of each calls it, and so does the code of runeopt,",
           "   through vm/native.c. */",
           "#ifndef RUNE_OPS_H",
           "#define RUNE_OPS_H",
           ""]
          @ List.concat
              (List.map (fn (i : instruction) =>
                           ["static inline void op_" ^ #name i ^ "(VM *vm, int32_t a, int32_t b) {",
                            "    Program *p = &vm->prog;",
                            "    (void)p; (void)a; (void)b;"]
                           @ indent 4 (#body i) @ ["}", ""])
                        (List.filter #shared instrs))
          @ ["#endif"])}

  (* ---- the tables of the compiler and of runeopt ---- *)

  fun opcodesSml (instrs : instruction list, fp : int) : file =
    let val is = numbered instrs
    in
      {path = "src/backend/opcodes.sml",
       text =
         lines
           (["(* " ^ generated ^ " *)",
             "structure Opcodes =",
             "struct",
             "  (* the version of the layout of an .rbc, and the fingerprint of the",
             "     instruction set, which an .rbc and an image carry *)",
             "  val rbcVersion = " ^ Int.toString StackIsa.rbcVersion,
             "  val fingerprint = " ^ Int.toString fp,
             "  val fingerprintHex = \"" ^ hex8 fp ^ "\""]
            @ List.map (fn (n, i : instruction) => "  val " ^ #name i ^ " = " ^ Int.toString n) is
            @ ["  val count = " ^ Int.toString (List.length instrs),
               "  val names = Vector.fromList [" ^ commaList (List.map (fn i : instruction => "\"" ^ #name i ^ "\"") instrs) ^ "]",
               "  val nargs = Vector.fromList [" ^ commaList (List.map (fn i : instruction => Int.toString (List.length (#operands i))) instrs) ^ "]",
               "end",
               "",
               "(* The opcodes as a datatype, for code that says what it does with each",
               "   one: MLton's build of runeopt treats a match that leaves one out as an",
               "   error, so a new opcode cannot go without its template. *)",
               "structure Opcode =",
               "struct",
               "  datatype t =",
               "      " ^ String.concatWith "\n    | " (List.map #name instrs),
               "  val all : t vector = Vector.fromList [" ^ commaList (List.map #name instrs) ^ "]",
               "  fun fromInt (n : int) : t = Vector.sub (all, n)",
               "end"])}
    end

  fun primsSml (prims : primitive list) : file =
    let
      val ps = numbered prims
      val n = List.length prims
    in
      {path = "src/backend/prims.sml",
       text =
         lines
           (["(* " ^ generated ^ " *)",
             "structure Prims =",
             "struct",
             "  (* (name, index, arity) *)",
             "  val table : (string * int * int) list = ["]
            @ List.map (fn (k, p : primitive) =>
                          "    (\"" ^ #name p ^ "\", " ^ Int.toString k ^ ", " ^ Int.toString (#arity p) ^ ")"
                          ^ (if k < n - 1 then "," else ""))
                       ps
            @ ["  ]",
               "  val byName =",
               "    List.foldl (fn ((n, i, a), m) => StringMap.insert (m, n, (i, a))) StringMap.empty table",
               "  (* find name = SOME (index, arity) *)",
               "  fun find name = StringMap.find (byName, name)",
               "end"])}
    end

  (* Every file, in the order they are written. *)
  fun files (instrs : instruction list, prims : primitive list) : file list =
    let
      val () = check (instrs, prims)
      val fp = fingerprint (instrs, prims)
    in
      [opcodesDef (instrs, fp), primsDef prims, opcodesH (instrs, fp), primsH prims,
       interpCases instrs, interpLabels instrs, opsH instrs, opcodesSml (instrs, fp), primsSml prims]
    end
end
