(* The primitives of the VMs, in the language of src/isa/isa.sml: a
   primitive's number is its place in this list, from 0, so a new one goes
   at the end. lib/basis binds each with `_prim "name" : ty`, and its C is
   `p_<name>` in vm/prims.c. `ty` is the type the library gives it, for
   documentation and for the hosts' RUNE_PRIM (tests/basis/host). Primitives
   that return an option rely on the prelude declaring
   `datatype 'a option = NONE | SOME of 'a` (NONE = tag 0, SOME = tag 1), and
   those that return an order on `datatype order = LESS | EQUAL | GREATER`.

   The effects say what a primitive may do beyond computing its result
   (Isa.effect); `anything` is the conservative answer, given wherever
   nothing more precise was worked out. *)
structure PrimIsa =
struct
  open Isa

  val primitives : primitive list =
    List.concat
      [group "polymorphic"
        [{name = "poly_eq", arity = 2, ty = "'a * 'a -> bool", effects = [],
          doc = "Structural equality (refs/arrays by identity)."},
         {name = "ptr_eq", arity = 2, ty = "'a * 'a -> bool", effects = [],
          doc = "Identity comparison of heap values."}],
       group "int (64-bit, Overflow checked)"
        [{name = "int_add", arity = 2, ty = "int * int -> int", effects = [Raises],
          doc = "Addition; raises Overflow."},
         {name = "int_sub", arity = 2, ty = "int * int -> int", effects = [Raises],
          doc = "Subtraction; raises Overflow."},
         {name = "int_mul", arity = 2, ty = "int * int -> int", effects = [Raises],
          doc = "Multiplication; raises Overflow."},
         {name = "int_div", arity = 2, ty = "int * int -> int", effects = [Raises],
          doc = "Floor division; raises Div, Overflow."},
         {name = "int_mod", arity = 2, ty = "int * int -> int", effects = [Raises],
          doc = "Floor modulus; raises Div."},
         {name = "int_quot", arity = 2, ty = "int * int -> int", effects = [Raises],
          doc = "Truncating division; raises Div, Overflow."},
         {name = "int_rem", arity = 2, ty = "int * int -> int", effects = [Raises],
          doc = "Truncating remainder; raises Div."},
         {name = "int_neg", arity = 1, ty = "int -> int", effects = [Raises],
          doc = "Negation; raises Overflow."},
         {name = "int_abs", arity = 1, ty = "int -> int", effects = [Raises],
          doc = "Absolute value; raises Overflow."},
         {name = "int_lt", arity = 2, ty = "int * int -> bool", effects = [],
          doc = "Less than."},
         {name = "int_le", arity = 2, ty = "int * int -> bool", effects = [],
          doc = "Less or equal."},
         {name = "int_gt", arity = 2, ty = "int * int -> bool", effects = [],
          doc = "Greater than."},
         {name = "int_ge", arity = 2, ty = "int * int -> bool", effects = [],
          doc = "Greater or equal."},
         {name = "int_to_string", arity = 1, ty = "int -> string", effects = [Allocates],
          doc = "Decimal rendering with ~ for negative."},
         {name = "int_from_string", arity = 1, ty = "string -> int option", effects = [Allocates],
          doc = "Parse an SML integer literal (decimal)."},
         {name = "int_to_char", arity = 1, ty = "int -> char", effects = [Raises],
          doc = "Raises Chr if out of range 0..255."},
         {name = "int_to_real", arity = 1, ty = "int -> real", effects = [RoundingMode],
          doc = "Conversion."}],
       group "word (64-bit unsigned)"
        [{name = "word_add", arity = 2, ty = "word * word -> word", effects = [],
          doc = "Wrapping addition."},
         {name = "word_sub", arity = 2, ty = "word * word -> word", effects = [],
          doc = "Wrapping subtraction."},
         {name = "word_mul", arity = 2, ty = "word * word -> word", effects = [],
          doc = "Wrapping multiplication."},
         {name = "word_div", arity = 2, ty = "word * word -> word", effects = [Raises],
          doc = "Division; raises Div."},
         {name = "word_mod", arity = 2, ty = "word * word -> word", effects = [Raises],
          doc = "Modulus; raises Div."},
         {name = "word_lt", arity = 2, ty = "word * word -> bool", effects = [],
          doc = "Unsigned less than."},
         {name = "word_le", arity = 2, ty = "word * word -> bool", effects = [],
          doc = "Unsigned less or equal."},
         {name = "word_gt", arity = 2, ty = "word * word -> bool", effects = [],
          doc = "Unsigned greater than."},
         {name = "word_ge", arity = 2, ty = "word * word -> bool", effects = [],
          doc = "Unsigned greater or equal."},
         {name = "word_andb", arity = 2, ty = "word * word -> word", effects = [],
          doc = "Bitwise and."},
         {name = "word_orb", arity = 2, ty = "word * word -> word", effects = [],
          doc = "Bitwise or."},
         {name = "word_xorb", arity = 2, ty = "word * word -> word", effects = [],
          doc = "Bitwise xor."},
         {name = "word_notb", arity = 1, ty = "word -> word", effects = [],
          doc = "Bitwise complement."},
         {name = "word_lsl", arity = 2, ty = "word * word -> word", effects = [],
          doc = "Logical shift left."},
         {name = "word_lsr", arity = 2, ty = "word * word -> word", effects = [],
          doc = "Logical shift right."},
         {name = "word_to_int", arity = 1, ty = "word -> int", effects = [Raises],
          doc = "Raises Overflow if it does not fit."},
         {name = "word_to_int_x", arity = 1, ty = "word -> int", effects = [],
          doc = "Two's complement reinterpretation."},
         {name = "word_from_int", arity = 1, ty = "int -> word", effects = [],
          doc = "Two's complement reinterpretation."},
         {name = "word_to_string", arity = 1, ty = "word -> string", effects = [Allocates],
          doc = "Uppercase hexadecimal."}],
       group "real (IEEE double)"
        [{name = "real_add", arity = 2, ty = "real * real -> real", effects = [RoundingMode],
          doc = "Addition."},
         {name = "real_sub", arity = 2, ty = "real * real -> real", effects = [RoundingMode],
          doc = "Subtraction."},
         {name = "real_mul", arity = 2, ty = "real * real -> real", effects = [RoundingMode],
          doc = "Multiplication."},
         {name = "real_div", arity = 2, ty = "real * real -> real", effects = [RoundingMode],
          doc = "Division."},
         {name = "real_neg", arity = 1, ty = "real -> real", effects = [],
          doc = "Negation."},
         {name = "real_abs", arity = 1, ty = "real -> real", effects = [],
          doc = "Absolute value."},
         {name = "real_lt", arity = 2, ty = "real * real -> bool", effects = [],
          doc = "Less than."},
         {name = "real_le", arity = 2, ty = "real * real -> bool", effects = [],
          doc = "Less or equal."},
         {name = "real_gt", arity = 2, ty = "real * real -> bool", effects = [],
          doc = "Greater than."},
         {name = "real_ge", arity = 2, ty = "real * real -> bool", effects = [],
          doc = "Greater or equal."},
         {name = "real_eq", arity = 2, ty = "real * real -> bool", effects = [],
          doc = "IEEE equality."},
         {name = "real_floor", arity = 1, ty = "real -> int", effects = [Raises],
          doc = "Raises Overflow/Domain."},
         {name = "real_ceil", arity = 1, ty = "real -> int", effects = [Raises],
          doc = "Raises Overflow/Domain."},
         {name = "real_round", arity = 1, ty = "real -> int", effects = [Raises],
          doc = "Round to nearest even; raises Overflow/Domain."},
         {name = "real_trunc", arity = 1, ty = "real -> int", effects = [Raises],
          doc = "Raises Overflow/Domain."},
         {name = "real_to_string", arity = 1, ty = "real -> string", effects = [RoundingMode, Allocates],
          doc = "SML formatting (~ for negative, E exponent)."},
         {name = "real_from_string", arity = 1, ty = "string -> real option", effects = [RoundingMode, Allocates],
          doc = "Parse a real literal."},
         {name = "real_sqrt", arity = 1, ty = "real -> real", effects = [RoundingMode],
          doc = "Square root."},
         {name = "real_exp", arity = 1, ty = "real -> real", effects = [RoundingMode],
          doc = "Exponential."},
         {name = "real_ln", arity = 1, ty = "real -> real", effects = [RoundingMode],
          doc = "Natural logarithm."},
         {name = "real_sin", arity = 1, ty = "real -> real", effects = [RoundingMode],
          doc = "Sine."},
         {name = "real_cos", arity = 1, ty = "real -> real", effects = [RoundingMode],
          doc = "Cosine."},
         {name = "real_tan", arity = 1, ty = "real -> real", effects = [RoundingMode],
          doc = "Tangent."},
         {name = "real_atan", arity = 1, ty = "real -> real", effects = [RoundingMode],
          doc = "Arc tangent."},
         {name = "real_atan2", arity = 2, ty = "real * real -> real", effects = [RoundingMode],
          doc = "Two argument arc tangent."},
         {name = "real_pow", arity = 2, ty = "real * real -> real", effects = [RoundingMode],
          doc = "Power."},
         {name = "real_is_nan", arity = 1, ty = "real -> bool", effects = [],
          doc = "NaN test."}],
       group "char"
        [{name = "char_ord", arity = 1, ty = "char -> int", effects = [],
          doc = "Code point."},
         {name = "char_lt", arity = 2, ty = "char * char -> bool", effects = [],
          doc = "Less than."},
         {name = "char_le", arity = 2, ty = "char * char -> bool", effects = [],
          doc = "Less or equal."},
         {name = "char_gt", arity = 2, ty = "char * char -> bool", effects = [],
          doc = "Greater than."},
         {name = "char_ge", arity = 2, ty = "char * char -> bool", effects = [],
          doc = "Greater or equal."}],
       group "string (8-bit byte strings)"
        [{name = "string_size", arity = 1, ty = "string -> int", effects = [],
          doc = "Length in bytes."},
         {name = "string_sub", arity = 2, ty = "string * int -> char", effects = [Raises],
          doc = "Indexing; raises Subscript."},
         {name = "string_concat", arity = 2, ty = "string * string -> string", effects = [Raises, Allocates],
          doc = "Concatenation; raises Size above 1073741823 characters (String.maxSize)."},
         {name = "string_extract", arity = 3, ty = "string * int * int -> string", effects = [Raises, Allocates],
          doc = "extract(s, i, n): substring of length n; raises Subscript."},
         {name = "string_lt", arity = 2, ty = "string * string -> bool", effects = [],
          doc = "Lexicographic less than."},
         {name = "string_le", arity = 2, ty = "string * string -> bool", effects = [],
          doc = "Lexicographic less or equal."},
         {name = "string_gt", arity = 2, ty = "string * string -> bool", effects = [],
          doc = "Lexicographic greater than."},
         {name = "string_ge", arity = 2, ty = "string * string -> bool", effects = [],
          doc = "Lexicographic greater or equal."},
         {name = "string_compare", arity = 2, ty = "string * string -> int", effects = [],
          doc = "Returns ~1, 0 or 1."},
         {name = "string_from_char", arity = 1, ty = "char -> string", effects = [Allocates],
          doc = "One character string."},
         {name = "string_implode", arity = 1, ty = "char list -> string", effects = [Raises, Allocates],
          doc = "Build a string from a list; raises Size above 1073741823 characters."},
         {name = "string_explode", arity = 1, ty = "string -> char list", effects = [Allocates],
          doc = "List of characters."},
         {name = "string_concat_list", arity = 1, ty = "string list -> string", effects = [Raises, Allocates],
          doc = "Concatenate a list of strings; raises Size above 1073741823 characters."}],
       group "ref / array / vector"
        [{name = "ref_new", arity = 1, ty = "'a -> 'a ref", effects = [Allocates],
          doc = "Allocate a reference cell."},
         {name = "ref_get", arity = 1, ty = "'a ref -> 'a", effects = [ReadsHeap],
          doc = "Dereference."},
         {name = "ref_set", arity = 2, ty = "'a ref * 'a -> unit", effects = [WritesHeap],
          doc = "Assignment."},
         {name = "array_new", arity = 2, ty = "int * 'a -> 'a array", effects = [Raises, Allocates],
          doc = "Allocate; raises Size if the length is negative or above 100000000."},
         {name = "array_length", arity = 1, ty = "'a array -> int", effects = [],
          doc = "Length."},
         {name = "array_sub", arity = 2, ty = "'a array * int -> 'a", effects = [Raises, ReadsHeap],
          doc = "Indexing; raises Subscript."},
         {name = "array_update", arity = 3, ty = "'a array * int * 'a -> unit", effects = [Raises, WritesHeap],
          doc = "Update; raises Subscript."},
         {name = "array_from_list", arity = 1, ty = "'a list -> 'a array", effects = [Raises, Allocates],
          doc = "Build from a list; raises Size above 100000000 elements."},
         {name = "vector_from_list", arity = 1, ty = "'a list -> 'a vector", effects = [Raises, Allocates],
          doc = "Build from a list; raises Size above 100000000 elements."},
         {name = "vector_length", arity = 1, ty = "'a vector -> int", effects = [],
          doc = "Length."},
         {name = "vector_sub", arity = 2, ty = "'a vector * int -> 'a", effects = [Raises],
          doc = "Indexing; raises Subscript."}],
       group "I/O and system"
        [{name = "print", arity = 1, ty = "string -> unit", effects = anything,
          doc = "Write to stdout."},
         {name = "print_err", arity = 1, ty = "string -> unit", effects = anything,
          doc = "Write to stderr."},
         {name = "flush_out", arity = 1, ty = "unit -> unit", effects = anything,
          doc = "Flush stdout."},
         {name = "input_line", arity = 1, ty = "unit -> string option", effects = anything,
          doc = "Read a line (including newline) from stdin."},
         {name = "input_all", arity = 1, ty = "unit -> string", effects = anything,
          doc = "Read the rest of stdin."},
         {name = "exit", arity = 1, ty = "int -> 'a", effects = anything,
          doc = "Terminate the process with the given status."},
         {name = "command_args", arity = 1, ty = "unit -> string list", effects = anything,
          doc = "Command line arguments after the bytecode file."},
         {name = "command_name", arity = 1, ty = "unit -> string", effects = anything,
          doc = "The bytecode file name."}],
       group "files (handles: 0 stdin, 1 stdout, 2 stderr, others from file_open)"
        [{name = "file_open", arity = 2, ty = "string * int -> int option", effects = anything,
          doc = "Open a file (mode 0 read, 1 write/truncate, 2 append); NONE on failure."},
         {name = "file_close", arity = 1, ty = "int -> unit", effects = anything,
          doc = "Close a handle (no-op for 0-2 and already closed handles)."},
         {name = "file_write", arity = 2, ty = "int * string -> bool", effects = anything,
          doc = "Write bytes; false if the handle is invalid or the write fails."},
         {name = "file_flush", arity = 1, ty = "int -> unit", effects = anything,
          doc = "Flush a handle."},
         {name = "file_read_line", arity = 1, ty = "int -> string option", effects = anything,
          doc = "Read a line including its newline (a last line without one gets it); NONE at end of file, and from then on."},
         {name = "file_read_all", arity = 1, ty = "int -> string", effects = anything,
          doc = "Read the rest of a handle, including what the file has gained since an end of file."},
         {name = "file_error", arity = 1, ty = "unit -> string", effects = anything,
          doc = "strerror text of the last failed file_open or file_write."}],
       group "added after the first release of the table (numbers are positions: append only)"
        [{name = "word_neg", arity = 1, ty = "word -> word", effects = [],
          doc = "Two's complement negation: 0 - w."},
         {name = "exn_name", arity = 1, ty = "exn -> string", effects = [Allocates],
          doc = "The name of the exception constructor of an exception value."},
         {name = "real_floor_r", arity = 1, ty = "real -> real", effects = [],
          doc = "Largest integral real not above the argument; zeros, infinities and NaN unchanged."},
         {name = "real_ceil_r", arity = 1, ty = "real -> real", effects = [],
          doc = "Smallest integral real not below the argument."},
         {name = "real_trunc_r", arity = 1, ty = "real -> real", effects = [],
          doc = "The argument without its fraction."},
         {name = "real_round_r", arity = 1, ty = "real -> real", effects = [],
          doc = "Nearest integral real, ties to even; the sign of the argument is kept."},
         {name = "real_sign_bit", arity = 1, ty = "real -> bool", effects = [],
          doc = "The sign bit, also of zeros and NaNs."},
         {name = "real_copy_sign", arity = 2, ty = "real * real -> real", effects = [],
          doc = "The first argument with the sign of the second."},
         {name = "real_frexp_man", arity = 1, ty = "real -> real", effects = [],
          doc = "man of x = man * 2^exp with 0.5 <= |man| < 1; x itself for zeros, infinities and NaN."},
         {name = "real_frexp_exp", arity = 1, ty = "real -> int", effects = [],
          doc = "exp of the same; 0 for zeros, infinities and NaN."},
         {name = "real_ldexp", arity = 2, ty = "real * int -> real", effects = [RoundingMode],
          doc = "x * 2^n, correctly rounded; overflows to an infinity, underflows to a zero."},
         {name = "real_next_after", arity = 2, ty = "real * real -> real", effects = [],
          doc = "The next real after the first argument in the direction of the second."},
         {name = "real_rem", arity = 2, ty = "real * real -> real", effects = [],
          doc = "x - n*y for n = trunc (x/y), computed exactly (C fmod)."},
         {name = "real_fmt_e", arity = 2, ty = "real * int -> string", effects = [RoundingMode, Raises, Allocates],
          doc = "C printf %.*e of a finite real: n digits after the point, e.g. -1.50e+02."},
         {name = "real_fmt_f", arity = 2, ty = "real * int -> string", effects = [RoundingMode, Raises, Allocates],
          doc = "C printf %.*f of a finite real: n digits after the point."},
         {name = "real_shortest", arity = 1, ty = "real -> string", effects = [RoundingMode, Allocates],
          doc = "The %.*e rendering of a finite real with the fewest digits that reads back as the same real."},
         {name = "real_set_round", arity = 1, ty = "int -> unit", effects = anything,
          doc = "Rounding mode of the arithmetic: 0 nearest, 1 downward, 2 upward, 3 toward zero."},
         {name = "real_get_round", arity = 1, ty = "unit -> int", effects = anything,
          doc = "The current rounding mode, numbered likewise."},
         {name = "real_sinh", arity = 1, ty = "real -> real", effects = [RoundingMode],
          doc = "Hyperbolic sine."},
         {name = "real_cosh", arity = 1, ty = "real -> real", effects = [RoundingMode],
          doc = "Hyperbolic cosine."},
         {name = "real_tanh", arity = 1, ty = "real -> real", effects = [RoundingMode],
          doc = "Hyperbolic tangent."},
         {name = "file_read_vec", arity = 2, ty = "int * int -> string", effects = anything,
          doc = "Read at most n bytes; \"\" at end of file. Raises Size for a negative n."},
         {name = "file_avail", arity = 1, ty = "int -> int", effects = anything,
          doc = "Bytes that can be read without waiting, ~1 when that cannot be told."},
         {name = "sys_errno", arity = 1, ty = "unit -> int", effects = anything,
          doc = "The errno of the last system call that failed."},
         {name = "sys_error_msg", arity = 1, ty = "int -> string", effects = anything,
          doc = "The text of an errno value."},
         {name = "sys_error_name", arity = 1, ty = "int -> string", effects = anything,
          doc = "The name of an errno value (\"ENOENT\"); \"\" when it has none."},
         {name = "sys_error_of_name", arity = 1, ty = "string -> int", effects = anything,
          doc = "The errno value of a name; ~1 when it is not known."},
         {name = "time_now", arity = 1, ty = "unit -> int", effects = anything,
          doc = "Microseconds since the epoch."},
         {name = "time_user", arity = 1, ty = "unit -> int", effects = anything,
          doc = "Processor time of this program in user mode, in microseconds."},
         {name = "time_sys", arity = 1, ty = "unit -> int", effects = anything,
          doc = "The same in system mode."},
         {name = "time_sleep", arity = 1, ty = "int -> unit", effects = anything,
          doc = "Wait for that many microseconds; a negative time waits not at all."},
         {name = "time_gc_user", arity = 1, ty = "unit -> int", effects = anything,
          doc = "Processor time this program has spent collecting, in user mode, in microseconds."},
         {name = "time_gc_sys", arity = 1, ty = "unit -> int", effects = anything,
          doc = "The same in system mode."},
         {name = "date_parts", arity = 2, ty = "int * int -> int list", effects = anything,
          doc = "Broken-down time (second, minute, hour, day, month, year - 1900, weekday, yearday, daylight saving) of a time in seconds, local when the second argument is 1; [] on failure."},
         {name = "date_seconds", arity = 2, ty = "int list * int -> int list", effects = anything,
          doc = "The reverse: the seconds, followed by the parts normalised; [] on failure."},
         {name = "date_offset", arity = 1, ty = "int -> int", effects = anything,
          doc = "Seconds by which local time is ahead of UTC at that time; raises Domain on failure."},
         {name = "date_format", arity = 3, ty = "string * int list * int -> string", effects = anything,
          doc = "strftime of the parts."},
         {name = "os_system", arity = 1, ty = "string -> int", effects = anything,
          doc = "Run a command with the shell and wait; what it exited with, or 256 plus the signal that ended it, or ~1."},
         {name = "os_getenv", arity = 1, ty = "string -> string option", effects = anything,
          doc = "The value of an environment variable."},
         {name = "file_errno", arity = 1, ty = "unit -> int", effects = anything,
          doc = "The errno of the last file_open or file_write that failed."},
         {name = "os_mkdir", arity = 1, ty = "string -> int", effects = anything,
          doc = "Make a directory; 0, or ~1 with the reason in sys_errno."},
         {name = "os_rmdir", arity = 1, ty = "string -> int", effects = anything,
          doc = "Remove an empty directory."},
         {name = "os_chdir", arity = 1, ty = "string -> int", effects = anything,
          doc = "Change the working directory."},
         {name = "os_getcwd", arity = 1, ty = "unit -> string", effects = anything,
          doc = "The working directory; \"\" on failure."},
         {name = "os_remove", arity = 1, ty = "string -> int", effects = anything,
          doc = "Remove a file."},
         {name = "os_rename", arity = 2, ty = "string * string -> int", effects = anything,
          doc = "Rename a file."},
         {name = "os_access", arity = 3, ty = "string * int * int -> int", effects = anything,
          doc = "Whether the file can be read, written or run (the flags are 1 for the third argument's bits 1, 2 and 4); 1, 0 or ~1."},
         {name = "os_file_kind", arity = 1, ty = "string -> int", effects = anything,
          doc = "0 file, 1 directory, 2 symbolic link, 3 other, ~1 on failure; follows links."},
         {name = "os_link_kind", arity = 1, ty = "string -> int", effects = anything,
          doc = "The same without following the last link."},
         {name = "os_file_size", arity = 1, ty = "string -> int", effects = anything,
          doc = "The size of a file in bytes; ~1 on failure."},
         {name = "os_mod_time", arity = 1, ty = "string -> int", effects = anything,
          doc = "When a file was last changed, in seconds since the epoch; ~1 on failure."},
         {name = "os_set_time", arity = 3, ty = "string * int * int -> int", effects = anything,
          doc = "Set that time, or the present when the third argument is 1."},
         {name = "os_read_link", arity = 1, ty = "string -> string", effects = anything,
          doc = "What a symbolic link points at; \"\" on failure."},
         {name = "os_real_path", arity = 1, ty = "string -> string", effects = anything,
          doc = "The path without links or the arcs . and ..; \"\" on failure."},
         {name = "os_tmp_name", arity = 1, ty = "unit -> string", effects = anything,
          doc = "The name of a new file that did not exist; \"\" on failure."},
         {name = "os_file_id", arity = 1, ty = "string -> int list", effects = anything,
          doc = "The device and the inode of a file, which tell files apart; [] on failure."},
         {name = "os_open_dir", arity = 1, ty = "string -> int", effects = anything,
          doc = "Open a directory; the number of the stream, or ~1."},
         {name = "os_read_dir", arity = 1, ty = "int -> string option", effects = anything,
          doc = "The next name in it, without . and ..; NONE at the end."},
         {name = "os_rewind_dir", arity = 1, ty = "int -> int", effects = anything,
          doc = "Start again at the first name."},
         {name = "os_close_dir", arity = 1, ty = "int -> int", effects = anything,
          doc = "Close the stream."},
         {name = "os_desc_kind", arity = 1, ty = "int -> int", effects = anything,
          doc = "The kind of a descriptor of the system: 0 file, 1 directory, 2 symbolic link, 3 terminal, 4 pipe, 5 socket, 6 device, ~1 on failure."},
         {name = "os_poll", arity = 3, ty = "int list * int list * int -> int list", effects = anything,
          doc = "Wait until one of the descriptors of the system is ready, at most for the given microseconds (a negative time has no limit); the events wanted and then returned are bits: 1 read, 2 write, 4 urgent. [] on failure."},
         {name = "posix_const", arity = 1, ty = "string -> int", effects = anything,
          doc = "The value of a named constant of POSIX (an errno, a signal, a flag of open, a bit of a file mode); ~1 when the name is not known."},
         {name = "posix_fork", arity = 1, ty = "unit -> int", effects = SavesImage :: anything,
          doc = "Make a child process: 0 in it, its number in the parent, ~1 on failure."},
         {name = "posix_exec", arity = 3, ty = "string * string list * int -> int", effects = anything,
          doc = "Replace this program with another: the path (searched for on PATH when the third argument is 1) and the arguments; returns ~1, or not at all."},
         {name = "posix_exece", arity = 3, ty = "string * string list * string list -> int", effects = anything,
          doc = "The same with the environment given."},
         {name = "posix_spawn", arity = 5, ty = "string * string list * string list * int * int list -> int", effects = anything,
          doc = "Start a program as fork, dup2 and exec would, without the fork: the path, the arguments, the environment (given when bit 1 of the fourth argument is set; bit 0 searches PATH) and the descriptors of its standard input, output and error (~1: this process's own); its process, or ~1."},
         {name = "posix_waitpid", arity = 2, ty = "int * int -> int list", effects = anything,
          doc = "Wait for a child: [process, 0 exited or 1 signalled or 2 stopped, status or signal]; [] on failure."},
         {name = "posix_kill", arity = 2, ty = "int * int -> int", effects = anything,
          doc = "Send a signal to a process."},
         {name = "posix_alarm", arity = 1, ty = "int -> int", effects = anything,
          doc = "Ask for SIGALRM in that many seconds; what was left of an earlier one."},
         {name = "posix_pause", arity = 1, ty = "unit -> int", effects = anything,
          doc = "Wait for a signal."},
         {name = "posix_getpid", arity = 1, ty = "unit -> int", effects = anything,
          doc = "This process."},
         {name = "posix_getppid", arity = 1, ty = "unit -> int", effects = anything,
          doc = "Its parent."},
         {name = "posix_getuid", arity = 1, ty = "unit -> int", effects = anything,
          doc = "The user."},
         {name = "posix_geteuid", arity = 1, ty = "unit -> int", effects = anything,
          doc = "The effective user."},
         {name = "posix_getgid", arity = 1, ty = "unit -> int", effects = anything,
          doc = "The group."},
         {name = "posix_getegid", arity = 1, ty = "unit -> int", effects = anything,
          doc = "The effective group."},
         {name = "posix_setuid", arity = 1, ty = "int -> int", effects = anything,
          doc = "Set the user."},
         {name = "posix_setgid", arity = 1, ty = "int -> int", effects = anything,
          doc = "Set the group."},
         {name = "posix_getgroups", arity = 1, ty = "unit -> int list", effects = anything,
          doc = "The groups the user is in."},
         {name = "posix_getlogin", arity = 1, ty = "unit -> string", effects = anything,
          doc = "The name of the user; \"\" on failure."},
         {name = "posix_getpgrp", arity = 1, ty = "unit -> int", effects = anything,
          doc = "The process group."},
         {name = "posix_setsid", arity = 1, ty = "unit -> int", effects = anything,
          doc = "Start a session; its number, or ~1."},
         {name = "posix_setpgid", arity = 2, ty = "int * int -> int", effects = anything,
          doc = "Set the process group of a process."},
         {name = "posix_uname", arity = 1, ty = "unit -> string list", effects = anything,
          doc = "The system, the machine's name, the release, the version and the machine."},
         {name = "posix_times", arity = 1, ty = "unit -> int list", effects = anything,
          doc = "Elapsed, user, system, children's user and children's system time, in microseconds."},
         {name = "posix_environ", arity = 1, ty = "unit -> string list", effects = anything,
          doc = "The environment, as \"name=value\"."},
         {name = "posix_ctermid", arity = 1, ty = "unit -> string", effects = anything,
          doc = "The controlling terminal of this process."},
         {name = "posix_ttyname", arity = 1, ty = "int -> string", effects = anything,
          doc = "The terminal a descriptor is open on; \"\" when it is not one."},
         {name = "posix_isatty", arity = 1, ty = "int -> int", effects = anything,
          doc = "Whether a descriptor is a terminal."},
         {name = "posix_sysconf", arity = 1, ty = "string -> int", effects = anything,
          doc = "A number the system reports (ARG_MAX, CLK_TCK, OPEN_MAX, PAGESIZE, ...); ~1 when the name is not known."},
         {name = "posix_openf", arity = 3, ty = "string * int * int -> int", effects = anything,
          doc = "Open a file with the flags and mode of POSIX; the handle, or ~1."},
         {name = "posix_close", arity = 1, ty = "int -> int", effects = anything,
          doc = "Close a handle."},
         {name = "posix_dup", arity = 1, ty = "int -> int", effects = anything,
          doc = "Another handle for the same file."},
         {name = "posix_dup2", arity = 2, ty = "int * int -> int", effects = anything,
          doc = "The same, with the second handle given."},
         {name = "posix_pipe", arity = 1, ty = "unit -> int list", effects = anything,
          doc = "A pipe, as [read handle, write handle]; [] on failure."},
         {name = "posix_read", arity = 2, ty = "int * int -> string", effects = anything,
          doc = "Read at most n bytes; \"\" at end of file (sys_errno is then 0) or on failure. Raises Size for a negative n."},
         {name = "posix_write", arity = 2, ty = "int * string -> int", effects = anything,
          doc = "Write the bytes; how many were written, or ~1."},
         {name = "posix_lseek", arity = 3, ty = "int * int * int -> int", effects = anything,
          doc = "Move the position; where it ends up, or ~1."},
         {name = "posix_fsync", arity = 1, ty = "int -> int", effects = anything,
          doc = "Write what the system holds for the file to the disk."},
         {name = "posix_fcntl", arity = 3, ty = "int * int * int -> int", effects = anything,
          doc = "The fcntl of POSIX, for the commands of the flags of a handle."},
         {name = "posix_ftruncate", arity = 2, ty = "int * int -> int", effects = anything,
          doc = "Set the length of a file."},
         {name = "posix_stat", arity = 3, ty = "string * int * int -> int list", effects = anything,
          doc = "The fields of stat: kind, mode, inode, device, links, user, group, size, access time, modification time, change time; of the path, of the link itself when the second argument is 1 (0 follows it), or of the descriptor when the path is \"\"; [] on failure. The kind: 0 regular file, 1 directory, 2 symbolic link, 3 other, 4 FIFO, 5 socket, 6 character device, 7 block device."},
         {name = "posix_chmod", arity = 3, ty = "string * int * int -> int", effects = anything,
          doc = "Set the mode of a path, or of a handle when the path is \"\"."},
         {name = "posix_chown", arity = 4, ty = "string * int * int * int -> int", effects = anything,
          doc = "Set the user and group likewise."},
         {name = "posix_link", arity = 2, ty = "string * string -> int", effects = anything,
          doc = "Make a hard link."},
         {name = "posix_symlink", arity = 2, ty = "string * string -> int", effects = anything,
          doc = "Make a symbolic link."},
         {name = "posix_mkfifo", arity = 2, ty = "string * int -> int", effects = anything,
          doc = "Make a named pipe."},
         {name = "posix_umask", arity = 1, ty = "int -> int", effects = anything,
          doc = "Set the mask of new files; the one before."},
         {name = "posix_getpw", arity = 2, ty = "string * int -> string list", effects = anything,
          doc = "A user by name, or by number when the name is \"\"; the name, the home directory and the shell, then the user and group numbers. [] when there is none."},
         {name = "posix_getgr", arity = 2, ty = "string * int -> string list", effects = anything,
          doc = "A group likewise: the name, then its number, then the members."},
         {name = "socket_create", arity = 3, ty = "int * int * int -> int", effects = anything,
          doc = "A socket of the domain, type and protocol; the handle, or ~1."},
         {name = "socket_pair", arity = 3, ty = "int * int * int -> int list", effects = anything,
          doc = "A pair of connected sockets; [] on failure."},
         {name = "socket_bind", arity = 2, ty = "int * string -> int", effects = anything,
          doc = "Give a socket an address."},
         {name = "socket_connect", arity = 2, ty = "int * string -> int", effects = anything,
          doc = "Connect it to one."},
         {name = "socket_listen", arity = 2, ty = "int * int -> int", effects = anything,
          doc = "Let it accept that many waiting connections."},
         {name = "socket_accept", arity = 1, ty = "int -> int", effects = anything,
          doc = "Take a connection; the handle of the new socket, or ~1."},
         {name = "socket_send", arity = 3, ty = "int * string * int -> int", effects = anything,
          doc = "Send the bytes with the flags; how many, or ~1."},
         {name = "socket_sendto", arity = 4, ty = "int * string * int * string -> int", effects = anything,
          doc = "The same to an address."},
         {name = "socket_recv", arity = 3, ty = "int * int * int -> string", effects = anything,
          doc = "Receive at most n bytes with the flags; \"\" at the end (sys_errno is then 0) or on failure."},
         {name = "socket_recvfrom", arity = 3, ty = "int * int * int -> string list", effects = anything,
          doc = "The bytes and the address they came from; [] on failure."},
         {name = "socket_shutdown", arity = 2, ty = "int * int -> int", effects = anything,
          doc = "Stop reading, writing or both."},
         {name = "socket_name", arity = 1, ty = "int -> string", effects = anything,
          doc = "The address of a socket; \"\" on failure."},
         {name = "socket_peer", arity = 1, ty = "int -> string", effects = anything,
          doc = "The address at the other end."},
         {name = "socket_getopt", arity = 3, ty = "int * int * int -> int", effects = anything,
          doc = "An option of a socket."},
         {name = "socket_setopt", arity = 4, ty = "int * int * int * int -> int", effects = anything,
          doc = "Set one."},
         {name = "socket_inet_addr", arity = 2, ty = "string * int -> string", effects = anything,
          doc = "An address of the internet, from a dotted host (or \"\" for any) and a port; \"\" on failure."},
         {name = "socket_unix_addr", arity = 1, ty = "string -> string", effects = anything,
          doc = "An address in the file system."},
         {name = "socket_addr_family", arity = 1, ty = "string -> int", effects = anything,
          doc = "Which kind of address it is."},
         {name = "socket_inet_parts", arity = 1, ty = "string -> string list", effects = anything,
          doc = "The dotted host and the port of an internet address; [] when it is not one."},
         {name = "socket_unix_path", arity = 1, ty = "string -> string", effects = anything,
          doc = "The path of an address in the file system."},
         {name = "netdb_host_byname", arity = 1, ty = "string -> string list", effects = anything,
          doc = "A host by name: its name, its addresses separated by spaces, then its other names; [] when there is none."},
         {name = "netdb_host_byaddr", arity = 1, ty = "string -> string list", effects = anything,
          doc = "The same by dotted address."},
         {name = "netdb_hostname", arity = 1, ty = "unit -> string", effects = anything,
          doc = "The name of this machine."},
         {name = "netdb_proto_byname", arity = 1, ty = "string -> string list", effects = anything,
          doc = "A protocol by name: its name, its number, then its other names."},
         {name = "netdb_proto_bynumber", arity = 1, ty = "int -> string list", effects = anything,
          doc = "The same by number."},
         {name = "netdb_serv_byname", arity = 2, ty = "string * string -> string list", effects = anything,
          doc = "A service by name and protocol: its name, its port, its protocol, then its other names."},
         {name = "netdb_serv_byport", arity = 2, ty = "int * string -> string list", effects = anything,
          doc = "The same by port."},
         {name = "file_descriptor", arity = 1, ty = "int -> int", effects = anything,
          doc = "The descriptor of the system under a file handle; ~1 for a closed one."},
         {name = "posix_exit", arity = 1, ty = "int -> 'a", effects = anything,
          doc = "End the process at once with the status: no buffer is flushed and no at-exit action runs."},
         {name = "posix_lock", arity = 6, ty = "int * int * int * int * int * int -> int list", effects = anything,
          doc = "fcntl with a lock: descriptor, command (F_GETLK, F_SETLK, F_SETLKW), type, whence, start, length; the lock afterwards (type, whence, start, length, pid), [] on failure."},
         {name = "posix_pathconf", arity = 3, ty = "string * int * string -> int list", effects = anything,
          doc = "The limit of a path (of the descriptor when the path is \"\") named without its _PC_ prefix: [value], [~1] when there is none, [] on failure."},
         {name = "posix_utime", arity = 3, ty = "string * int * int -> int", effects = anything,
          doc = "Set the access and modification times of a file, in seconds."},
         {name = "file_tell", arity = 1, ty = "int -> int", effects = anything,
          doc = "The position of a file in bytes, or ~1 when it has none (a pipe, a terminal) or the handle is closed."},
         {name = "file_seek", arity = 2, ty = "int * int -> int", effects = anything,
          doc = "Move a file to a position in bytes from its start; 0, or ~1 on failure (file_errno says why)."},
         {name = "posix_tcgetattr", arity = 1, ty = "int -> int list", effects = anything,
          doc = "The settings of a terminal: iflag, oflag, cflag, lflag, input speed, output speed, then the NCCS control characters; [] on failure."},
         {name = "posix_tcsetattr", arity = 3, ty = "int * int * int list -> int", effects = anything,
          doc = "Set them with an action (TCSANOW, TCSADRAIN, TCSAFLUSH); ~1 on failure."},
         {name = "posix_tcop", arity = 3, ty = "int * int * int -> int", effects = anything,
          doc = "On a terminal: 0 tcdrain, 1 tcflush (the queue), 2 tcflow (the action), 3 tcsendbreak (the duration), 4 tcgetpgrp (gives the group), 5 tcsetpgrp (the group); ~1 on failure."},
         {name = "real_to_bits", arity = 1, ty = "real -> word", effects = [],
          doc = "The 64 bits of a real, IEEE 754 binary64."},
         {name = "real_from_bits", arity = 1, ty = "word -> real", effects = [],
          doc = "The real of 64 bits."},
         {name = "socket_linger", arity = 3, ty = "int * int * int -> int list", effects = anything,
          doc = "SO_LINGER of a socket: set it to the seconds (~1 turns it off) when the second argument is 1; [the seconds afterwards, ~1 when off], [] on failure."},
         {name = "socket_query", arity = 2, ty = "int * int -> int", effects = anything,
          doc = "0: the bytes a socket can read at once (FIONREAD); 1: whether it is at the out-of-band mark; ~1 on failure."},
         {name = "real_to_single", arity = 1, ty = "real -> real", effects = [RoundingMode],
          doc = "The IEEE 754 binary32 value nearest the argument in the current rounding mode (an infinity beyond the range), as a real."},
         {name = "real_single_from_string", arity = 1, ty = "string -> real option", effects = [RoundingMode, Allocates],
          doc = "Parse a real literal to the nearest binary32 value (C strtof), as a real."},
         {name = "socket_inet6_addr", arity = 2, ty = "string * int -> string", effects = anything,
          doc = "The bytes of an IPv6 sockaddr for a host in the text of inet_pton and a port; \"\" on failure."},
         {name = "socket_inet6_parts", arity = 1, ty = "string -> string list", effects = anything,
          doc = "The host and the port of such a sockaddr, as two strings; [] when it is not one."}],
       group "Windows (lib/basis/windows.sml; vm/sys_win.c, ENOSYS on other systems)"
        [{name = "win_reg_open", arity = 4, ty = "int * string * int * int -> int list", effects = anything,
          doc = "Open (or with the fourth argument 1, create) a subkey of the registry with the given rights: [1 created or 2 opened, the key]; [] on failure."},
         {name = "win_reg_close", arity = 1, ty = "int -> int", effects = anything,
          doc = "Close a key of the registry."},
         {name = "win_reg_delete", arity = 3, ty = "int * string * int -> int", effects = anything,
          doc = "Delete a subkey (third argument 0) or a value (1) of a key."},
         {name = "win_reg_enum", arity = 3, ty = "int * int * int -> string list", effects = anything,
          doc = "The name of the subkey (third argument 0) or value (1) of that index: [name], or [] when there are no more (sys_errno 0) or on failure."},
         {name = "win_reg_query", arity = 2, ty = "int * string -> string list", effects = anything,
          doc = "A value of a key: [its type of the registry, its bytes], or [] when there is none (sys_errno 0) or on failure."},
         {name = "win_reg_set", arity = 4, ty = "int * string * int * string -> int", effects = anything,
          doc = "Set a value of a key to the bytes given, of the type of the registry given."},
         {name = "win_config", arity = 1, ty = "int -> string", effects = anything,
          doc = "The directory of Windows (0), its system directory (1), the name of the computer (2) or of the user (3); \"\" on failure."},
         {name = "win_version", arity = 1, ty = "unit -> string list", effects = anything,
          doc = "The version of Windows: [major, minor, build, platform, service pack]; [] on failure."},
         {name = "win_volume", arity = 1, ty = "string -> string list", effects = anything,
          doc = "The volume of a root: [name, file system, serial number, longest name]; [] on failure."},
         {name = "win_find_executable", arity = 1, ty = "string -> string list", effects = anything,
          doc = "The program Windows opens a file with: [path], or [] when there is none (sys_errno 0) or on failure."},
         {name = "win_shell_execute", arity = 3, ty = "string * string * int -> int", effects = anything,
          doc = "ShellExecute \"open\": a program with an argument (third argument 0) or a document (1)."},
         {name = "win_spawn", arity = 3, ty = "string * string * int list -> int", effects = anything,
          doc = "Start a program with its arguments as one command line and three descriptors as its standard streams (~1: this process's); its process, or ~1."},
         {name = "win_wait", arity = 1, ty = "int -> int list", effects = anything,
          doc = "Wait for a child: [the code it ended with, all 32 bits]; [] on failure."},
         {name = "win_dde_start", arity = 2, ty = "string * string -> int", effects = anything,
          doc = "Start a conversation of DDE with a service on a topic."},
         {name = "win_dde_execute", arity = 4, ty = "int * string * int * int -> int", effects = anything,
          doc = "Execute a command in a conversation, trying again that many times while the service is busy, that many milliseconds apart."},
         {name = "win_dde_stop", arity = 1, ty = "int -> int", effects = anything,
          doc = "End a conversation of DDE."},
         {name = "rt_instructions", arity = 1, ty = "unit -> int", effects = anything,
          doc = "Bytecode instructions this program has executed, which `runevm --count` prints when it ends."},
         {name = "rt_bytes", arity = 1, ty = "unit -> int", effects = anything,
          doc = "Bytes it has allocated in the heap, including what has since been collected."},
         {name = "rt_objects", arity = 1, ty = "unit -> int", effects = anything,
          doc = "Objects it has allocated, likewise."},
         {name = "rt_collections", arity = 1, ty = "unit -> int", effects = anything,
          doc = "Collections the collector has made."},
         {name = "rt_live", arity = 1, ty = "unit -> int", effects = anything,
          doc = "Bytes of the current semispace that are in use: what the last collection kept plus what has been allocated since."},
         {name = "rt_heap_size", arity = 1, ty = "unit -> int", effects = anything,
          doc = "The size of one semispace, in bytes."},
         {name = "rt_collect", arity = 1, ty = "unit -> unit", effects = anything,
          doc = "Collect the heap now: free every unreachable object and move every surviving one."},
         {name = "rt_version", arity = 1, ty = "unit -> string", effects = anything,
          doc = "The version of Rune this VM was built as, which `runevm --version` prints."},
         {name = "rt_trace", arity = 1, ty = "int -> (string * string * int * int) list", effects = anything,
          doc = "The frames, innermost first, leaving out the innermost n: the name of each function, the file it is in, and the line and column it is stopped at; the file is \"\" and both numbers 0 where the program carries no position."},
         {name = "rt_save", arity = 1, ty = "string -> int", effects = SavesImage :: anything,
          doc = "Write the whole VM to a file, to be carried on by `runevm --restore`: 0 here, 1 in the world that starts again from it, ~1 if it could not be written."},
         {name = "rt_restore", arity = 1, ty = "string -> int", effects = NewWorld :: anything,
          doc = "Become the world in a file that Runtime.save wrote, bytecode and all; it does not come back, and gives ~1 only when the image cannot be read."}],
       group "comparisons that answer an order (LESS = tag 0, EQUAL = 1, GREATER = 2, as lib/basis/initial.sml declares it), for Int, Word, Char and String.compare"
        [{name = "int_order", arity = 2, ty = "int * int -> order", effects = [],
          doc = "LESS, EQUAL or GREATER: how the first int compares with the second."},
         {name = "word_order", arity = 2, ty = "word * word -> order", effects = [],
          doc = "The same for words, unsigned."},
         {name = "char_order", arity = 2, ty = "char * char -> order", effects = [],
          doc = "The same for characters, by code."},
         {name = "string_order", arity = 2, ty = "string * string -> order", effects = [],
          doc = "The same for strings, lexicographically by the codes of their characters."}]]
end
