/* Generated by runeisa from src/isa -- do not edit. */
#ifndef RUNE_ISA_H
#define RUNE_ISA_H

/* What the two instruction sets share: the version of the layout of an
   .rbc, and the fingerprint of each set, which its .rbc and its images
   carry. */
#define RBC_VERSION 6
#define STACK_ISA_FINGERPRINT 0x00bc2b41u
#define STACK_ISA_FINGERPRINT_HEX "00bc2b41"
#define REG_ISA_FINGERPRINT 0x005f1a5cu
#define REG_ISA_FINGERPRINT_HEX "005f1a5c"

/* Where control goes after an instruction (src/isa/isa.sml, flow): what
   each set's table says of its own (op_flow in runtime/stack/opcodes.h,
   rop_flow in runtime/register/regops.h). */
enum OpFlow { FLOW_NEXT, FLOW_BRANCH, FLOW_JUMP, FLOW_CALL, FLOW_TAILCALL, FLOW_RETURN, FLOW_RAISE, FLOW_HALT,
              FLOW_SWITCH };

#endif
