(* Generated by scripts/gen-basis-sigs.sh from tests/basis/spec-sigs/MONO_ARRAY2.sml; do not edit. *)
(* signature MONO_ARRAY2, transcribed from
   https://smlfamily.github.io/Basis/mono-array2.html

   The constraints of the instances (`structure Word8Array2 :> MONO_ARRAY2
   where type vector = Word8Vector.vector where type elem = Word8.word`, the
   same for CharArray2 with CharVector.vector and char, and for BoolArray2,
   IntArray2, WordArray2, RealArray2, LargeIntArray2, LargeWordArray2,
   LargeRealArray2, Int<N>Array2, Word<N>Array2 and Real<N>Array2 with the
   vector of their element type) are in tests/basis/word8array2_sig.sml,
   tests/basis/chararray2_sig.sml and tests/basis/mono.*_sig.sml. "If an
   implementation provides any structure matching MONO_ARRAY2, it must also
   supply the structure Array2 and its signature ARRAY2": the traversal is
   that of Array2. *)
signature MONO_ARRAY2 =
sig
  eqtype array
  type elem
  type vector
  type region = {base : array, row : int, col : int, nrows : int option, ncols : int option}
  datatype traversal = datatype Array2.traversal

  val array : int * int * elem -> array
  val fromList : elem list list -> array
  val tabulate : traversal -> int * int * (int * int -> elem) -> array
  val sub : array * int * int -> elem
  val update : array * int * int * elem -> unit
  val dimensions : array -> int * int
  val nCols : array -> int
  val nRows : array -> int
  val row : array * int -> vector
  val column : array * int -> vector
  val copy : {src : region, dst : array, dst_row : int, dst_col : int} -> unit
  val appi : traversal -> (int * int * elem -> unit) -> region -> unit
  val app : traversal -> (elem -> unit) -> array -> unit
  val foldi : traversal -> (int * int * elem * 'b -> 'b) -> 'b -> region -> 'b
  val fold : traversal -> (elem * 'b -> 'b) -> 'b -> array -> 'b
  val modifyi : traversal -> (int * int * elem -> elem) -> region -> unit
  val modify : traversal -> (elem -> elem) -> array -> unit
end
