(* Generated by scripts/gen-basis-sigs.sh from tests/basis/spec-sigs/IO.sml; do not edit. *)
(* signature IO, transcribed from https://smlfamily.github.io/Basis/io.html *)
signature IO =
sig
  exception Io of {name : string, function : string, cause : exn}
  exception BlockingNotSupported
  exception NonblockingNotSupported
  exception RandomAccessNotSupported
  exception ClosedStream
  datatype buffer_mode = NO_BUF | LINE_BUF | BLOCK_BUF
end
