(* Generated by scripts/gen-basis-sigs.sh from tests/basis/spec-sigs/NET_PROT_DB.sml; do not edit. *)
(* signature NET_PROT_DB, transcribed from
   https://smlfamily.github.io/Basis/prot-db.html *)
signature NET_PROT_DB =
sig
  type entry
  val name : entry -> string
  val aliases : entry -> string list
  val protocol : entry -> int
  val getByName : string -> entry option
  val getByNumber : int -> entry option
end
