(* Generated by scripts/gen-basis-sigs.sh from tests/basis/spec-sigs/COMMAND_LINE.sml; do not edit. *)
(* signature COMMAND_LINE, transcribed from
   https://smlfamily.github.io/Basis/command-line.html *)
signature COMMAND_LINE =
sig
  val name : unit -> string
  val arguments : unit -> string list
end
