(* Generated by scripts/gen-basis-sigs.sh from tests/basis/spec-sigs/GENERAL.sml; do not edit. *)
(* signature GENERAL, transcribed from https://smlfamily.github.io/Basis/general.html

   The page specifies `type exn = exn`; here that equates General.exn with the
   top-level exn, which is what the page means ("All of the types and values
   defined in General are available unqualified at the top-level"). *)
signature GENERAL =
sig
  eqtype unit
  type exn = exn

  exception Bind
  exception Match
  exception Chr
  exception Div
  exception Domain
  exception Fail of string
  exception Overflow
  exception Size
  exception Span
  exception Subscript

  val exnName : exn -> string
  val exnMessage : exn -> string

  datatype order = LESS | EQUAL | GREATER

  val ! : 'a ref -> 'a
  val := : 'a ref * 'a -> unit
  val o : ('b -> 'c) * ('a -> 'b) -> 'a -> 'c
  val before : 'a * unit -> 'a
  val ignore : 'a -> unit
end
