(* Generated by runeisa from src/isa -- do not edit. *)
structure Opcodes =
struct
  (* the version of the layout of an .rbc, and the fingerprint of the
     instruction set, which an .rbc and an image carry *)
  val rbcVersion = 4
  val fingerprint = 11069976
  val fingerprintHex = "00a8ea18"
  val HALT = 0
  val CONST = 1
  val INT = 2
  val UNIT = 3
  val CON0 = 4
  val LOCAL = 5
  val SETLOCAL = 6
  val ENV = 7
  val SELF = 8
  val GLOBAL = 9
  val SETGLOBAL = 10
  val POP = 11
  val TUPLE = 12
  val SELECT = 13
  val CON = 14
  val DECON = 15
  val CONTAG = 16
  val CLOSURE = 17
  val SETENV = 18
  val CALL = 19
  val TAILCALL = 20
  val RET = 21
  val JUMP = 22
  val JUMPIFNOT = 23
  val JUMPIF = 24
  val PUSHHANDLER = 25
  val POPHANDLER = 26
  val RAISE = 27
  val NEWEXN = 28
  val BUILTINEXN = 29
  val MKEXN = 30
  val EXNCON = 31
  val EXNARG = 32
  val PRIM = 33
  val JUMPIFNOTTAG = 34
  val TEELOCAL = 35
  val CALLK = 36
  val SWITCH = 37
  val TAILCALLK = 38
  val CONN = 39
  val FIELD = 40
  val count = 41
  val names = Vector.fromList ["HALT", "CONST", "INT", "UNIT", "CON0", "LOCAL", "SETLOCAL", "ENV", "SELF", "GLOBAL", "SETGLOBAL", "POP", "TUPLE", "SELECT", "CON", "DECON", "CONTAG", "CLOSURE", "SETENV", "CALL", "TAILCALL", "RET", "JUMP", "JUMPIFNOT", "JUMPIF", "PUSHHANDLER", "POPHANDLER", "RAISE", "NEWEXN", "BUILTINEXN", "MKEXN", "EXNCON", "EXNARG", "PRIM", "JUMPIFNOTTAG", "TEELOCAL", "CALLK", "SWITCH", "TAILCALLK", "CONN", "FIELD"]
  val nargs = Vector.fromList [0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 2, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 2, 1, 2, 1, 2, 2, 2]
end

(* The opcodes as a datatype, for code that says what it does with each
   one: MLton's build of runeopt treats a match that leaves one out as an
   error, so a new opcode cannot go without its template. *)
structure Opcode =
struct
  datatype t =
      HALT
    | CONST
    | INT
    | UNIT
    | CON0
    | LOCAL
    | SETLOCAL
    | ENV
    | SELF
    | GLOBAL
    | SETGLOBAL
    | POP
    | TUPLE
    | SELECT
    | CON
    | DECON
    | CONTAG
    | CLOSURE
    | SETENV
    | CALL
    | TAILCALL
    | RET
    | JUMP
    | JUMPIFNOT
    | JUMPIF
    | PUSHHANDLER
    | POPHANDLER
    | RAISE
    | NEWEXN
    | BUILTINEXN
    | MKEXN
    | EXNCON
    | EXNARG
    | PRIM
    | JUMPIFNOTTAG
    | TEELOCAL
    | CALLK
    | SWITCH
    | TAILCALLK
    | CONN
    | FIELD
  val all : t vector = Vector.fromList [HALT, CONST, INT, UNIT, CON0, LOCAL, SETLOCAL, ENV, SELF, GLOBAL, SETGLOBAL, POP, TUPLE, SELECT, CON, DECON, CONTAG, CLOSURE, SETENV, CALL, TAILCALL, RET, JUMP, JUMPIFNOT, JUMPIF, PUSHHANDLER, POPHANDLER, RAISE, NEWEXN, BUILTINEXN, MKEXN, EXNCON, EXNARG, PRIM, JUMPIFNOTTAG, TEELOCAL, CALLK, SWITCH, TAILCALLK, CONN, FIELD]
  fun fromInt (n : int) : t = Vector.sub (all, n)
end
