(* Generated by runeisa from src/isa -- do not edit. *)
structure RegCodes =
struct
  (* the fingerprint of the register instruction set, which its .rbc
     carries; the layout's version is the stack bytecode's *)
  val fingerprint = 3716966
  val fingerprintHex = "0038b766"
  val HALT = 0
  val MOVE = 1
  val INT = 2
  val CONST = 3
  val UNIT = 4
  val CON0 = 5
  val GLOBAL = 6
  val SETGLOBAL = 7
  val ENV = 8
  val SELF = 9
  val CALL = 10
  val RESULT = 11
  val TAILCALL = 12
  val RET = 13
  val PRIM = 14
  val PRIMPUSH = 15
  val TUPLE = 16
  val CLOSURE = 17
  val SELECT = 18
  val CON = 19
  val DECON = 20
  val CONTAG = 21
  val NEWEXN = 22
  val BUILTINEXN = 23
  val MKEXN = 24
  val EXNCON = 25
  val EXNARG = 26
  val SETENV = 27
  val JUMP = 28
  val JUMPIF = 29
  val JUMPIFNOT = 30
  val JUMPIFNOTTAG = 31
  val PUSHHANDLER = 32
  val POPHANDLER = 33
  val CATCH = 34
  val RAISE = 35
  val CALLK = 36
  val TAILCALLK = 37
  val SWITCH = 38
  val CONN = 39
  val FIELD = 40
  val count = 41
  val names = Vector.fromList ["HALT", "MOVE", "INT", "CONST", "UNIT", "CON0", "GLOBAL", "SETGLOBAL", "ENV", "SELF", "CALL", "RESULT", "TAILCALL", "RET", "PRIM", "PRIMPUSH", "TUPLE", "CLOSURE", "SELECT", "CON", "DECON", "CONTAG", "NEWEXN", "BUILTINEXN", "MKEXN", "EXNCON", "EXNARG", "SETENV", "JUMP", "JUMPIF", "JUMPIFNOT", "JUMPIFNOTTAG", "PUSHHANDLER", "POPHANDLER", "CATCH", "RAISE", "CALLK", "TAILCALLK", "SWITCH", "CONN", "FIELD"]
end
