#!/bin/sh
# Generate what Rune compiles a program of the xc2:mlton configuration of
# tests/basis/run-matrix.sh with: MLton's Basis Library and the shim that
# makes MLton's primitives of Rune's (tests/basis/xc2/README.md).
#   tests/basis/xc2/mlton/gen.sh OUTDIR [MLTON_LIB]      (RUNE: bin/rune)
# MLTON_LIB is MLton's library directory (default: the lib/mlton next to the
# bin of the mlton on PATH); the library's sources are MLTON_LIB/sml/basis,
# with basis.patch applied (XC2_MLTON_BASIS names a directory to take as it
# is instead, when working on the patch). Writes to OUTDIR:
#   prefix          the files a program compiles before its own, in order:
#                   prologue.sml, consts.sml, shim.sml, prims.sml, stubs.sml
#                   and src/*
#   src/NNNN-NAME.sml  the sources of MLton's basis.mlb in load order
#                   (../flatten.sh), MLton's extensions (_prim, _import,
#                   _const, ...) replaced by names of the shim (rewrite.awk)
#   consts.sml      XC2Consts.table: MLton's integer constants
#   prims.sml       the primitives that come in families (prims.awk)
#   stubs.sml       XC2Prim, XC2FFI and XC2Symbol: a value for every
#                   primitive, which raises unless the shim implements it
#   lib             the part of Rune's library the shim needs (../trim-lib.sh)
#   flags           the options of the compiler: --default-type=int64 and
#                   word64
set -eu

[ $# -ge 1 ] || { echo "usage: tests/basis/xc2/mlton/gen.sh OUTDIR [MLTON_LIB]" >&2; exit 2; }
mkdir -p "$1"
out=$(cd "$1" && pwd)
cd "$(dirname "$0")/../../../.."
here=$(pwd)/tests/basis/xc2/mlton
xc2=$(pwd)/tests/basis/xc2
if [ $# -ge 2 ]; then lib=$2
else
  m=$(command -v mlton) || { echo "xc2/mlton/gen.sh: no mlton on PATH" >&2; exit 2; }
  lib=$(cd "$(dirname "$m")/../lib/mlton" && pwd)
fi
target=$lib/targets/self
[ -f "$target/constants" ] || { echo "xc2/mlton/gen.sh: no $target/constants" >&2; exit 2; }

if [ -n "${XC2_MLTON_BASIS:-}" ]; then basis=$XC2_MLTON_BASIS
else
  rm -rf "$out/mlton-basis"
  cp -R "$lib/sml/basis" "$out/mlton-basis"
  chmod -R u+w "$out/mlton-basis"
  (cd "$out/mlton-basis" && patch -s -p1 < "$here/basis.patch")
  basis=$out/mlton-basis
fi

# The configuration of the build: 64-bit int and word, the types of Rune's
# int and word, as the xc1 configuration of MLton has them.
vars="OBJPTR_REP=rep64 SEQINDEX_INT=int64 SEQUENCE_METADATA_SIZE=size192"
vars="$vars NORMAL_METADATA_SIZE=size64 DEFAULT_INT=int64 DEFAULT_WORD=word64"
vars="$vars DEFAULT_REAL=real64 DEFAULT_CHAR=char8 DEFAULT_WIDECHAR=widechar32"
vars="$vars LIB_MLTON_DIR=$lib TARGET=self"
# MLton's overloading of the arithmetic of its types is left out: Rune's
# compiler overloads the operators at the same types (they are Rune's).
awk -v vars="$vars" -f "$xc2/mlb-flatten.awk" "$basis/basis.mlb" |
  grep -v '/libs/basis-2002/top-level/overloads.sml$' > "$out/flat"

# The constants: those of MLton's constants file, and the build constants,
# which MLton's compiler sets.
{
  sed -n 's/^const::\([A-Za-z0-9_]*\) = \(.*\)$/\1	\2/p' "$target/constants"
  printf '%s\t%s\n' MLton_Align_align 8 MLton_Codegen_codegen 0 \
    MLton_FFI_numExports 0 MLton_Platform_Format executable MLton_Profile_isOn false
} > "$out/consts"
# The C types: C_X is an IntN, WordN or RealN (c-types.sml of the target).
awk '
/^structure C_[A-Za-z0-9_]* = struct open (Int|Word|Real)[0-9]+ / { T[$2] = $6; next }
/^structure C_[A-Za-z0-9_]* = C_[A-Za-z0-9_]*$/ { A[$2] = $4 }
END { for (n in A) { t = A[n]; while (t in A) t = A[t]; T[n] = T[t] } for (n in T) print n "\t" T[n] }
' "$target/sml/c-types.sml" > "$out/ctypes"

# The integer constants as SML, for the shim: XC2Consts.table, (name, value)
{
  echo "(* Generated by tests/basis/xc2/mlton/gen.sh -- do not edit. *)"
  echo "structure XC2Consts ="
  echo "struct"
  echo "  val table : (string * int) list = ["
  awk -F"\t" '$2 ~ /^-?[0-9]+$/ && length($2) < 19 { v = $2; sub(/^-/, "~", v); printf "%s    (\"%s\", %s)", (n++ ? ",\n" : ""), $1, v } END { print "" }' "$out/consts"
  echo "  ]"
  echo "end"
} > "$out/consts.sml"

# The table of the extensions, and the names used at more than one type
rm -f "$out/table"
sed -n 's/^file //p' "$out/flat" | sort -u | while read -r f; do
  awk -v table="$out/table" -v consts="$out/consts" -v ctypes="$out/ctypes" -f "$here/rewrite.awk" "$f" > /dev/null
done
sort -u "$out/table" -o "$out/table"
cut -f1,2 "$out/table" | uniq -d > "$out/ambiguous"

sh "$xc2/flatten.sh" "$out/flat" "$out" "$basis" \
  awk -v consts="$out/consts" -v ctypes="$out/ctypes" -v ambiguous="$out/ambiguous" -f "$here/rewrite.awk"

# The primitives that come in families (prims.awk)
awk -v ctypes="$out/ctypes" -v ambiguous="$out/ambiguous" -f "$here/prims.awk" "$out/table" > "$out/prims.sml"

# The stubs: a value for every extension of the table, which raises
# XC2.Unimplemented when it is applied.
awk -F'\t' -v ambiguous="$out/ambiguous" '
BEGIN { while ((getline l < ambiguous) > 0) AMB[l] = 1 }
function mangle(t) {
  gsub(/->/, " to ", t); gsub(/\*/, " x ", t); gsub(/'"'"'/, "q", t)
  gsub(/[^A-Za-z0-9]+/, "_", t); sub(/^_/, "", t); sub(/_$/, "", t)
  return t
}
{
  id = $2; if (($1 "\t" $2) in AMB) id = $2 "__" mangle($3)
  if ((id, $1) in DONE) next
  DONE[id, $1] = 1
  if ($1 == "symbol")
    V[$1] = V[$1] "  val " id " = (fn () => XC2.unimplemented \"_symbol " $2 "\", fn _ => XC2.unimplemented \"_symbol " $2 "\")\n"
  else
    V[$1] = V[$1] "  val " id " = fn _ => XC2.unimplemented \"_" $1 " " $2 "\"\n"
}
END {
  print "(* Generated by tests/basis/xc2/mlton/gen.sh -- do not edit. *)"
  split("prim XC2Prim import XC2FFI symbol XC2Symbol address XC2Address", k, " ")
  split("XC2PrimImpl XC2PrimGen,XC2FFIImpl XC2FFIReal,XC2SymbolImpl,", impl, ",")
  for (i = 1; i < 8; i += 2) {
    o = impl[(i + 1) / 2]; gsub(/[^ ]+/, "  open &\n", o)
    print "structure " k[i + 1] " =\nstruct\n" V[k[i]] o "end"
  }
  print "(* the sources of MLton start where nothing is infix (the top-level infixes\n   come with top-level/infixes.sml), and the library of Rune has left its\n   own: *)"
  print "nonfix * / div mod + - ^ @ <> > >= < <= := o before"
}
' "$out/table" > "$out/stubs.sml"

# What a program compiles first: the prologue, the shim and the sources (the
# first two copied, so that a run compiles one version of them throughout).
cp "$xc2/xc2.sml" "$here/prologue.sml" "$here/shim.sml" "$out/"
{
  echo "$out/xc2.sml"
  echo "$out/prologue.sml"
  echo "$out/consts.sml"
  echo "$out/shim.sml"
  echo "$out/prims.sml"
  echo "$out/stubs.sml"
  cat "$out/files"
} > "$out/prefix"

# MLton's library is built for a 64-bit int and word (above), which are
# Rune's Int64.int and Word64.word; Rune's int and word have 63 bits. As
# MLton's -default-type int64 does, --default-type makes them the types of
# the constants and the arithmetic that a declaration leaves open, in the
# library and in the test programs.
echo --default-type=int64 --default-type=word64 > "$out/flags"

# The part of Rune's library the shim needs
# shellcheck disable=SC2046
sh "$xc2/trim-lib.sh" "$out" $(sed 6q "$out/prefix")
