#!/bin/sh
# Generate what Rune compiles a program of the xc2:smlnj-legacy configuration of
# tests/basis/run-matrix.sh with: SML/NJ's Basis Library and its init
# library, and the shim that makes SML/NJ's primitives and C functions of
# Rune's (tests/basis/xc2/README.md).
#   tests/basis/xc2/smlnj-legacy/gen.sh OUTDIR SMLNJ      (RUNE: bin/rune)
# SMLNJ is SML/NJ's installation: its sml runs CM to find the order of the
# library's files, and SMLNJ/system holds their sources (system.tgz of the
# release, which scripts/fetch-hosts.sh unpacks there), with basis.patch
# applied (XC2_SMLNJ_BASIS names a patched system directory to take as it is
# instead, when working on the patch). Writes to OUTDIR:
#   prefix          the files a program compiles before its own, in order
#   src/NNNN-NAME.sml  the files of the init library (smlnj/init, in the
#                   order of its init.cmi, some replaced by the shim) and of
#                   the Basis Library (Basis, in the order of CM), SML/NJ's
#                   extensions and C functions replaced (rewrite.awk)
#   stubs.sml       XC2NC: a value for every C function, which raises unless
#                   cfuns.sml implements it
#   lib             the part of Rune's library the shim needs (../trim-lib.sh)
#   flags           what Rune compiles a program with besides --allow-prim:
#                   --or-patterns, which SML/NJ's library uses
set -eu

[ $# = 2 ] || { echo "usage: tests/basis/xc2/smlnj-legacy/gen.sh OUTDIR SMLNJ" >&2; exit 2; }
mkdir -p "$1"
out=$(cd "$1" && pwd)
smlnj=$(cd "$2" && pwd)
cd "$(dirname "$0")/../../../.."
here=$(pwd)/tests/basis/xc2/smlnj-legacy
xc2=$(pwd)/tests/basis/xc2
[ -f "$smlnj/system/Basis/basis.cm" ] || { echo "xc2/smlnj-legacy/gen.sh: no sources in $smlnj/system (system.tgz)" >&2; exit 2; }

# The order of CM, of the sources as they are: CM puts the files of a group
# after those of the groups it uses, and the flat order keeps the groups
# apart (TypesOnly, Implementation, then Exports, which bind the names a
# program sees).
rm -rf "$out/cm"
mkdir -p "$out/cm"
cp -R "$smlnj/system/Basis" "$smlnj/system/smlnj" "$out/cm/"
XC2_CM="$out/cm/Basis/basis-common.cm" "$smlnj/bin/sml" "$here/order.sml" < /dev/null > "$out/cm.log" 2>&1 || true
sed -n 's/^FILE //p' "$out/cm.log" > "$out/order.cm"
[ -s "$out/order.cm" ] || { echo "xc2/smlnj-legacy/gen.sh: CM gave no order (see $out/cm.log)" >&2; exit 1; }
{ grep '^TypesOnly/' "$out/order.cm"; grep '^Implementation/' "$out/order.cm"; grep '^Exports/' "$out/order.cm"; } > "$out/order"

if [ -n "${XC2_SMLNJ_BASIS:-}" ]; then system=$XC2_SMLNJ_BASIS
else
  rm -rf "$out/system"
  mkdir -p "$out/system/smlnj"
  cp -R "$smlnj/system/Basis" "$out/system/Basis"
  cp -R "$smlnj/system/smlnj/init" "$out/system/smlnj/init"
  chmod -R u+w "$out/system"
  (cd "$out/system" && patch -s -p1 < "$here/basis.patch")
  system=$out/system
fi

rm -rf "$out/src"
mkdir -p "$out/src"
: > "$out/table"
: > "$out/files"
i=0
emit() { # emit FILE: FILE rewritten, as the next file of the program
  i=$((i + 1))
  dst=$out/src/$(printf '%04d' "$i")-$(basename "$1")
  awk -v table="$out/table" -f "$here/rewrite.awk" "$1" > "$dst"
  echo "$dst" >> "$out/files"
}
# The init library (init.cmi, for a 64-bit target), where the files that
# stand on SML/NJ's runtime and representations are the shim's: the runtime's
# Assembly (dummy.sml), Core and CoreIntInf (target64-core.sml,
# target64-core-intinf.sml), InlineT (target64-inline.sml) and MathInlineT
# (math-built-in.sml). rawmem-dummy.sml is empty.
init=$system/smlnj/init
emit "$init/assembly.sig"
emit "$here/rts.sml"
emit "$init/order.sml"
emit "$here/core.sml"
emit "$init/xcore.sml"
emit "$here/inline.sml"
first=$((i + 1))
for f in pre-perv.sml pre-string.sml substring.sig substring.sml print-hook.sml use-hook.sml \
         exn-info-hook.sml init-utils.sml pervasive.sml; do
  emit "$init/$f"
done
# nothing is infix where the init library starts (after the shim); the
# library of Rune has left its own
sed -i "1s/^/nonfix * \/ div mod + - ^ @ <> > >= < <= := o before\n/" "$(sed -n "${first}p" "$out/files")"
while read -r f; do emit "$system/Basis/$f"; done < "$out/order"
sort -u "$out/table" -o "$out/table"

# The stubs: a value for every C function of the table, which raises
# XC2.Unimplemented when it is applied.
{
  echo "(* Generated by tests/basis/xc2/smlnj-legacy/gen.sh -- do not edit. *)"
  echo "structure XC2NC ="
  echo "struct"
  awk -F'\t' '!($1 in D) { D[$1] = 1; print "  val " $1 " = fn _ => XC2.unimplemented \"c_function " $2 " " $3 "\"" }' "$out/table"
  echo "  open XC2NCImpl"
  echo "end"
} > "$out/stubs.sml"

# What a program compiles first: the prologue, the C functions and the
# sources (the shim copied, so that a run compiles one version of it
# throughout).
cp "$xc2/xc2.sml" "$here/prologue.sml" "$here/cfuns.sml" "$out/"
{
  echo "$out/xc2.sml"
  echo "$out/prologue.sml"
  echo "$out/cfuns.sml"
  echo "$out/stubs.sml"
  cat "$out/files"
} > "$out/prefix"

echo --or-patterns > "$out/flags"

# The part of Rune's library the shim needs
# shellcheck disable=SC2046
sh "$xc2/trim-lib.sh" "$out" $(sed 4q "$out/prefix") \
  $(grep -e '-rts\.sml$' -e '-core\.sml$' -e '-inline\.sml$' "$out/files")
