#!/bin/sh
# Generate what Rune compiles a program of the xc2:mlkit configuration of
# tests/basis/run-matrix.sh with: MLKit's Basis Library and the shim that
# makes MLKit's primitives of Rune's (tests/basis/xc2/README.md).
#   tests/basis/xc2/mlkit/gen.sh OUTDIR MLKIT_LIB      (RUNE: bin/rune)
# MLKIT_LIB is MLKit's library directory (lib/mlkit); the library's sources
# are MLKIT_LIB/basis, with basis.patch applied (XC2_MLKIT_BASIS names a
# directory to take as it is instead, when working on the patch). Writes to
# OUTDIR:
#   prefix          the files a program compiles before its own, in order:
#                   prologue.sml, shim.sml, stubs.sml and src/*
#   src/NNNN-NAME.sml  the sources of MLKit's basis.mlb in load order
#                   (../flatten.sh), MLKit's primitives replaced by names of
#                   the shim (rewrite.awk)
#   stubs.sml       XC2KPrim: a value for every primitive, which raises
#                   unless the shim implements it
#   lib             the part of Rune's library the shim needs (../trim-lib.sh)
set -eu

[ $# = 2 ] || { echo "usage: tests/basis/xc2/mlkit/gen.sh OUTDIR MLKIT_LIB" >&2; exit 2; }
mkdir -p "$1"
out=$(cd "$1" && pwd)
lib=$(cd "$2" && pwd)
cd "$(dirname "$0")/../../../.."
here=$(pwd)/tests/basis/xc2/mlkit
xc2=$(pwd)/tests/basis/xc2

if [ -n "${XC2_MLKIT_BASIS:-}" ]; then basis=$XC2_MLKIT_BASIS
else
  rm -rf "$out/mlkit-basis"
  mkdir -p "$out/mlkit-basis"
  # the sources only, not what MLKit compiled from them (MLB/, *.log)
  (cd "$lib/basis" && find . -name MLB -prune -o \( -name '*.sml' -o -name '*.sig' -o -name '*.mlb' \) -print | tar -cf - -T -) |
    (cd "$out/mlkit-basis" && tar -xf -)
  chmod -R u+w "$out/mlkit-basis"
  (cd "$out/mlkit-basis" && patch -s -p1 < "$here/basis.patch")
  basis=$out/mlkit-basis
fi

awk -f "$xc2/mlb-flatten.awk" "$basis/basis.mlb" > "$out/flat"

# The table of the primitives
rm -f "$out/table"
sed -n 's/^file //p' "$out/flat" | sort -u | while read -r f; do
  awk -v table="$out/table" -v typed="$here/typed.txt" -f "$here/rewrite.awk" "$f" > /dev/null
done
sort -u "$out/table" -o "$out/table"

sh "$xc2/flatten.sh" "$out/flat" "$out" "$basis" awk -v typed="$here/typed.txt" -f "$here/rewrite.awk"

# The constants of MLKit's IntInf.int, which MLKit's compiler reads itself:
# Rune's overloads them from where IntInf is made on (_overload, with
# --allow-prim).
cat > "$out/intinf-literals.sml" <<'EOF'
(* Generated by tests/basis/xc2/mlkit/gen.sh -- do not edit. *)
structure XC2KIntInfLit = struct fun fromLit s = valOf (IntInf.fromString s) end
_overload int IntInf via XC2KIntInfLit.fromLit
EOF
awk -v add="$out/intinf-literals.sml" '{ print } /-IntInf\.sml$/ { print add }' "$out/files" > "$out/files.tmp"
mv "$out/files.tmp" "$out/files"

# The stubs: a value for every primitive of the table, which raises
# XC2.Unimplemented when it is applied.
awk -F'\t' '
!($1 in DONE) { DONE[$1] = 1; V = V "  val " $1 " = fn _ => XC2.unimplemented \"prim " $2 "\"\n" }
END {
  print "(* Generated by tests/basis/xc2/mlkit/gen.sh -- do not edit. *)"
  print "structure XC2KPrim =\nstruct\n" V "  open XC2KPrimImpl\nend"
}
' "$out/table" > "$out/stubs.sml"

# What a program compiles first: the prologue, the shim and the sources (the
# first two copied, so that a run compiles one version of them throughout).
cp "$xc2/xc2.sml" "$here/prologue.sml" "$here/shim.sml" "$out/"
{
  echo "$out/xc2.sml"
  echo "$out/prologue.sml"
  echo "$out/shim.sml"
  echo "$out/stubs.sml"
  cat "$out/files"
} > "$out/prefix"

# The part of Rune's library the shim needs
# shellcheck disable=SC2046
sh "$xc2/trim-lib.sh" "$out" $(sed 4q "$out/prefix")
