#!/bin/sh
# Generate the sources with which a host system compiles Rune's Basis Library
# (the xc1 configurations of tests/basis/run-matrix.sh).
#   tests/basis/host/gen-host-basis.sh OUTDIR
# Writes to OUTDIR:
#   RUNE_PRIM.sml   signature RUNE_PRIM: a `val` per primitive of vm/prims.def
#                   with the type of its TYPE column
#   basis/*.sml     lib/basis with `_prim "name"` replaced by `RunePrim.name`
#                   and without its `_overload` declarations (a host has its
#                   own, closed, overloading)
#   hide.sml        rebinds the top-level values of the Basis Library to a
#                   value of no use, so that a test cannot pass with the
#                   host's `exnName` where lib/basis does not define one
#   prelude         the files to load first: RUNE_PRIM.sml, rune-prim.sml, hide.sml
#   files           "FILE<TAB>STRUCTURES": the files of lib/basis/MANIFEST in
#                   load order with the structures each one declares
# The same output serves every host.
#
# The host column of lib/basis/MANIFEST says how a file is given to a host:
# yes, as it is; no, not at all; swap, without its top-level datatype and
# exception declarations. The latter is for the file that declares the types
# and exceptions that primitives and the host's own library share with the
# program (option, order, Fail, ...): on a host those must remain the host's;
# what the file defines in terms of them is kept. IEEEReal.Unordered takes
# the place of Rune's top-level Unordered.
set -eu

[ $# = 1 ] || { echo "usage: tests/basis/host/gen-host-basis.sh OUTDIR" >&2; exit 2; }
mkdir -p "$1/basis"
out=$(cd "$1" && pwd)
cd "$(dirname "$0")/../../.."
here=$(pwd)/tests/basis/host

# poly_eq and ptr_eq are what the compiler makes of `=` and of exception
# matching; no library source names them, and no host can give them a type.
awk '
BEGIN {
  print "(* Generated by tests/basis/host/gen-host-basis.sh from vm/prims.def -- do not edit. *)"
  print "signature RUNE_PRIM ="
  print "sig"
}
/^[[:space:]]*#/ || /^[[:space:]]*$/ { next }
$1 == "poly_eq" || $1 == "ptr_eq" { next }
{
  line = $0
  sub(/^[^ \t]+[ \t]+[^ \t]+[ \t]+/, "", line)
  n = match(line, /  |\t/)
  printf("  val %s : %s\n", $1, n ? substr(line, 1, n - 1) : line)
}
END { print "end" }
' vm/prims.def > "$out/RUNE_PRIM.sml"

# The values of the top-level environment of the specification, except the
# overloaded operators and `ref ! :=`, which Rune's compiler supplies too.
{
  echo '(* Generated by tests/basis/host/gen-host-basis.sh -- do not edit. *)'
  echo 'datatype not_in_lib_basis = NotInLibBasis'
  for v in app ceil chr concat exnMessage exnName explode floor foldl foldr getOpt hd ignore \
           implode isSome length map not null ord print real rev round size str substring tl \
           trunc valOf vector 'op @' 'op ^' 'op o' 'op before'; do
    echo "val $v = NotInLibBasis"
  done
} > "$out/hide.sml"

printf '%s\n' "$out/RUNE_PRIM.sml" "$here/rune-prim.sml" "$out/hide.sml" > "$out/prelude"

: > "$out/files"
grep -v -E '^[[:space:]]*(#|$)' lib/basis/MANIFEST | while IFS='|' read -r f _ host _; do
  f=$(echo $f)
  host=$(echo $host)
  [ "$host" = no ] && continue
  dest=$out/basis/$f
  # Line numbers stay those of lib/basis.
  if [ "$host" = swap ]; then
    awk '/^exception Unordered$/ { print "exception Unordered = IEEEReal.Unordered"; next }
         /^(datatype|exception) / { print ""; next }
         { print }' "lib/basis/$f"
  else
    cat "lib/basis/$f"
  fi | sed -e 's/_prim "\([a-z_0-9]*\)"/RunePrim.\1/g' -e 's/^_overload .*//' > "$dest"
  structures=$(sed -n 's/^structure \([A-Za-z0-9_]*\).*/\1/p' "lib/basis/$f" | tr '\n' ' ')
  printf '%s\t%s\n' "$dest" "${structures% }" >> "$out/files"
done
