/* Generated by runeisa from src/isa -- do not edit.
   The cases of the JIT's walk over a function (vm/new/jit/compile.c):
   each instruction's operands read as the loop reads them, and its
   emitter called. */
case ROP_HALT: {
    emit_HALT(j, pc);
    break;
}
case ROP_MOVE: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    emit_MOVE(j, pc, a, b);
    break;
}
case ROP_INT: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    emit_INT(j, pc, a, b);
    break;
}
case ROP_CONST: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    emit_CONST(j, pc, a, b);
    break;
}
case ROP_UNIT: {
    int32_t a = read_i32(code + pc + 1);
    emit_UNIT(j, pc, a);
    break;
}
case ROP_CON0: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    emit_CON0(j, pc, a, b);
    break;
}
case ROP_GLOBAL: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    emit_GLOBAL(j, pc, a, b);
    break;
}
case ROP_SETGLOBAL: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    emit_SETGLOBAL(j, pc, a, b);
    break;
}
case ROP_ENV: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    emit_ENV(j, pc, a, b);
    break;
}
case ROP_SELF: {
    int32_t a = read_i32(code + pc + 1);
    emit_SELF(j, pc, a);
    break;
}
case ROP_CALL: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    emit_CALL(j, pc, a, b);
    break;
}
case ROP_RESULT: {
    int32_t a = read_i32(code + pc + 1);
    emit_RESULT(j, pc, a);
    break;
}
case ROP_TAILCALL: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    emit_TAILCALL(j, pc, a, b);
    break;
}
case ROP_RET: {
    int32_t a = read_i32(code + pc + 1);
    emit_RET(j, pc, a);
    break;
}
case ROP_PRIM: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    const uint8_t *L = code + pc + 9;
    uint32_t n = prim_arity[a];
    emit_PRIM(j, pc, a, b, L, n);
    break;
}
case ROP_PRIMPUSH: {
    int32_t a = read_i32(code + pc + 1);
    const uint8_t *L = code + pc + 5;
    uint32_t n = prim_arity[a];
    emit_PRIMPUSH(j, pc, a, L, n);
    break;
}
case ROP_TUPLE: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    const uint8_t *L = code + pc + 9;
    uint32_t n = (uint32_t)b;
    emit_TUPLE(j, pc, a, b, L, n);
    break;
}
case ROP_CLOSURE: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    int32_t c = read_i32(code + pc + 9);
    const uint8_t *L = code + pc + 13;
    uint32_t n = (uint32_t)c;
    emit_CLOSURE(j, pc, a, b, c, L, n);
    break;
}
case ROP_SELECT: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    int32_t c = read_i32(code + pc + 9);
    emit_SELECT(j, pc, a, b, c);
    break;
}
case ROP_CON: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    int32_t c = read_i32(code + pc + 9);
    emit_CON(j, pc, a, b, c);
    break;
}
case ROP_DECON: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    int32_t c = read_i32(code + pc + 9);
    emit_DECON(j, pc, a, b, c);
    break;
}
case ROP_CONTAG: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    emit_CONTAG(j, pc, a, b);
    break;
}
case ROP_NEWEXN: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    emit_NEWEXN(j, pc, a, b);
    break;
}
case ROP_BUILTINEXN: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    emit_BUILTINEXN(j, pc, a, b);
    break;
}
case ROP_MKEXN: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    int32_t c = read_i32(code + pc + 9);
    emit_MKEXN(j, pc, a, b, c);
    break;
}
case ROP_EXNCON: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    emit_EXNCON(j, pc, a, b);
    break;
}
case ROP_EXNARG: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    emit_EXNARG(j, pc, a, b);
    break;
}
case ROP_SETENV: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    int32_t c = read_i32(code + pc + 9);
    emit_SETENV(j, pc, a, b, c);
    break;
}
case ROP_JUMP: {
    int32_t a = read_i32(code + pc + 1);
    emit_JUMP(j, pc, a);
    break;
}
case ROP_JUMPIF: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    emit_JUMPIF(j, pc, a, b);
    break;
}
case ROP_JUMPIFNOT: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    emit_JUMPIFNOT(j, pc, a, b);
    break;
}
case ROP_JUMPIFNOTTAG: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    int32_t c = read_i32(code + pc + 9);
    emit_JUMPIFNOTTAG(j, pc, a, b, c);
    break;
}
case ROP_PUSHHANDLER: {
    int32_t a = read_i32(code + pc + 1);
    emit_PUSHHANDLER(j, pc, a);
    break;
}
case ROP_POPHANDLER: {
    emit_POPHANDLER(j, pc);
    break;
}
case ROP_CATCH: {
    int32_t a = read_i32(code + pc + 1);
    emit_CATCH(j, pc, a);
    break;
}
case ROP_RAISE: {
    int32_t a = read_i32(code + pc + 1);
    emit_RAISE(j, pc, a);
    break;
}
case ROP_CALLK: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    const uint8_t *L = code + pc + 9;
    uint32_t n = (uint32_t)b;
    emit_CALLK(j, pc, a, b, L, n);
    break;
}
case ROP_TAILCALLK: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    const uint8_t *L = code + pc + 9;
    uint32_t n = (uint32_t)b;
    emit_TAILCALLK(j, pc, a, b, L, n);
    break;
}
case ROP_SWITCH: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    emit_SWITCH(j, pc, a, b);
    break;
}
case ROP_CONN: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    int32_t c = read_i32(code + pc + 9);
    const uint8_t *L = code + pc + 13;
    uint32_t n = (uint32_t)c;
    emit_CONN(j, pc, a, b, c, L, n);
    break;
}
case ROP_FIELD: {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    int32_t c = read_i32(code + pc + 9);
    int32_t d = read_i32(code + pc + 13);
    emit_FIELD(j, pc, a, b, c, d);
    break;
}
