/* Generated by runeisa from src/isa -- do not edit.
   The emitters of tier 1 (vm/new/jit/emit.c), one per instruction of
   src/isa/regs.sml: an instruction without one does not build. */
#ifndef RUNE_JIT_EMIT_H
#define RUNE_JIT_EMIT_H

typedef struct Jit Jit;

void emit_HALT(Jit *j, uint32_t pc);
void emit_MOVE(Jit *j, uint32_t pc, int32_t a, int32_t b);
void emit_INT(Jit *j, uint32_t pc, int32_t a, int32_t b);
void emit_CONST(Jit *j, uint32_t pc, int32_t a, int32_t b);
void emit_UNIT(Jit *j, uint32_t pc, int32_t a);
void emit_CON0(Jit *j, uint32_t pc, int32_t a, int32_t b);
void emit_GLOBAL(Jit *j, uint32_t pc, int32_t a, int32_t b);
void emit_SETGLOBAL(Jit *j, uint32_t pc, int32_t a, int32_t b);
void emit_ENV(Jit *j, uint32_t pc, int32_t a, int32_t b);
void emit_SELF(Jit *j, uint32_t pc, int32_t a);
void emit_CALL(Jit *j, uint32_t pc, int32_t a, int32_t b);
void emit_RESULT(Jit *j, uint32_t pc, int32_t a);
void emit_TAILCALL(Jit *j, uint32_t pc, int32_t a, int32_t b);
void emit_RET(Jit *j, uint32_t pc, int32_t a);
void emit_PRIM(Jit *j, uint32_t pc, int32_t a, int32_t b, const uint8_t *L, uint32_t n);
void emit_PRIMPUSH(Jit *j, uint32_t pc, int32_t a, const uint8_t *L, uint32_t n);
void emit_TUPLE(Jit *j, uint32_t pc, int32_t a, int32_t b, const uint8_t *L, uint32_t n);
void emit_CLOSURE(Jit *j, uint32_t pc, int32_t a, int32_t b, int32_t c, const uint8_t *L, uint32_t n);
void emit_SELECT(Jit *j, uint32_t pc, int32_t a, int32_t b, int32_t c);
void emit_CON(Jit *j, uint32_t pc, int32_t a, int32_t b, int32_t c);
void emit_DECON(Jit *j, uint32_t pc, int32_t a, int32_t b, int32_t c);
void emit_CONTAG(Jit *j, uint32_t pc, int32_t a, int32_t b);
void emit_NEWEXN(Jit *j, uint32_t pc, int32_t a, int32_t b);
void emit_BUILTINEXN(Jit *j, uint32_t pc, int32_t a, int32_t b);
void emit_MKEXN(Jit *j, uint32_t pc, int32_t a, int32_t b, int32_t c);
void emit_EXNCON(Jit *j, uint32_t pc, int32_t a, int32_t b);
void emit_EXNARG(Jit *j, uint32_t pc, int32_t a, int32_t b);
void emit_SETENV(Jit *j, uint32_t pc, int32_t a, int32_t b, int32_t c);
void emit_JUMP(Jit *j, uint32_t pc, int32_t a);
void emit_JUMPIF(Jit *j, uint32_t pc, int32_t a, int32_t b);
void emit_JUMPIFNOT(Jit *j, uint32_t pc, int32_t a, int32_t b);
void emit_JUMPIFNOTTAG(Jit *j, uint32_t pc, int32_t a, int32_t b, int32_t c);
void emit_PUSHHANDLER(Jit *j, uint32_t pc, int32_t a);
void emit_POPHANDLER(Jit *j, uint32_t pc);
void emit_CATCH(Jit *j, uint32_t pc, int32_t a);
void emit_RAISE(Jit *j, uint32_t pc, int32_t a);
void emit_CALLK(Jit *j, uint32_t pc, int32_t a, int32_t b, const uint8_t *L, uint32_t n);
void emit_TAILCALLK(Jit *j, uint32_t pc, int32_t a, int32_t b, const uint8_t *L, uint32_t n);
void emit_SWITCH(Jit *j, uint32_t pc, int32_t a, int32_t b);
void emit_CONN(Jit *j, uint32_t pc, int32_t a, int32_t b, int32_t c, const uint8_t *L, uint32_t n);
void emit_FIELD(Jit *j, uint32_t pc, int32_t a, int32_t b, int32_t c, int32_t d);

#endif
