/* Generated by runeisa from src/isa -- do not edit.
   The cases of vm/new's loop, each the body of its instruction in
   src/isa/regs.sml. */
case ROP_HALT: {
    return 0;
    break;
}
case ROP_MOVE: {
    R(a) = R(b);
    break;
}
case ROP_INT: {
    R(a) = mk_int(b);
    break;
}
case ROP_CONST: {
    R(a) = p->consts[b];
    break;
}
case ROP_UNIT: {
    R(a) = mk_unit();
    break;
}
case ROP_CON0: {
    R(a) = mk_con0(b);
    break;
}
case ROP_GLOBAL: {
    if (!vm->global_set[b]) vm_fatal(vm, "global %d read before initialization", b);
    R(a) = vm->globals[b];
    break;
}
case ROP_SETGLOBAL: {
    vm->globals[a] = R(b);
    vm->global_set[a] = 1;
    break;
}
case ROP_ENV: {
    Obj *c = fr->closure;
    if (!c || (uint32_t)b + 1 >= c->len) vm_fatal(vm, "environment slot %d out of range", b);
    R(a) = OBJ_FIELDS(c)[b + 1];
    break;
}
case ROP_SELF: {
    if (!fr->closure) vm_fatal(vm, "SELF outside a closure");
    R(a) = mk_ptr(fr->closure);
    break;
}
case ROP_CALL: {
    Value arg = R(b);
    Value cv = R(a);
    Obj *c = vm_expect_obj(vm, cv, K_CLOSURE, "closure in call");
    int64_t fidx = OBJ_FIELDS(c)[0].u.i;
    if (fidx < 0 || (uint64_t)fidx >= p->nfuncs) vm_fatal(vm, "bad function index");
    Function *fn = &p->funcs[fidx];
    vm_push_frame(vm, (uint32_t)fidx, c, vm->pc, vm->sp);
    if (vm->sp + fn->nlocals > vm->stack_cap) vm_grow_stack(vm, vm->sp + fn->nlocals);
    Value *slot = &vm->stack[vm->sp];
    slot[0] = arg;
    for (uint32_t i = 1; i < fn->nlocals; i++) slot[i] = mk_unit();
    vm->sp += fn->nlocals;
    vm->pc = fn->code_offset;
    break;
}
case ROP_RESULT: {
    Value v = vm_pop(vm);
    R(a) = v;
    break;
}
case ROP_TAILCALL: {
    Value arg = R(b);
    Value cv = R(a);
    Obj *c = vm_expect_obj(vm, cv, K_CLOSURE, "closure in call");
    int64_t fidx = OBJ_FIELDS(c)[0].u.i;
    if (fidx < 0 || (uint64_t)fidx >= p->nfuncs) vm_fatal(vm, "bad function index");
    Function *fn = &p->funcs[fidx];
    vm->sp = fr->base;
    fr->func = (uint32_t)fidx;
    fr->closure = c;
    if (vm->sp + fn->nlocals > vm->stack_cap) vm_grow_stack(vm, vm->sp + fn->nlocals);
    Value *slot = &vm->stack[vm->sp];
    slot[0] = arg;
    for (uint32_t i = 1; i < fn->nlocals; i++) slot[i] = mk_unit();
    vm->sp += fn->nlocals;
    vm->pc = fn->code_offset;
    break;
}
case ROP_RET: {
    Value v = R(a);
    vm->sp = fr->base;
    vm->pc = fr->ret_pc;
    if (vm->fp == 0) { vm_push(vm, v); return 0; }
    vm->fp--;
    vm_push(vm, v);
    break;
}
case ROP_PRIM: {
    for (uint32_t i = 0; i < n; i++) vm_push(vm, R(LIST(i)));
    /* 1: it raised, and the handler has its exception (vm_raise) */
    int r = prim_table[a](vm);
    if (r == 1) break;
    if (r == PRIM_NEW_WORLD) vm_fatal(vm, "a primitive that changes the world in PRIM");
    Value v = vm_pop(vm);
    R(b) = v;
    break;
}
case ROP_PRIMPUSH: {
    for (uint32_t i = 0; i < n; i++) vm_push(vm, R(LIST(i)));
    /* one that says PRIM_NEW_WORLD has put another program here
       (Runtime.restore): take its code again, and the pc with it */
    if (prim_table[a](vm) == PRIM_NEW_WORLD) code = p->code;
    break;
}
case ROP_TUPLE: {
    if (n == 0) { R(a) = mk_unit(); break; }
    Obj *t = vm_alloc_fields(vm, K_TUPLE, 0, n);
    Value *f = OBJ_FIELDS(t);
    for (uint32_t i = 0; i < n; i++) f[i] = R(LIST(i));
    R(a) = mk_ptr(t);
    break;
}
case ROP_CLOSURE: {
    Obj *c = vm_alloc_fields(vm, K_CLOSURE, 0, n + 1);
    Value *f = OBJ_FIELDS(c);
    f[0] = mk_int(b);
    for (uint32_t i = 0; i < n; i++) f[i + 1] = R(LIST(i));
    R(a) = mk_ptr(c);
    break;
}
case ROP_SELECT: {
    Value v = R(c);
    Obj *t = vm_expect_obj(vm, v, K_TUPLE, "tuple");
    if ((uint32_t)b >= t->len) vm_fatal(vm, "tuple index %d out of range", b);
    R(a) = OBJ_FIELDS(t)[b];
    break;
}
case ROP_CON: {
    Obj *o = vm_alloc_fields(vm, K_CON, (uint16_t)b, 1);
    OBJ_FIELDS(o)[0] = R(c);
    R(a) = mk_ptr(o);
    break;
}
case ROP_DECON: {
    Value v = R(b);
    Obj *o = vm_expect_obj(vm, v, K_CON, "constructor with argument");
    if (vm->checked && o->contag != c) vm_fatal(vm, "DECON of a constructor of tag %d where %d is wanted", (int)o->contag, (int)c);
    R(a) = OBJ_FIELDS(o)[0];
    break;
}
case ROP_CONTAG: {
    Value v = R(b);
    if (v.tag == T_CON0) R(a) = mk_int(v.u.i);
    else if (v.tag == T_PTR && v.u.p->kind == K_CON) R(a) = mk_int(v.u.p->contag);
    else vm_fatal(vm, "CONTAG on non-constructor");
    break;
}
case ROP_NEWEXN: {
    Obj *o = vm_alloc_fields(vm, K_EXNCON, 0, 1);
    OBJ_FIELDS(o)[0] = p->consts[b];
    R(a) = mk_ptr(o);
    break;
}
case ROP_BUILTINEXN: {
    R(a) = mk_ptr(vm->builtin_exns[b]);
    break;
}
case ROP_MKEXN: {
    Obj *e = vm_alloc_fields(vm, K_EXN, 0, 2);
    Value con = R(b);
    if (con.tag != T_PTR || con.u.p->kind != K_EXNCON) vm_fatal(vm, "MKEXN on non-constructor");
    OBJ_FIELDS(e)[0] = con;
    OBJ_FIELDS(e)[1] = R(c);
    R(a) = mk_ptr(e);
    break;
}
case ROP_EXNCON: {
    Value v = R(b);
    Obj *e = vm_expect_obj(vm, v, K_EXN, "exception");
    R(a) = OBJ_FIELDS(e)[0];
    break;
}
case ROP_EXNARG: {
    Value v = R(b);
    Obj *e = vm_expect_obj(vm, v, K_EXN, "exception");
    R(a) = OBJ_FIELDS(e)[1];
    break;
}
case ROP_SETENV: {
    Value cv = R(a);
    Obj *o = vm_expect_obj(vm, cv, K_CLOSURE, "closure");
    if ((uint32_t)b + 1 >= o->len) vm_fatal(vm, "environment slot %d out of range", b);
    OBJ_FIELDS(o)[b + 1] = R(c);
    break;
}
case ROP_JUMP: {
    vm->pc = (uint32_t)a;
    break;
}
case ROP_JUMPIF: {
    Value v = R(a);
    if (v.tag != T_CON0) vm_fatal(vm, "JUMPIF on non-bool");
    if (v.u.i != 0) vm->pc = (uint32_t)b;
    break;
}
case ROP_JUMPIFNOT: {
    Value v = R(a);
    if (v.tag != T_CON0) vm_fatal(vm, "JUMPIFNOT on non-bool");
    if (v.u.i == 0) vm->pc = (uint32_t)b;
    break;
}
case ROP_JUMPIFNOTTAG: {
    Value v = R(a);
    int64_t tag = 0;
    if (v.tag == T_CON0) tag = v.u.i;
    else if (v.tag == T_PTR && v.u.p->kind == K_CON) tag = v.u.p->contag;
    else vm_fatal(vm, "JUMPIFNOTTAG on non-constructor");
    if (tag != c) vm->pc = (uint32_t)b;
    break;
}
case ROP_PUSHHANDLER: {
    vm_push_handler(vm, (uint32_t)a);
    break;
}
case ROP_POPHANDLER: {
    if (vm->hp == 0) vm_fatal(vm, "POPHANDLER with no handler");
    vm->hp--;
    break;
}
case ROP_CATCH: {
    Value v = vm_pop(vm);
    R(a) = v;
    break;
}
case ROP_RAISE: {
    Value v = R(a);
    if (v.tag != T_PTR || v.u.p->kind != K_EXN) vm_fatal(vm, "RAISE of non-exception");
    vm_raise(vm, v);
    break;
}
case ROP_CALLK: {
    Function *fn = &p->funcs[a];
    if (vm->sp + fn->nlocals > vm->stack_cap) vm_grow_stack(vm, vm->sp + fn->nlocals);
    /* the arguments read before the frame is pushed, which R would read */
    Value *slot = &vm->stack[vm->sp];
    for (uint32_t i = 0; i < n; i++) slot[i] = R(LIST(i));
    for (uint32_t i = n; i < fn->nlocals; i++) slot[i] = mk_unit();
    vm_push_frame(vm, (uint32_t)a, NULL, vm->pc, vm->sp);
    vm->sp += fn->nlocals;
    vm->pc = fn->code_offset;
    break;
}
case ROP_TAILCALLK: {
    Function *fn = &p->funcs[a];
    size_t base = fr->base;
    size_t need = vm->sp + n;
    if (base + fn->nlocals > need) need = base + fn->nlocals;
    if (need > vm->stack_cap) vm_grow_stack(vm, need);
    /* the arguments above the frame first, since they are its registers */
    Value *tmp = &vm->stack[vm->sp];
    for (uint32_t i = 0; i < n; i++) tmp[i] = R(LIST(i));
    Value *slot = &vm->stack[base];
    memmove(slot, tmp, (size_t)n * sizeof(Value));
    for (uint32_t i = n; i < fn->nlocals; i++) slot[i] = mk_unit();
    vm->sp = base + fn->nlocals;
    fr->func = (uint32_t)a;
    fr->closure = NULL;
    vm->pc = fn->code_offset;
    break;
}
case ROP_SWITCH: {
    /* the JUMPs are a table, which the loader has checked; each is
       5 bytes, its target after its opcode */
    Value v = R(a);
    int64_t tag = 0;
    if (v.tag == T_CON0) tag = v.u.i;
    else if (v.tag == T_PTR && v.u.p->kind == K_CON) tag = v.u.p->contag;
    else vm_fatal(vm, "SWITCH on non-constructor");
    if (tag >= 0 && tag < b) vm->pc = (uint32_t)read_i32(code + vm->pc + 5 * (uint32_t)tag + 1);
    else vm->pc += 5 * (uint32_t)b;
    break;
}
