/* Generated by runeisa from src/isa -- do not edit.
   The cases of vm/new's loop (vm/new/interp.c), each the body of its
   instruction in src/isa/regs.sml, in the loop's words. */
CASE(HALT) {
    TRACE(ROP_HALT, 0, 0, 0);
    pc += 1;
    count++;
    SYNC();
    return 0;
    NEXT;
}
CASE(MOVE) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    TRACE(ROP_MOVE, a, b, 0);
    pc += 9;
    count++;
    R(a) = R(b);
    NEXT;
}
CASE(INT) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    TRACE(ROP_INT, a, b, 0);
    pc += 9;
    count++;
    R(a) = mk_int(b);
    NEXT;
}
CASE(CONST) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    TRACE(ROP_CONST, a, b, 0);
    pc += 9;
    count++;
    R(a) = p->consts[b];
    NEXT;
}
CASE(UNIT) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(ROP_UNIT, a, 0, 0);
    pc += 5;
    count++;
    R(a) = mk_unit();
    NEXT;
}
CASE(CON0) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    TRACE(ROP_CON0, a, b, 0);
    pc += 9;
    count++;
    R(a) = mk_con0(b);
    NEXT;
}
CASE(GLOBAL) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    TRACE(ROP_GLOBAL, a, b, 0);
    pc += 9;
    count++;
    if (!vm->global_set[b]) FATAL("global %d read before initialization", b);
    R(a) = vm->globals[b];
    NEXT;
}
CASE(SETGLOBAL) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    TRACE(ROP_SETGLOBAL, a, b, 0);
    pc += 9;
    count++;
    vm->globals[a] = R(b);
    vm->global_set[a] = 1;
    NEXT;
}
CASE(ENV) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    TRACE(ROP_ENV, a, b, 0);
    pc += 9;
    count++;
    Obj *c = fr->closure;
    if (!c || (uint32_t)b + 1 >= c->len) FATAL("environment slot %d out of range", b);
    R(a) = OBJ_FIELDS(c)[b + 1];
    NEXT;
}
CASE(SELF) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(ROP_SELF, a, 0, 0);
    pc += 5;
    count++;
    if (!fr->closure) FATAL("SELF outside a closure");
    R(a) = mk_ptr(fr->closure);
    NEXT;
}
CASE(CALL) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    TRACE(ROP_CALL, a, b, 0);
    pc += 9;
    count++;
    Value arg = R(b);
    Obj *c = EXPECT(R(a), K_CLOSURE, "closure in call");
    int64_t fidx = OBJ_FIELDS(c)[0].u.i;
    if (fidx < 0 || (uint64_t)fidx >= p->nfuncs) FATAL("bad function index");
    Function *fn = &p->funcs[fidx];
    size_t top = (size_t)(sp - vm->stack);
    ROOM(top, fn);
    vm_push_frame(vm, (uint32_t)fidx, c, pc, top);
    Value *slot = vm->stack + top;
    slot[0] = arg;
    for (uint32_t i = 1; i < fn->nlocals; i++) slot[i] = mk_unit();
    ENTER(slot, fn);
    HANDOVER((uint32_t)fidx);
    NEXT;
}
CASE(RESULT) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(ROP_RESULT, a, 0, 0);
    pc += 5;
    count++;
    R(a) = POP();
    NEXT;
}
CASE(TAILCALL) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    TRACE(ROP_TAILCALL, a, b, 0);
    pc += 9;
    count++;
    Value arg = R(b);
    Obj *c = EXPECT(R(a), K_CLOSURE, "closure in call");
    int64_t fidx = OBJ_FIELDS(c)[0].u.i;
    if (fidx < 0 || (uint64_t)fidx >= p->nfuncs) FATAL("bad function index");
    Function *fn = &p->funcs[fidx];
    size_t top = fr->base;
    ROOM(top, fn);
    fr->func = (uint32_t)fidx;
    fr->closure = c;
    Value *slot = vm->stack + top;
    slot[0] = arg;
    for (uint32_t i = 1; i < fn->nlocals; i++) slot[i] = mk_unit();
    ENTER(slot, fn);
    HANDOVER((uint32_t)fidx);
    NEXT;
}
CASE(RET) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(ROP_RET, a, 0, 0);
    pc += 5;
    count++;
    Value v = R(a);
    uint32_t back = fr->ret_pc;
    const void *back_native = fr->native_ret;
    size_t top = fr->base;   /* the caller's stack pointer, where the callee's registers began */
    if (vm->fp == 0) { vm->sp = top; vm->pc = back; vm->instructions = count; vm_push(vm, v); return 0; }
    vm->fp--;
    fr = &vm->frames[vm->fp];
    base = vm->stack + fr->base;
    sp = vm->stack + top;
    /* the caller goes on at RESULT d, which takes the value: written
       into d here, and RESULT passed over; anything else takes it from
       the stack, as an image resumed at RESULT does */
    if (code[back] == ROP_RESULT) { R(read_i32(code + back + 1)) = v; pc = back + 5; }
    else { PUSH(v); pc = back; }
    /* a caller in native code takes the frame back where it left it (M5);
       one that kept no address, but whose function has code, goes on in it (M6) */
    if (back_native) RETURN_NATIVE(back_native);
    RESUME_NATIVE(fr->func, pc);
    NEXT;
}
CASE(PRIM) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    const uint8_t *L = code + pc + 9;
    uint32_t n = prim_arity[a];
    TRACE(ROP_PRIM, a, b, 0);
    pc += 9 + 4 * n;
    count++;
    /* the common case of the primitives done in the loop (vm/new/fastprim.h) */
    if (prim_fast(a, n, base, L, &R(b))) NEXT;
    for (uint32_t i = 0; i < n; i++) PUSH(R(LIST(i)));
    SYNC();
    int r = prim_table[a](vm);
    RELOAD();
    /* 1: it raised, and the handler has its exception (vm_raise) */
    if (r == 1) RAISED();
    if (r == PRIM_NEW_WORLD) FATAL("a primitive that changes the world in PRIM");
    R(b) = POP();
    NEXT;
}
CASE(PRIMPUSH) {
    int32_t a = read_i32(code + pc + 1);
    const uint8_t *L = code + pc + 5;
    uint32_t n = prim_arity[a];
    TRACE(ROP_PRIMPUSH, a, 0, 0);
    pc += 5 + 4 * n;
    count++;
    for (uint32_t i = 0; i < n; i++) PUSH(R(LIST(i)));
    SYNC();
    /* one that says PRIM_NEW_WORLD has put another program here
       (Runtime.restore): RELOAD takes its code again, and the pc with
       it, and the JIT's view of the program is made again */
    int r = prim_table[a](vm);
    if (r == PRIM_NEW_WORLD) NEW_PROGRAM();
    RELOAD();
    if (r == 1) RAISED();
    NEXT;
}
CASE(TUPLE) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    const uint8_t *L = code + pc + 9;
    uint32_t n = (uint32_t)b;
    TRACE(ROP_TUPLE, a, b, 0);
    pc += 9 + 4 * n;
    count++;
    if (n == 0) { R(a) = mk_unit(); NEXT; }
    SYNC();
    Obj *t = vm_alloc_fields(vm, K_TUPLE, 0, n);
    Value *f = OBJ_FIELDS(t);
    for (uint32_t i = 0; i < n; i++) f[i] = R(LIST(i));
    R(a) = mk_ptr(t);
    NEXT;
}
CASE(CLOSURE) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    int32_t c = read_i32(code + pc + 9);
    const uint8_t *L = code + pc + 13;
    uint32_t n = (uint32_t)c;
    TRACE(ROP_CLOSURE, a, b, c);
    pc += 13 + 4 * n;
    count++;
    SYNC();
    Obj *cl = vm_alloc_fields(vm, K_CLOSURE, 0, n + 1);
    Value *f = OBJ_FIELDS(cl);
    f[0] = mk_int(b);
    for (uint32_t i = 0; i < n; i++) f[i + 1] = R(LIST(i));
    R(a) = mk_ptr(cl);
    NEXT;
}
CASE(SELECT) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    int32_t c = read_i32(code + pc + 9);
    TRACE(ROP_SELECT, a, b, c);
    pc += 13;
    count++;
    Obj *t = EXPECT(R(c), K_TUPLE, "tuple");
    if ((uint32_t)b >= t->len) FATAL("tuple index %d out of range", b);
    R(a) = OBJ_FIELDS(t)[b];
    NEXT;
}
CASE(CON) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    int32_t c = read_i32(code + pc + 9);
    TRACE(ROP_CON, a, b, c);
    pc += 13;
    count++;
    SYNC();
    Obj *o = vm_alloc_fields(vm, K_CON, (uint16_t)b, 1);
    OBJ_FIELDS(o)[0] = R(c);
    R(a) = mk_ptr(o);
    NEXT;
}
CASE(DECON) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    int32_t c = read_i32(code + pc + 9);
    TRACE(ROP_DECON, a, b, c);
    pc += 13;
    count++;
    Obj *o = EXPECT(R(b), K_CON, "constructor with argument");
    if (vm->checked && o->contag != c) FATAL("DECON of a constructor of tag %d where %d is wanted", (int)o->contag, (int)c);
    R(a) = OBJ_FIELDS(o)[0];
    NEXT;
}
CASE(CONTAG) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    TRACE(ROP_CONTAG, a, b, 0);
    pc += 9;
    count++;
    Value v = R(b);
    if (v.tag == T_CON0) R(a) = mk_int(v.u.i);
    else if (v.tag == T_PTR && v.u.p->kind == K_CON) R(a) = mk_int(v.u.p->contag);
    else FATAL("CONTAG on non-constructor");
    NEXT;
}
CASE(NEWEXN) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    TRACE(ROP_NEWEXN, a, b, 0);
    pc += 9;
    count++;
    SYNC();
    Obj *o = vm_alloc_fields(vm, K_EXNCON, 0, 1);
    OBJ_FIELDS(o)[0] = p->consts[b];
    R(a) = mk_ptr(o);
    NEXT;
}
CASE(BUILTINEXN) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    TRACE(ROP_BUILTINEXN, a, b, 0);
    pc += 9;
    count++;
    R(a) = mk_ptr(vm->builtin_exns[b]);
    NEXT;
}
CASE(MKEXN) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    int32_t c = read_i32(code + pc + 9);
    TRACE(ROP_MKEXN, a, b, c);
    pc += 13;
    count++;
    SYNC();
    Obj *e = vm_alloc_fields(vm, K_EXN, 0, 2);
    Value con = R(b);
    if (con.tag != T_PTR || con.u.p->kind != K_EXNCON) FATAL("MKEXN on non-constructor");
    OBJ_FIELDS(e)[0] = con;
    OBJ_FIELDS(e)[1] = R(c);
    R(a) = mk_ptr(e);
    NEXT;
}
CASE(EXNCON) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    TRACE(ROP_EXNCON, a, b, 0);
    pc += 9;
    count++;
    Obj *e = EXPECT(R(b), K_EXN, "exception");
    R(a) = OBJ_FIELDS(e)[0];
    NEXT;
}
CASE(EXNARG) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    TRACE(ROP_EXNARG, a, b, 0);
    pc += 9;
    count++;
    Obj *e = EXPECT(R(b), K_EXN, "exception");
    R(a) = OBJ_FIELDS(e)[1];
    NEXT;
}
CASE(SETENV) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    int32_t c = read_i32(code + pc + 9);
    TRACE(ROP_SETENV, a, b, c);
    pc += 13;
    count++;
    Obj *o = EXPECT(R(a), K_CLOSURE, "closure");
    if ((uint32_t)b + 1 >= o->len) FATAL("environment slot %d out of range", b);
    OBJ_FIELDS(o)[b + 1] = R(c);
    NEXT;
}
CASE(JUMP) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(ROP_JUMP, a, 0, 0);
    pc += 5;
    count++;
    /* a jump back is a loop's: counted, and where the function has
       code, gone on in it (M6) */
    if ((uint32_t)a < pc) BACKWARD((uint32_t)a);
    pc = (uint32_t)a;
    NEXT;
}
CASE(JUMPIF) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    TRACE(ROP_JUMPIF, a, b, 0);
    pc += 9;
    count++;
    Value v = R(a);
    if (v.tag != T_CON0) FATAL("JUMPIF on non-bool");
    if (v.u.i != 0) pc = (uint32_t)b;
    NEXT;
}
CASE(JUMPIFNOT) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    TRACE(ROP_JUMPIFNOT, a, b, 0);
    pc += 9;
    count++;
    Value v = R(a);
    if (v.tag != T_CON0) FATAL("JUMPIFNOT on non-bool");
    if (v.u.i == 0) pc = (uint32_t)b;
    NEXT;
}
CASE(JUMPIFNOTTAG) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    int32_t c = read_i32(code + pc + 9);
    TRACE(ROP_JUMPIFNOTTAG, a, b, c);
    pc += 13;
    count++;
    Value v = R(a);
    int64_t tag = 0;
    if (v.tag == T_CON0) tag = v.u.i;
    else if (v.tag == T_PTR && v.u.p->kind == K_CON) tag = v.u.p->contag;
    else FATAL("JUMPIFNOTTAG on non-constructor");
    if (tag != c) pc = (uint32_t)b;
    NEXT;
}
CASE(PUSHHANDLER) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(ROP_PUSHHANDLER, a, 0, 0);
    pc += 5;
    count++;
    SYNC();
    vm_push_handler(vm, (uint32_t)a);
    NEXT;
}
CASE(POPHANDLER) {
    TRACE(ROP_POPHANDLER, 0, 0, 0);
    pc += 1;
    count++;
    if (vm->hp == 0) FATAL("POPHANDLER with no handler");
    vm->hp--;
    NEXT;
}
CASE(CATCH) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(ROP_CATCH, a, 0, 0);
    pc += 5;
    count++;
    R(a) = POP();
    NEXT;
}
CASE(RAISE) {
    int32_t a = read_i32(code + pc + 1);
    TRACE(ROP_RAISE, a, 0, 0);
    pc += 5;
    count++;
    Value v = R(a);
    if (v.tag != T_PTR || v.u.p->kind != K_EXN) FATAL("RAISE of non-exception");
    SYNC();
    vm_raise(vm, v);
    RELOAD();
    RAISED();
    NEXT;
}
CASE(CALLK) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    const uint8_t *L = code + pc + 9;
    uint32_t n = (uint32_t)b;
    TRACE(ROP_CALLK, a, b, 0);
    pc += 9 + 4 * n;
    count++;
    Function *fn = &p->funcs[a];
    size_t top = (size_t)(sp - vm->stack);
    ROOM(top, fn);
    /* the arguments read before the frame is pushed, which R would read */
    Value *slot = vm->stack + top;
    for (uint32_t i = 0; i < n; i++) slot[i] = R(LIST(i));
    for (uint32_t i = n; i < fn->nlocals; i++) slot[i] = mk_unit();
    vm_push_frame(vm, (uint32_t)a, NULL, pc, top);
    ENTER(slot, fn);
    HANDOVER((uint32_t)a);
    NEXT;
}
CASE(TAILCALLK) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    const uint8_t *L = code + pc + 9;
    uint32_t n = (uint32_t)b;
    TRACE(ROP_TAILCALLK, a, b, 0);
    pc += 9 + 4 * n;
    count++;
    Function *fn = &p->funcs[a];
    size_t top = fr->base;
    size_t need = (size_t)(sp - vm->stack) + n;
    if (top + fn->nlocals + fn->maxstack > need) need = top + fn->nlocals + fn->maxstack;
    if (need > vm->stack_cap) { SYNC(); vm_grow_stack(vm, need); RELOAD(); }
    /* the arguments above the frame first, since they are its registers */
    Value *tmp = sp;
    for (uint32_t i = 0; i < n; i++) tmp[i] = R(LIST(i));
    Value *slot = vm->stack + top;
    memmove(slot, tmp, (size_t)n * sizeof(Value));
    for (uint32_t i = n; i < fn->nlocals; i++) slot[i] = mk_unit();
    fr->func = (uint32_t)a;
    fr->closure = NULL;
    ENTER(slot, fn);
    HANDOVER((uint32_t)a);
    NEXT;
}
CASE(SWITCH) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    TRACE(ROP_SWITCH, a, b, 0);
    pc += 9;
    count++;
    /* the JUMPs are a table, which the loader has checked; each is
       5 bytes, its target after its opcode */
    Value v = R(a);
    int64_t tag = 0;
    if (v.tag == T_CON0) tag = v.u.i;
    else if (v.tag == T_PTR && v.u.p->kind == K_CON) tag = v.u.p->contag;
    else FATAL("SWITCH on non-constructor");
    if (tag >= 0 && tag < b) pc = (uint32_t)read_i32(code + pc + 5 * (uint32_t)tag + 1);
    else pc += 5 * (uint32_t)b;
    NEXT;
}
CASE(CONN) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    int32_t c = read_i32(code + pc + 9);
    const uint8_t *L = code + pc + 13;
    uint32_t n = (uint32_t)c;
    TRACE(ROP_CONN, a, b, c);
    pc += 13 + 4 * n;
    count++;
    SYNC();
    Obj *o = vm_alloc_fields(vm, K_CON, (uint16_t)b, n);
    Value *f = OBJ_FIELDS(o);
    for (uint32_t i = 0; i < n; i++) f[i] = R(LIST(i));
    R(a) = mk_ptr(o);
    NEXT;
}
CASE(FIELD) {
    int32_t a = read_i32(code + pc + 1);
    int32_t b = read_i32(code + pc + 5);
    int32_t c = read_i32(code + pc + 9);
    int32_t d = read_i32(code + pc + 13);
    TRACE(ROP_FIELD, a, b, c);
    pc += 17;
    count++;
    Obj *o = EXPECT(R(b), K_CON, "constructor with fields");
    if (vm->checked && o->contag != c) FATAL("FIELD of a constructor of tag %d where %d is wanted", (int)o->contag, (int)c);
    if ((uint32_t)d >= o->len) FATAL("constructor field %d out of range", d);
    R(a) = OBJ_FIELDS(o)[d];
    NEXT;
}
