/* Generated by runeisa from src/isa -- do not edit. */
#ifndef RUNE_REGOPS_H
#define RUNE_REGOPS_H

/* The fingerprint of the register instruction set, which its .rbc
   and its images carry. */
#define REG_ISA_FINGERPRINT 0x007d001du
#define REG_ISA_FINGERPRINT_HEX "007d001d"

enum RegOpcode {
  ROP_HALT = 0,  /* Stop execution. */
  ROP_MOVE = 1,  /* Register d := register s. */
  ROP_INT = 2,  /* Register d := the small integer i. */
  ROP_CONST = 3,  /* Register d := constant k. */
  ROP_UNIT = 4,  /* Register d := unit. */
  ROP_CON0 = 5,  /* Register d := the nullary constructor with tag t. */
  ROP_GLOBAL = 6,  /* Register d := global g. */
  ROP_SETGLOBAL = 7,  /* Global g := register s. */
  ROP_ENV = 8,  /* Register d := slot e of the current closure's environment. */
  ROP_SELF = 9,  /* Register d := the closure running. */
  ROP_CALL = 10,  /* Call the closure in register f with register x; RESULT takes what it returns. */
  ROP_RESULT = 11,  /* Register d := what the call or primitive before it left on the stack. */
  ROP_TAILCALL = 12,  /* Like CALL, but the current frame is replaced. */
  ROP_RET = 13,  /* Return register s to the caller. */
  ROP_PRIM = 14,  /* Register d := primitive p applied to the registers of args. */
  ROP_PRIMPUSH = 15,  /* Primitive p applied to the registers of args, its result left for RESULT: for one that saves or restores an image, which resumes at RESULT. */
  ROP_TUPLE = 16,  /* Register d := a tuple of the n registers of fields. */
  ROP_CLOSURE = 17,  /* Register d := a closure of function f capturing the n registers of env. */
  ROP_SELECT = 18,  /* Register d := field i of the tuple in register s. */
  ROP_CON = 19,  /* Register d := constructor t applied to register s. */
  ROP_DECON = 20,  /* Register d := the argument of the constructor value in register s. */
  ROP_CONTAG = 21,  /* Register d := the tag of the constructor value in register s, as an int. */
  ROP_NEWEXN = 22,  /* Register d := a fresh exception constructor named by string constant k. */
  ROP_BUILTINEXN = 23,  /* Register d := built-in exception constructor i (see docs/bytecode.md). */
  ROP_MKEXN = 24,  /* Register d := the exception of the constructor in register c and the payload in register x. */
  ROP_EXNCON = 25,  /* Register d := the constructor of the exception in register s. */
  ROP_EXNARG = 26,  /* Register d := the payload of the exception in register s. */
  ROP_SETENV = 27,  /* Slot e of the environment of the closure in register c := register v. */
  ROP_JUMP = 28,  /* Jump to absolute code offset o. */
  ROP_JUMPIF = 29,  /* Jump to o if register s holds true. */
  ROP_JUMPIFNOT = 30,  /* Jump to o if register s holds false. */
  ROP_JUMPIFNOTTAG = 31,  /* Jump to o unless the constructor value in register s has tag t. */
  ROP_PUSHHANDLER = 32,  /* Install an exception handler whose code starts at o, with CATCH. */
  ROP_POPHANDLER = 33,  /* Remove the innermost exception handler. */
  ROP_CATCH = 34,  /* Register d := the exception a raise left for the handler this begins. */
  ROP_RAISE = 35,  /* Raise the exception in register s. */
  ROP__COUNT
};

static const char *const rop_names[] = {
  "HALT",
  "MOVE",
  "INT",
  "CONST",
  "UNIT",
  "CON0",
  "GLOBAL",
  "SETGLOBAL",
  "ENV",
  "SELF",
  "CALL",
  "RESULT",
  "TAILCALL",
  "RET",
  "PRIM",
  "PRIMPUSH",
  "TUPLE",
  "CLOSURE",
  "SELECT",
  "CON",
  "DECON",
  "CONTAG",
  "NEWEXN",
  "BUILTINEXN",
  "MKEXN",
  "EXNCON",
  "EXNARG",
  "SETENV",
  "JUMP",
  "JUMPIF",
  "JUMPIFNOT",
  "JUMPIFNOTTAG",
  "PUSHHANDLER",
  "POPHANDLER",
  "CATCH",
  "RAISE",
};

/* how many operands come before the list, if there is one */
static const unsigned char rop_nfixed[] = {
  0,
  2,
  2,
  2,
  1,
  2,
  2,
  2,
  2,
  1,
  2,
  1,
  2,
  1,
  2,
  1,
  2,
  3,
  3,
  3,
  2,
  2,
  2,
  2,
  3,
  2,
  2,
  3,
  1,
  2,
  2,
  3,
  1,
  0,
  1,
  1,
};

/* the operand that says how long the list is (-1: no list), and
   whether it names a primitive, whose arity it is, or is a count */
static const signed char rop_list_at[] = {
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  0,
  0,
  1,
  2,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
};
static const unsigned char rop_list_prim[] = {
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
};

/* What each operand is (src/isa/regs.sml), which says what the
   loader accepts for it: the kinds of the stack bytecode and a
   register. */
enum RegOperandKind {
  RK_CONSTANT = 0,
  RK_STRING_CONSTANT = 1,
  RK_IMMEDIATE = 2,
  RK_TAG = 3,
  RK_LOCAL = 4,
  RK_ENV_SLOT = 5,
  RK_GLOBAL = 6,
  RK_FUNCTION = 7,
  RK_LABEL = 8,
  RK_HANDLER_LABEL = 9,
  RK_PRIMITIVE = 10,
  RK_COUNT = 11,
  RK_FIELD = 12,
  RK_BUILTIN_EXN = 13,
  RK_REGISTER = 14,
};

/* The kind of each operand before the list, by position; 0 past the last. */
static const unsigned char rop_kinds[][4] = {
  {0, 0, 0, 0},  /* HALT */
  {14, 14, 0, 0},  /* MOVE */
  {14, 2, 0, 0},  /* INT */
  {14, 0, 0, 0},  /* CONST */
  {14, 0, 0, 0},  /* UNIT */
  {14, 3, 0, 0},  /* CON0 */
  {14, 6, 0, 0},  /* GLOBAL */
  {6, 14, 0, 0},  /* SETGLOBAL */
  {14, 5, 0, 0},  /* ENV */
  {14, 0, 0, 0},  /* SELF */
  {14, 14, 0, 0},  /* CALL */
  {14, 0, 0, 0},  /* RESULT */
  {14, 14, 0, 0},  /* TAILCALL */
  {14, 0, 0, 0},  /* RET */
  {10, 14, 0, 0},  /* PRIM */
  {10, 0, 0, 0},  /* PRIMPUSH */
  {14, 11, 0, 0},  /* TUPLE */
  {14, 7, 11, 0},  /* CLOSURE */
  {14, 12, 14, 0},  /* SELECT */
  {14, 3, 14, 0},  /* CON */
  {14, 14, 0, 0},  /* DECON */
  {14, 14, 0, 0},  /* CONTAG */
  {14, 1, 0, 0},  /* NEWEXN */
  {14, 13, 0, 0},  /* BUILTINEXN */
  {14, 14, 14, 0},  /* MKEXN */
  {14, 14, 0, 0},  /* EXNCON */
  {14, 14, 0, 0},  /* EXNARG */
  {14, 5, 14, 0},  /* SETENV */
  {8, 0, 0, 0},  /* JUMP */
  {14, 8, 0, 0},  /* JUMPIF */
  {14, 8, 0, 0},  /* JUMPIFNOT */
  {14, 8, 3, 0},  /* JUMPIFNOTTAG */
  {9, 0, 0, 0},  /* PUSHHANDLER */
  {0, 0, 0, 0},  /* POPHANDLER */
  {14, 0, 0, 0},  /* CATCH */
  {14, 0, 0, 0},  /* RAISE */
};

#endif
