(* Examples that run (docs/plans/docgen.md, D10). An `Example:` paragraph
   shows code; a piece of it that is an equation, `e = v`, claims something
   that can be tried. Such an example is elaborated when the documentation is
   made, so that one that is no Standard ML, or not of an equality type, is an
   error at its comment; and the examples of a signature are written out as a
   program that tries each, which the test suite runs.

   The names of the signature's members are in scope, as they are inside a
   structure that implements it: the example is read under `open S`, where S
   is the structure with the shortest name among those that implement the
   signature (`Int` for `INTEGER`), and under `open S.Sub` as well for a
   member of a substructure. Another structure is named in full. *)
structure DocExamples =
struct
  structure I = DocIR
  structure T = DocText

  type example = {signat : string,
                  member : string,              (* with its substructures; "" for the signature itself *)
                  path : string list,           (* the substructures *)
                  code : string, span : Source.span}

  (* e = v, for the compiler's parser under the fixity of the top level *)
  fun isEquation (code : string) : bool =
    case DocHead.parseExp code of
      SOME (Ast.EApp (Ast.EVar (([], "="), _, _), Ast.ETuple ([_, _], _), _)) => true
    | _ => false

  fun ofDoc (signat, member, path, span) (doc : I.doc) : example list =
    List.concat
      (List.map (fn T.Reserved {keyword = "Example", body, ...} =>
                      List.mapPartial (fn T.Code c =>
                                            if isEquation c
                                            then SOME {signat = signat, member = member, path = path, code = c, span = span}
                                            else NONE
                                        | _ => NONE) body
                  | _ => [])
                doc)

  fun ofSignature (s : I.signatureRecord) : example list =
    ofDoc (#name s, "", [], #span s) (#doc s)
    @ List.concat (List.map (fn e : I.entryRecord =>
                               ofDoc (#name s, String.concatWith "." (#path e @ [#name e]), #path e, #span e) (#doc e))
                            (DocPage.entriesOf (#body s)))

  (* The structure whose members an example of the signature names: of those
     that implement it the one with the shortest name, and the first in the
     alphabet of several, among those the specification requires if there are
     any. So it is Int for INTEGER and not Int8 or LargeInt. *)
  fun structureOf (claims : DocClaims.claim list, statusOf : DocClaims.claim -> string) (signat : string) : string option =
    let
      val mine = List.filter (fn c : DocClaims.claim => #signat c = signat andalso not (#isFunctor c) andalso #origin c <> "inherited")
                             claims
      val required = List.filter (fn c => statusOf c = "required") mine
      fun better (a : string, b : string) =
        String.size a < String.size b orelse (String.size a = String.size b andalso a < b)
      fun best [] = NONE
        | best (c :: cs) = SOME (List.foldl (fn (x : DocClaims.claim, b) => if better (#name x, b) then #name x else b) (#name c) cs)
    in
      best (if List.null required then mine else required)
    end

  (* The example as an expression of type bool. *)
  fun expression (structure' : string option, {path, code, ...} : example) : string =
    case structure' of
      NONE => code
    | SOME s =>
        let
          fun prefixes ([], _) = []
            | prefixes (p :: ps, sofar) = (sofar ^ "." ^ p) :: prefixes (ps, sofar ^ "." ^ p)
        in
          "let open " ^ String.concatWith " " (s :: prefixes (path, s)) ^ " in " ^ code ^ " end"
        end

  fun nameOf ({signat, member, code, ...} : example) : string =
    signat ^ (if member = "" then "" else "." ^ member) ^ ": " ^ code

  (* The program that tries the examples of one signature: a line PASS or
     FAIL for each, and a status that says whether all hold. An example that
     raises an exception does not hold. *)
  fun program (signat : string, file : string, structure' : string option, examples : example list) : string =
    "(* The examples of the documentation of " ^ signat ^ " that are equations, as a program.\n"
    ^ "   Generated by runedoc from " ^ file ^ "; do not edit. *)\n"
    ^ "val failed = ref 0\n"
    ^ "fun example (name, holds) =\n"
    ^ "  if holds () handle _ => false then print (\"PASS \" ^ name ^ \"\\n\")\n"
    ^ "  else (print (\"FAIL \" ^ name ^ \"\\n\"); failed := !failed + 1)\n"
    ^ String.concat (List.map (fn e => "val () = example (\"" ^ String.toString (nameOf e) ^ "\",\n"
                                       ^ "  fn () => " ^ expression (structure', e) ^ ")\n")
                              examples)
    ^ "val () = if !failed = 0 then () else OS.Process.exit OS.Process.failure\n"
end
