#!/bin/sh
# Generate opcode/primitive tables for the VM (C) and the compiler (SML)
# from vm/opcodes.def and vm/prims.def.
set -eu
cd "$(dirname "$0")/.."

awk '
BEGIN { n = 0 }
/^[[:space:]]*#/ || /^[[:space:]]*$/ { next }
{
  name[n] = $1
  if ($2 == "-") nargs[n] = 0; else nargs[n] = split($2, tmp, ",")
  desc = ""; for (i = 3; i <= NF; i++) desc = desc (i > 3 ? " " : "") $i
  doc[n] = desc
  n++
}
END {
  h = "vm/opcodes.h"
  print "/* Generated by scripts/gen-opcodes.sh from vm/opcodes.def -- do not edit. */" > h
  print "#ifndef RUNE_OPCODES_H\n#define RUNE_OPCODES_H\n" > h
  print "enum Opcode {" > h
  for (i = 0; i < n; i++) printf("  OP_%s = %d,%s\n", name[i], i, "  /* " doc[i] " */") > h
  print "  OP__COUNT" > h
  print "};\n" > h
  print "static const char *const op_names[] = {" > h
  for (i = 0; i < n; i++) printf("  \"%s\",\n", name[i]) > h
  print "};\n" > h
  print "static const unsigned char op_nargs[] = {" > h
  for (i = 0; i < n; i++) printf("  %d,\n", nargs[i]) > h
  print "};\n\n#endif" > h

  s = "src/backend/opcodes.sml"
  print "(* Generated by scripts/gen-opcodes.sh from vm/opcodes.def -- do not edit. *)" > s
  print "structure Opcodes =\nstruct" > s
  for (i = 0; i < n; i++) printf("  val %s = %d\n", name[i], i) > s
  printf("  val count = %d\n", n) > s
  printf("  val names = Vector.fromList [") > s
  for (i = 0; i < n; i++) printf("%s\"%s\"", (i ? ", " : ""), name[i]) > s
  print "]" > s
  printf("  val nargs = Vector.fromList [") > s
  for (i = 0; i < n; i++) printf("%s%d", (i ? ", " : ""), nargs[i]) > s
  print "]\nend" > s
}' vm/opcodes.def

awk '
BEGIN { n = 0 }
/^[[:space:]]*#/ || /^[[:space:]]*$/ { next }
{
  name[n] = $1; arity[n] = $2; n++
}
END {
  h = "vm/prims_table.h"
  print "/* Generated by scripts/gen-opcodes.sh from vm/prims.def -- do not edit. */" > h
  print "#ifndef RUNE_PRIMS_TABLE_H\n#define RUNE_PRIMS_TABLE_H\n" > h
  print "enum Prim {" > h
  for (i = 0; i < n; i++) printf("  PRIM_%s = %d,\n", name[i], i) > h
  print "  PRIM__COUNT" > h
  print "};\n" > h
  print "static const char *const prim_names[] = {" > h
  for (i = 0; i < n; i++) printf("  \"%s\",\n", name[i]) > h
  print "};\n" > h
  print "static const unsigned char prim_arity[] = {" > h
  for (i = 0; i < n; i++) printf("  %d,\n", arity[i]) > h
  print "};\n" > h
  printf("#define RUNE_PRIM_LIST(X) \\\n") > h
  for (i = 0; i < n; i++) printf("  X(%s)%s\n", name[i], (i < n - 1 ? " \\" : "")) > h
  print "\n#endif" > h

  s = "src/backend/prims.sml"
  print "(* Generated by scripts/gen-opcodes.sh from vm/prims.def -- do not edit. *)" > s
  print "structure Prims =\nstruct" > s
  print "  (* (name, index, arity) *)" > s
  print "  val table : (string * int * int) list = [" > s
  for (i = 0; i < n; i++) printf("    (\"%s\", %d, %d)%s\n", name[i], i, arity[i], (i < n - 1 ? "," : "")) > s
  print "  ]" > s
  print "  fun find name =" > s
  print "    let fun go [] = NONE" > s
  print "          | go ((n, i, a) :: rest) = if n = name then SOME (i, a) else go rest" > s
  print "    in go table end" > s
  print "end" > s
}' vm/prims.def

echo "generated vm/opcodes.h vm/prims_table.h src/backend/opcodes.sml src/backend/prims.sml"
