#!/bin/sh
# Generate per-compiler build files from the source lists.
# Usage: scripts/gen-build-files.sh [ROOT_DIR]
# For every program (rune from sources.txt, runedoc from sources-doc.txt,
# runeopt from sources-opt.txt, runeisa from sources-isa.txt)
# produces build/PROG.mlb (MLton), build/PROG.cm (SML/NJ),
# build/PROG-polyml-build.sml (Poly/ML, run from ROOT; polyml-build.sml for
# rune) and, once, build/config.sml.
set -eu

root=${1:-$(pwd)}
cd "$root"
mkdir -p build

# gen PROG LIST MAINPREFIX POLYSCRIPT
gen() {
  prog=$1 list=$2 mainprefix=$3 polyscript=$4
  srcs=$(grep -v '^[[:space:]]*#' "$list" | grep -v '^[[:space:]]*$')

  # --- MLton ----------------------------------------------------------------
  {
    echo "(* Generated by scripts/gen-build-files.sh from $list -- do not edit. *)"
    echo '$(SML_LIB)/basis/basis.mlb'
    echo 'config.sml'
    # x64.sml's templates are a match over every opcode (Opcode.t): one left
    # out stops the build instead of the translation
    for f in $srcs; do
      case $f in
        src/opt/x64.sml) echo "ann \"nonexhaustiveMatch error\" in ../$f end" ;;
        *) echo "../$f" ;;
      esac
    done
    echo "../src/main/${mainprefix}mlton-main.sml"
  } > "build/$prog.mlb"

  # --- SML/NJ ---------------------------------------------------------------
  {
    echo "(* Generated by scripts/gen-build-files.sh from $list -- do not edit. *)"
    echo 'Group is'
    echo '  $/basis.cm'
    echo '  config.sml'
    for f in $srcs; do echo "  ../$f"; done
  } > "build/$prog.cm"

  # --- Poly/ML --------------------------------------------------------------
  {
    echo "(* Generated by scripts/gen-build-files.sh from $list -- do not edit. *)"
    echo '(* Run polyc from the repository root. *)'
    echo 'use "build/config.sml";'
    for f in $srcs; do echo "use \"$f\";"; done
    echo "use \"src/main/${mainprefix}polyml-main.sml\";"
  } > "build/$polyscript"
}

gen rune sources.txt "" polyml-build.sml
gen runedoc sources-doc.txt runedoc- runedoc-polyml-build.sml
gen runeopt sources-opt.txt runeopt- runeopt-polyml-build.sml
gen runeisa sources-isa.txt runeisa- runeisa-polyml-build.sml

# --- Config -----------------------------------------------------------------
# The one place the version is written. The compiler reads it from
# build/config.sml, the VM from vm/version.h, and `Runtime.version` is what the
# VM was built with, so the three cannot drift apart. scripts/check-docs.sh
# holds the manual pages to it.
version=0.3.0

cat > build/config.sml <<EOC
(* Generated by scripts/gen-build-files.sh -- do not edit. *)
structure Config =
struct
  val version = "$version"
end
EOC

cat > vm/version.h <<EOC
/* Generated by scripts/gen-build-files.sh -- do not edit. */
#ifndef RUNE_VERSION_H
#define RUNE_VERSION_H
#define RUNE_VERSION "$version"
#endif
EOC

echo "generated build/rune.mlb build/rune.cm build/polyml-build.sml build/runedoc.mlb build/runedoc.cm build/runedoc-polyml-build.sml build/runeopt.mlb build/runeopt.cm build/runeopt-polyml-build.sml build/runeisa.mlb build/runeisa.cm build/runeisa-polyml-build.sml build/config.sml vm/version.h"
