#!/bin/sh
# Generate per-compiler build files from sources.txt.
# Usage: scripts/gen-build-files.sh [ROOT_DIR]
# Produces build/rune.mlb (MLton), build/rune.cm (SML/NJ),
# build/polyml-build.sml (Poly/ML, run from ROOT) and build/config.sml.
set -eu

root=${1:-$(pwd)}
libdir=${RUNE_LIB:-$root/lib}
cd "$root"
mkdir -p build

srcs=$(grep -v '^[[:space:]]*#' sources.txt | grep -v '^[[:space:]]*$')

# --- MLton ------------------------------------------------------------------
{
  echo '(* Generated by scripts/gen-build-files.sh from sources.txt -- do not edit. *)'
  echo '$(SML_LIB)/basis/basis.mlb'
  echo 'config.sml'
  for f in $srcs; do echo "../$f"; done
  echo '../src/main/mlton-main.sml'
} > build/rune.mlb

# --- SML/NJ -----------------------------------------------------------------
{
  echo '(* Generated by scripts/gen-build-files.sh from sources.txt -- do not edit. *)'
  echo 'Group is'
  echo '  $/basis.cm'
  echo '  config.sml'
  for f in $srcs; do echo "  ../$f"; done
} > build/rune.cm

# --- Poly/ML ----------------------------------------------------------------
{
  echo '(* Generated by scripts/gen-build-files.sh from sources.txt -- do not edit. *)'
  echo '(* Run polyc from the repository root. *)'
  echo 'use "build/config.sml";'
  for f in $srcs; do echo "use \"$f\";"; done
  echo 'use "src/main/polyml-main.sml";'
} > build/polyml-build.sml

# --- Config -----------------------------------------------------------------
cat > build/config.sml <<EOF
(* Generated by scripts/gen-build-files.sh -- do not edit. *)
structure Config =
struct
  val version = "0.2.0"
  val defaultLibDir = "$libdir"
end
EOF

echo "generated build/rune.mlb build/rune.cm build/polyml-build.sml build/config.sml (lib=$libdir)"
