#!/bin/sh
# Make the signatures of the specification part of the basis library: every
# signature SPEC_<SIG> transcribed in tests/basis/spec-sigs becomes a file
# lib/basis/sig_<sig>.sml declaring signature <SIG>, loaded on demand like the
# structures, and a block of lib/basis/MANIFEST lists them.
#   scripts/gen-basis-sigs.sh [--check] [LIBDIR]
# LIBDIR defaults to lib; --check changes nothing and fails when a file or the
# block differs from what would be generated (make check-docs runs it).
#
# The transcriptions stay the source: they are written from the pages of the
# specification independently of lib/basis, and the suite matches Rune's
# structures against them. Left out: the partial transcriptions (*_IMP), and
# signatures that lib/basis declares itself because its structures are sealed
# with them (WORD, PRIM_IO, STREAM_IO, the MONO_* ones).
set -u
check=0
[ "${1:-}" = --check ] && { check=1; shift; }
cd "$(dirname "$0")/.."
lib=${1:-lib}
basis=$lib/basis
manifest=$basis/MANIFEST
begin='# ---- the signatures of the specification (scripts/gen-basis-sigs.sh)'
end='# ---- end of the signatures'
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT HUP INT TERM
status=0

# The MANIFEST without the generated block, and the names its files provide.
awk -v b="$begin" -v e="$end" '$0 == b { skip = 1; next } $0 == e { skip = 0; next } !skip' "$manifest" > "$tmp/manifest.base"
awk -F '|' '!/^[[:space:]]*(#|$)/ { n = split($4, p, " "); for (i = 1; i <= n; i++) print p[i] }' "$tmp/manifest.base" | sort -u > "$tmp/provided"
# The signatures lib/basis declares itself (a structure and a signature can
# have the same name, IO and OS: only these count).
for f in $(awk -F '|' '!/^[[:space:]]*(#|$)/ { gsub(/ /, "", $1); print $1 }' "$tmp/manifest.base"); do
  case "$f" in sig_*) continue ;; esac
  sed -n 's/^signature \([A-Z0-9_]*\).*/\1/p' "$basis/$f"
done | sort -u > "$tmp/own"

# The files to generate: SIG and the transcription it comes from.
: > "$tmp/sigs"
for f in tests/basis/spec-sigs/*.sml; do
  case "$f" in *_IMP.sml) continue ;; esac
  for s in $(sed -n 's/^signature SPEC_\([A-Z0-9_]*\).*/\1/p' "$f"); do
    grep -q -x "$s" "$tmp/own" && continue
    printf '%s %s\n' "$s" "$f" >> "$tmp/sigs"
  done
done
cut -d ' ' -f 1 "$tmp/sigs" | sort -u > "$tmp/generated"
cat "$tmp/provided" "$tmp/generated" | sort -u > "$tmp/all"

# Write each file, and find what it requires: the names in it that another
# file provides, heads of long identifiers only, as the loader counts them (a
# signature's own name excepted).
mkdir -p "$tmp/out"
: > "$tmp/edges"
: > "$tmp/lines"
while read -r sig src; do
  name=sig_$(echo "$sig" | tr 'A-Z' 'a-z').sml
  {
    echo "(* Generated by scripts/gen-basis-sigs.sh from $src; do not edit. *)"
    sed 's/SPEC_\([A-Z0-9_]*\)/\1/g' "$src"
  } > "$tmp/out/$name"
  # identifiers, and the heads of long identifiers, outside comments
  requires=$(sed 's/SPEC_\([A-Z0-9_]*\)/\1/g' "$src" |
    awk '{ line = $0; out = "";
           while (length(line) > 0) {
             if (depth == 0 && substr(line, 1, 2) == "(*") { depth = 1; line = substr(line, 3); continue }
             if (depth > 0) {
               if (substr(line, 1, 2) == "(*") { depth++; line = substr(line, 3); continue }
               if (substr(line, 1, 2) == "*)") { depth--; line = substr(line, 3); continue }
               line = substr(line, 2); continue
             }
             out = out substr(line, 1, 1); line = substr(line, 2)
           }
           print out }' |
    grep -o "[A-Za-z][A-Za-z0-9_']*\(\.[A-Za-z][A-Za-z0-9_']*\)*" | sed 's/\..*//' |
    sort -u | grep -x -F -f "$tmp/all" | grep -v -x "$sig" | tr '\n' ' ')
  printf '%s | demand | yes  | %s | %s\n' "$name" "$sig" "$requires" | sed 's/ *$//' >> "$tmp/lines"
  echo "$sig $sig" >> "$tmp/edges"
  for r in $requires; do
    grep -q -x "$r" "$tmp/generated" && echo "$r $sig" >> "$tmp/edges"
  done
done < "$tmp/sigs"

# The block, in an order where a signature comes after those it names.
{
  echo "$begin"
  for sig in $(tsort "$tmp/edges"); do
    grep "| $sig |" "$tmp/lines"
  done
  echo "$end"
} > "$tmp/block"
# The block goes before the files compiled after the program.
awk -v blockfile="$tmp/block" '
  !done && /^[^#]*\| *final *\|/ { while ((getline l < blockfile) > 0) print l; done = 1 }
  { print }
  END { if (!done) while ((getline l < blockfile) > 0) print l }
' "$tmp/manifest.base" > "$tmp/manifest.new"

if [ $check = 1 ]; then
  cmp -s "$tmp/manifest.new" "$manifest" || { echo "gen-basis-sigs: $manifest is not up to date (run scripts/gen-basis-sigs.sh)"; status=1; }
  for f in "$tmp"/out/*.sml; do
    [ -f "$f" ] || continue
    cmp -s "$f" "$basis/$(basename "$f")" || { echo "gen-basis-sigs: $basis/$(basename "$f") is not up to date (run scripts/gen-basis-sigs.sh)"; status=1; }
  done
  for f in "$basis"/sig_*.sml; do
    [ -f "$f" ] || continue
    [ -f "$tmp/out/$(basename "$f")" ] || { echo "gen-basis-sigs: $f has no transcription any more (run scripts/gen-basis-sigs.sh)"; status=1; }
  done
  [ $status = 0 ] && echo "gen-basis-sigs: OK ($(wc -l < "$tmp/generated" | tr -d ' ') signatures)"
  exit $status
fi
rm -f "$basis"/sig_*.sml
cp "$tmp"/out/*.sml "$basis"/ 2> /dev/null
cp "$tmp/manifest.new" "$manifest"
echo "gen-basis-sigs: $(wc -l < "$tmp/generated" | tr -d ' ') signatures in $basis"
