#!/bin/sh
# Write the version into build/config.sml, for the compiler, and
# runtime/version.h, for the VM.
# Usage: scripts/gen-version.sh [ROOT_DIR]
#
# git decides the version: the name of the tag that points at HEAD, or else
# HEAD's abbreviated hash, with -dirty after it when a tracked file differs
# from HEAD (untracked files do not count, as with `git describe --dirty`;
# git leaves the index alone, which a copy of the tree may share).
# Without git or a repository (a tarball, a copy without .git) the files keep
# the version they have, or say "unknown" when there are none.
#
# The Makefile runs this on every make, so a file is written only when what
# it says changes: its time stays put and nothing is rebuilt for nothing.
# `Runtime.version` is what the VM was built with, so the compiler, the VM and
# the library cannot drift apart. scripts/install.sh writes it into the
# manual pages.
set -eu

root=${1:-$(pwd)}
cd "$root"
mkdir -p build

if version=$(git describe --tags --exact-match HEAD 2> /dev/null) ||
   version=$(git rev-parse --short HEAD 2> /dev/null); then
  status=0
  git --no-optional-locks diff --quiet HEAD -- 2> /dev/null || status=$?
  [ "$status" -ne 1 ] || version=$version-dirty
elif [ -f build/config.sml ] && [ -f runtime/version.h ]; then
  exit 0
else
  version=unknown
fi

# update FILE: FILE.tmp becomes FILE, unless the two are the same
update() {
  if cmp -s "$1.tmp" "$1"; then rm -f "$1.tmp"; else mv "$1.tmp" "$1"; fi
}

cat > build/config.sml.tmp <<EOC
(* Generated by scripts/gen-version.sh -- do not edit. *)
structure Config =
struct
  val version = "$version"
end
EOC
update build/config.sml

cat > runtime/version.h.tmp <<EOC
/* Generated by scripts/gen-version.sh -- do not edit. */
#ifndef RUNE_VERSION_H
#define RUNE_VERSION_H
#define RUNE_VERSION "$version"
#endif
EOC
update runtime/version.h
