#!/usr/bin/env python3
"""Maintain checked-in opcode definitions, support tables, and example inclusions."""
import csv
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def rows(path):
    with (ROOT / path).open(newline="") as f:
        return list(csv.DictReader(f, delimiter="\t"))


def products():
    ops = rows("spec/opcodes.tsv")
    assert [int(x["code"]) for x in ops] == list(range(len(ops)))
    sml = "(* Generated by scripts/generate.py; edit spec/opcodes.tsv. *)\nstructure Opcode =\nstruct\n"
    for op in ops:
        sml += f'  val {op["name"]} = {op["code"]}\n'
    sml += '  val names = Vector.fromList [' + ', '.join('"' + x['name'] + '"' for x in ops) + ']\n'
    sml += '  val operands = Vector.fromList [' + ', '.join('"' + x['operand'] + '"' for x in ops) + ']\nend\n'
    c = "/* Generated by scripts/generate.py; edit spec/opcodes.tsv. */\n"
    c += "enum {\n" + "".join(f'    OP_{x["name"]} = {x["code"]},\n' for x in ops) + f'    OP_COUNT = {len(ops)}\n}};\n'
    kinds = ["none", "int", "bool", "constant", "builtin", "local", "target", "environment", "function", "arity", "index"]
    c += "enum { " + ", ".join("ARG_" + k.upper() for k in kinds) + " };\n"
    c += "static const unsigned char op_arg[] = {" + ",".join("ARG_" + x['operand'].upper() for x in ops) + "};\n"
    for name in ("pops", "pushes"):
        c += f'static const signed char op_{name}[] = {{' + ",".join(x[name] for x in ops) + "};\n"
    yield "src/opcode.sml", sml
    yield "vm/opcode.h", c
    table = "| Code | Instruction | Operand | Pops | Pushes |\n| --- | --- | --- | --- | --- |\n"
    table += "".join(f'| {x["code"]} | {x["name"]} | {x["operand"]} | {x["pops"]} | {x["pushes"]} |\n' for x in ops)
    doc = (ROOT / "docs/BYTECODE.md").read_text()
    yield "docs/BYTECODE.md", replace(doc, "opcodes", table)
    feature_path = ROOT / "docs/features.tsv"
    if feature_path.exists():
        features = rows("docs/features.tsv")
        table = "| ID | Feature | Status | Target | Boundary |\n| --- | --- | --- | --- | --- |\n"
        table += "".join(f'| {x["id"]} | {x["feature"]} | {x["status"]} | {x["target"]} | {x["boundary"]} |\n' for x in features)
        doc = replace((ROOT / "docs/LANGUAGE.md").read_text(), "features", table)
        for path in re.findall(r'<!-- example:([^ ]+):start -->', doc):
            code = (ROOT / path).read_text()
            doc = replace(doc, "example:" + path, "```sml\n" + code + "```\n")
        yield "docs/LANGUAGE.md", doc


def replace(text, name, body):
    start, end = f"<!-- {name}:start -->", f"<!-- {name}:end -->"
    assert text.count(start) == text.count(end) == 1, name
    before, rest = text.split(start)
    _, after = rest.split(end)
    return before + start + "\n" + body + end + after


def main():
    check = "--check" in sys.argv
    stale = []
    for name, content in products():
        path = ROOT / name
        if not path.exists() or path.read_text() != content:
            if check:
                stale.append(name)
            else:
                path.write_text(content)
    if stale:
        raise SystemExit("Generated files are stale; run make generate:\n" + "\n".join(stale))


if __name__ == "__main__":
    main()
