(* Generated by scripts/generate.py; edit spec/opcodes.tsv. *)
structure Opcode =
struct
  val HALT = 0
  val INT = 1
  val BOOL = 2
  val UNIT = 3
  val STRING = 4
  val BUILTIN = 5
  val LOAD = 6
  val STORE = 7
  val POP = 8
  val ADD = 9
  val SUB = 10
  val MUL = 11
  val DIV = 12
  val MOD = 13
  val CONCAT = 14
  val EQ = 15
  val NE = 16
  val LT = 17
  val LE = 18
  val GT = 19
  val GE = 20
  val CALL = 21
  val JUMP = 22
  val JUMP_FALSE = 23
  val names = Vector.fromList ["HALT", "INT", "BOOL", "UNIT", "STRING", "BUILTIN", "LOAD", "STORE", "POP", "ADD", "SUB", "MUL", "DIV", "MOD", "CONCAT", "EQ", "NE", "LT", "LE", "GT", "GE", "CALL", "JUMP", "JUMP_FALSE"]
  val operands = Vector.fromList ["none", "int", "bool", "none", "constant", "builtin", "local", "local", "none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "target", "target"]
end
